// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type Append struct {
	_tab flatbuffers.Table
}

func GetRootAsAppend(buf []byte, offset flatbuffers.UOffsetT) *Append {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Append{}
	x.Init(buf, n+offset)
	return x
}

func FinishAppendBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAppend(buf []byte, offset flatbuffers.UOffsetT) *Append {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Append{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAppendBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Append) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Append) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Append) ClientSeq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Append) MutateClientSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Append) Events(obj *AppendEvent, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Append) EventsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AppendStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AppendAddClientSeq(builder *flatbuffers.Builder, clientSeq uint64) {
	builder.PrependUint64Slot(0, clientSeq, 0)
}
func AppendAddEvents(builder *flatbuffers.Builder, events flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(events), 0)
}
func AppendStartEventsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AppendEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
