// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type CheckpointResult struct {
	_tab flatbuffers.Table
}

func GetRootAsCheckpointResult(buf []byte, offset flatbuffers.UOffsetT) *CheckpointResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CheckpointResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishCheckpointResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCheckpointResult(buf []byte, offset flatbuffers.UOffsetT) *CheckpointResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CheckpointResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCheckpointResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CheckpointResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CheckpointResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CheckpointResult) Present() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CheckpointResult) MutatePresent(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *CheckpointResult) Lsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CheckpointResult) MutateLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *CheckpointResult) Blob(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *CheckpointResult) BlobLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CheckpointResult) BlobBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CheckpointResult) MutateBlob(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func CheckpointResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func CheckpointResultAddPresent(builder *flatbuffers.Builder, present bool) {
	builder.PrependBoolSlot(0, present, false)
}
func CheckpointResultAddLsn(builder *flatbuffers.Builder, lsn uint64) {
	builder.PrependUint64Slot(1, lsn, 0)
}
func CheckpointResultAddBlob(builder *flatbuffers.Builder, blob flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(blob), 0)
}
func CheckpointResultStartBlobVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func CheckpointResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
