// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type CheckpointAck struct {
	_tab flatbuffers.Table
}

func GetRootAsCheckpointAck(buf []byte, offset flatbuffers.UOffsetT) *CheckpointAck {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CheckpointAck{}
	x.Init(buf, n+offset)
	return x
}

func FinishCheckpointAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCheckpointAck(buf []byte, offset flatbuffers.UOffsetT) *CheckpointAck {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CheckpointAck{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCheckpointAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CheckpointAck) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CheckpointAck) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CheckpointAck) Lsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CheckpointAck) MutateLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func CheckpointAckStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CheckpointAckAddLsn(builder *flatbuffers.Builder, lsn uint64) {
	builder.PrependUint64Slot(0, lsn, 0)
}
func CheckpointAckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
