// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type DeleteResult struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteResult(buf []byte, offset flatbuffers.UOffsetT) *DeleteResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeleteResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeleteResult(buf []byte, offset flatbuffers.UOffsetT) *DeleteResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeleteResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeleteResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeleteResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteResult) Actor() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DeleteResult) MutateActor(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *DeleteResult) Receipt(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *DeleteResult) ReceiptLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DeleteResult) ReceiptBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DeleteResult) MutateReceipt(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func DeleteResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DeleteResultAddActor(builder *flatbuffers.Builder, actor uint16) {
	builder.PrependUint16Slot(0, actor, 0)
}
func DeleteResultAddReceipt(builder *flatbuffers.Builder, receipt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(receipt), 0)
}
func DeleteResultStartReceiptVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func DeleteResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
