// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type Health struct {
	_tab flatbuffers.Table
}

func GetRootAsHealth(buf []byte, offset flatbuffers.UOffsetT) *Health {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Health{}
	x.Init(buf, n+offset)
	return x
}

func FinishHealthBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHealth(buf []byte, offset flatbuffers.UOffsetT) *Health {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Health{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHealthBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Health) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Health) Table() flatbuffers.Table {
	return rcv._tab
}

func HealthStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func HealthEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
