// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type LatencyHistograms struct {
	_tab flatbuffers.Table
}

func GetRootAsLatencyHistograms(buf []byte, offset flatbuffers.UOffsetT) *LatencyHistograms {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LatencyHistograms{}
	x.Init(buf, n+offset)
	return x
}

func FinishLatencyHistogramsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLatencyHistograms(buf []byte, offset flatbuffers.UOffsetT) *LatencyHistograms {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LatencyHistograms{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLatencyHistogramsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LatencyHistograms) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LatencyHistograms) Table() flatbuffers.Table {
	return rcv._tab
}

func LatencyHistogramsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func LatencyHistogramsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
