// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type ProjectionStat struct {
	_tab flatbuffers.Table
}

func GetRootAsProjectionStat(buf []byte, offset flatbuffers.UOffsetT) *ProjectionStat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProjectionStat{}
	x.Init(buf, n+offset)
	return x
}

func FinishProjectionStatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsProjectionStat(buf []byte, offset flatbuffers.UOffsetT) *ProjectionStat {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProjectionStat{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedProjectionStatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ProjectionStat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProjectionStat) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProjectionStat) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ProjectionStat) AppliedLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProjectionStat) MutateAppliedLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func ProjectionStatStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ProjectionStatAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func ProjectionStatAddAppliedLsn(builder *flatbuffers.Builder, appliedLsn uint64) {
	builder.PrependUint64Slot(1, appliedLsn, 0)
}
func ProjectionStatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
