// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type RebuildProjection struct {
	_tab flatbuffers.Table
}

func GetRootAsRebuildProjection(buf []byte, offset flatbuffers.UOffsetT) *RebuildProjection {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RebuildProjection{}
	x.Init(buf, n+offset)
	return x
}

func FinishRebuildProjectionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRebuildProjection(buf []byte, offset flatbuffers.UOffsetT) *RebuildProjection {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RebuildProjection{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRebuildProjectionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RebuildProjection) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RebuildProjection) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RebuildProjection) Actor() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RebuildProjection) MutateActor(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *RebuildProjection) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RebuildProjectionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RebuildProjectionAddActor(builder *flatbuffers.Builder, actor uint16) {
	builder.PrependUint16Slot(0, actor, 0)
}
func RebuildProjectionAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func RebuildProjectionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
