// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type Recall struct {
	_tab flatbuffers.Table
}

func GetRootAsRecall(buf []byte, offset flatbuffers.UOffsetT) *Recall {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Recall{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecallBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRecall(buf []byte, offset flatbuffers.UOffsetT) *Recall {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Recall{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecallBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Recall) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Recall) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Recall) Query(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Recall) QueryLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Recall) QueryBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Recall) MutateQuery(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Recall) Limit() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Recall) MutateLimit(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Recall) Mode() RecallMode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return RecallMode(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Recall) MutateMode(n RecallMode) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *Recall) Level() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Recall) MutateLevel(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *Recall) StartNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Recall) MutateStartNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *Recall) EndNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Recall) MutateEndNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func RecallStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func RecallAddQuery(builder *flatbuffers.Builder, query flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(query), 0)
}
func RecallStartQueryVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RecallAddLimit(builder *flatbuffers.Builder, limit uint32) {
	builder.PrependUint32Slot(1, limit, 0)
}
func RecallAddMode(builder *flatbuffers.Builder, mode RecallMode) {
	builder.PrependByteSlot(2, byte(mode), 0)
}
func RecallAddLevel(builder *flatbuffers.Builder, level byte) {
	builder.PrependByteSlot(3, level, 0)
}
func RecallAddStartNs(builder *flatbuffers.Builder, startNs int64) {
	builder.PrependInt64Slot(4, startNs, 0)
}
func RecallAddEndNs(builder *flatbuffers.Builder, endNs int64) {
	builder.PrependInt64Slot(5, endNs, 0)
}
func RecallEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
