// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type Transcript struct {
	_tab flatbuffers.Table
}

func GetRootAsTranscript(buf []byte, offset flatbuffers.UOffsetT) *Transcript {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Transcript{}
	x.Init(buf, n+offset)
	return x
}

func FinishTranscriptBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTranscript(buf []byte, offset flatbuffers.UOffsetT) *Transcript {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Transcript{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTranscriptBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Transcript) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Transcript) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Transcript) Conversation(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Transcript) ConversationLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Transcript) ConversationBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Transcript) MutateConversation(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Transcript) SinceLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Transcript) MutateSinceLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Transcript) Limit() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Transcript) MutateLimit(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func TranscriptStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TranscriptAddConversation(builder *flatbuffers.Builder, conversation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(conversation), 0)
}
func TranscriptStartConversationVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TranscriptAddSinceLsn(builder *flatbuffers.Builder, sinceLsn uint64) {
	builder.PrependUint64Slot(1, sinceLsn, 0)
}
func TranscriptAddLimit(builder *flatbuffers.Builder, limit uint32) {
	builder.PrependUint32Slot(2, limit, 0)
}
func TranscriptEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
