// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type TranscriptResult struct {
	_tab flatbuffers.Table
}

func GetRootAsTranscriptResult(buf []byte, offset flatbuffers.UOffsetT) *TranscriptResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TranscriptResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishTranscriptResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTranscriptResult(buf []byte, offset flatbuffers.UOffsetT) *TranscriptResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TranscriptResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTranscriptResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TranscriptResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TranscriptResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TranscriptResult) Records(obj *FrameRecord, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TranscriptResult) RecordsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TranscriptResult) Truncated() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TranscriptResult) MutateTruncated(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func TranscriptResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TranscriptResultAddRecords(builder *flatbuffers.Builder, records flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(records), 0)
}
func TranscriptResultStartRecordsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TranscriptResultAddTruncated(builder *flatbuffers.Builder, truncated bool) {
	builder.PrependBoolSlot(1, truncated, false)
}
func TranscriptResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
