// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type VerifyStatus struct {
	_tab flatbuffers.Table
}

func GetRootAsVerifyStatus(buf []byte, offset flatbuffers.UOffsetT) *VerifyStatus {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VerifyStatus{}
	x.Init(buf, n+offset)
	return x
}

func FinishVerifyStatusBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVerifyStatus(buf []byte, offset flatbuffers.UOffsetT) *VerifyStatus {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VerifyStatus{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVerifyStatusBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VerifyStatus) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VerifyStatus) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VerifyStatus) Actor() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VerifyStatus) MutateActor(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func VerifyStatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VerifyStatusAddActor(builder *flatbuffers.Builder, actor uint16) {
	builder.PrependUint16Slot(0, actor, 0)
}
func VerifyStatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
