// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type Welcome struct {
	_tab flatbuffers.Table
}

func GetRootAsWelcome(buf []byte, offset flatbuffers.UOffsetT) *Welcome {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Welcome{}
	x.Init(buf, n+offset)
	return x
}

func FinishWelcomeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWelcome(buf []byte, offset flatbuffers.UOffsetT) *Welcome {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Welcome{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWelcomeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Welcome) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Welcome) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Welcome) ProtoVersion() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Welcome) MutateProtoVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *Welcome) ActorNs() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Welcome) MutateActorNs(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *Welcome) Admin() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Welcome) MutateAdmin(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *Welcome) MaximumFrameBytes() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Welcome) MutateMaximumFrameBytes(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *Welcome) MaximumBatchEvents() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Welcome) MutateMaximumBatchEvents(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *Welcome) MaximumSubscriptions() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Welcome) MutateMaximumSubscriptions(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *Welcome) NextClientSeq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Welcome) MutateNextClientSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func WelcomeStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func WelcomeAddProtoVersion(builder *flatbuffers.Builder, protoVersion uint16) {
	builder.PrependUint16Slot(0, protoVersion, 0)
}
func WelcomeAddActorNs(builder *flatbuffers.Builder, actorNs uint16) {
	builder.PrependUint16Slot(1, actorNs, 0)
}
func WelcomeAddAdmin(builder *flatbuffers.Builder, admin bool) {
	builder.PrependBoolSlot(2, admin, false)
}
func WelcomeAddMaximumFrameBytes(builder *flatbuffers.Builder, maximumFrameBytes uint32) {
	builder.PrependUint32Slot(3, maximumFrameBytes, 0)
}
func WelcomeAddMaximumBatchEvents(builder *flatbuffers.Builder, maximumBatchEvents uint32) {
	builder.PrependUint32Slot(4, maximumBatchEvents, 0)
}
func WelcomeAddMaximumSubscriptions(builder *flatbuffers.Builder, maximumSubscriptions uint32) {
	builder.PrependUint32Slot(5, maximumSubscriptions, 0)
}
func WelcomeAddNextClientSeq(builder *flatbuffers.Builder, nextClientSeq uint64) {
	builder.PrependUint64Slot(6, nextClientSeq, 0)
}
func WelcomeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
