/* eslint-disable */
// Code generated by `construct codegen`; DO NOT EDIT.
//
// TypeScript mirror of the Construct wire schema. The Go structs in
// packages/construct/schema (+ schema/primitives) are the single source of truth; this
// file is regenerated by `go run ./cmd/construct codegen` and checked for
// drift by `go run ./cmd/construct codegen --check`. Edit the Go schema, not
// this file. See construct/construct.frozen.kvx for the frozen vocabulary.

export type Kind =
  | 'narration'
  | 'metric'
  | 'entity'
  | 'structure'
  | 'stream'
  | 'timeline'
  | 'canvas'
  | 'ask'

export type Stakes = 'fact' | 'hypothesis' | 'decision' | 'irreversible'

export type Temporality = 'point' | 'stream' | 'persistent'

export type NarrationRole = 'thinking' | 'intent' | 'answer'

export type Trend = 'up' | 'down' | 'flat'

export type MetricDisplay = 'plain' | 'bar' | 'gauge'

export type AffordanceKind = 'link' | 'ask' | 'copy'

export type Shape = 'list' | 'table' | 'tree'

export type StepStatus = 'pending' | 'running' | 'done' | 'failed'

export type MediaKind = 'image' | 'video' | 'audio' | 'page' | 'chart'

export type ChartKind = 'area' | 'bar' | 'line' | 'pie' | 'radar' | 'scatter'

export type AskKind = 'choose' | 'input' | 'confirm' | 'sign' | 'upload'

export interface Cost {
  amount: number
  unit?: string
  cap?: number
}

export interface Attributes {
  stakes?: Stakes
  confidence?: number
  cost?: Cost
  temporality?: Temporality
}

export interface Narration {
  text: string
  role?: NarrationRole
}

export interface MetricThreshold {
  warn?: number
  limit?: number
  direction?: string
}

export interface Metric {
  label: string
  value: string
  unit?: string
  magnitude?: number
  scale?: string
  trend?: Trend
  display?: MetricDisplay
  threshold?: MetricThreshold
}

export interface EntityField {
  key: string
  value: string
  ref?: string
}

export interface Affordance {
  id: string
  label: string
  kind?: AffordanceKind
  href?: string
  ask_ref?: string
}

export interface Entity {
  type: string
  identity: string
  label?: string
  fields?: EntityField[]
  affordances?: Affordance[]
}

export interface StructureNode {
  id?: string
  label?: string
  ref?: string
  cells?: Record<string, string>
  children?: StructureNode[]
}

export interface Structure {
  shape: Shape
  columns?: string[]
  records: StructureNode[]
}

export interface StreamChunk {
  seq: number
  text: string
  channel?: string
}

export interface Stream {
  source?: string
  title?: string
  chunks?: StreamChunk[]
  closed?: boolean
}

export interface TimelineStep {
  id: string
  label: string
  status: StepStatus
  detail?: string
  ref?: string
}

export interface Timeline {
  title?: string
  steps: TimelineStep[]
}

export interface CanvasMedia {
  kind: MediaKind
  url?: string
  mime?: string
  alt?: string
}

export interface ChartSeries {
  key: string
  name?: string
  color?: string
}

export interface ChartPoint {
  label?: string
  values: Record<string, number>
}

export interface Chart {
  kind: ChartKind
  series?: ChartSeries[]
  points: ChartPoint[]
  x_label?: string
  y_label?: string
  stacked?: boolean
}

export interface CanvasRegion {
  id: string
  label?: string
  x: number
  y: number
  w: number
  h: number
  ask_ref?: string
}

export interface Canvas {
  media: CanvasMedia
  chart?: Chart
  caption?: string
  regions?: CanvasRegion[]
}

export interface AskOption {
  id: string
  label: string
}

export interface AskResponse {
  choice?: string
  value?: string
  confirmed?: boolean
  signature?: string
  upload_ref?: string
  answered_at?: string
}

export interface Ask {
  ask_kind: AskKind
  prompt: string
  options?: AskOption[]
  expected?: string
  required?: boolean
  response?: AskResponse
}

export interface Surface {
  kind: Kind
  id: string
  ref?: string
  seq?: number
  parent?: string
  attributes?: Attributes
  narration?: Narration
  metric?: Metric
  entity?: Entity
  structure?: Structure
  stream?: Stream
  timeline?: Timeline
  canvas?: Canvas
  ask?: Ask
}

export interface Frame {
  seq: number
  ts: string
  phase: string
  type: string
  fields?: Record<string, unknown>
}

export interface StateResponse {
  conversation_id: string
  frames: Frame[]
  last_seq: number
}
