#!/usr/bin/env node
// uwac — MCP stdio proxy bridging Matrix agents to the SHARED UWAC control
// plane (uwacd: the OAuth connector hub + token vault). Same shape as
// tools/tachyon/tachyon.mjs: the daemon spawns this over stdio and it forwards
// tools/call to uwacd's REST lane (POST {MATRIX_UWAC_URL}/v1/invoke).
//
// Boot decoupling: initialize/tools/list are answered LOCALLY from the static
// registry baked alongside this file (uwac-tools.json, generated by
// `uwacd -dump-tools`). uwacd is contacted lazily on the first tools/call, so
// an unreachable control plane never bricks daemon boot — uwac tools just
// return a structured error until uwacd is reachable.
//
// Two-layer auth (connections.frozen.kvx [credential_flow]):
//   transport  — shared MATRIX_UWAC_TOKEN -> `Authorization: Bearer <tok>`
//   principal  — per-owner agent-DID token minted from the daemon's ed25519
//                executor key (challenge/verify against uwacd's own lane) ->
//                `X-UWAC-Agent: <token>`. uwacd resolves owner_user_id from the
//                DID label (the Supabase user UUID), scoping the vault lookup.
// The OAuth token NEVER reaches the daemon; uwacd injects it server-side.
//
// Env:
//   MATRIX_UWAC_URL          base URL (e.g. http://matrix-uwac.internal:8646)
//   MATRIX_UWAC_TOKEN        shared transport bearer (optional in dev)
//   MATRIX_UWAC_TIMEOUT_MS   per-call timeout (default 30000)
//   Agent identity (reused from the daemon, no extra wiring in hosted mode):
//     UWAC_AGENT_KEYFILE | MATRIX_EXECUTOR_KEYFILE | ${MATRIX_DATA_DIR|/data}/.matrix/executor.key
//     MATRIX_USER_ID | UWAC_AGENT_LABEL | MATRIX_DID_LABEL   (must be the owner uuid)
//     UWAC_AGENT_AUTH_DISABLE=1 to disable principal-token minting.
//
// Run `node tools/uwac/uwac.mjs --selftest` to smoke it offline (drift guard).

import { createInterface } from 'node:readline'
import { readdirSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import { createPrivateKey, createPublicKey, sign as edSign } from 'node:crypto'

const SERVER_NAME = 'uwac'
const SERVER_VERSION = '0.1.0'
const PROTOCOL_VERSION = '2024-11-05'

const REMOTE_URL = (process.env.MATRIX_UWAC_URL || '').trim().replace(/\/+$/, '')
const REMOTE_TOKEN = (process.env.MATRIX_UWAC_TOKEN || '').trim()
const TIMEOUT_MS = clampInt(process.env.MATRIX_UWAC_TIMEOUT_MS, 30000, 2000, 600000)

function clampInt(v, def, min, max) {
  const n = Number.parseInt(v ?? '', 10)
  if (!Number.isFinite(n)) return def
  return Math.min(max, Math.max(min, n))
}

// ── static tool registry (advertised verbatim) ───────────────────────────────
// executor/mcp Manager.verifyTools requires the advertised set to EQUAL the
// manifest set, so this file and agents/*.json must stay in bijection. Generate
// with `uwacd -dump-tools` and re-run --selftest after any change.
const TOOLS_PATH = fileURLToPath(new URL('./uwac-tools.json', import.meta.url))
let tools = []
try {
  tools = JSON.parse(readFileSync(TOOLS_PATH, 'utf8'))
} catch (err) {
  console.error(`uwac: cannot load tool registry ${TOOLS_PATH}: ${err.message}`)
  process.exit(1)
}
const TOOL_NAMES = tools.map((t) => t.name)
const TOOL_SET = new Set(TOOL_NAMES)

// ── result shaping ───────────────────────────────────────────────────────────
function errResult(tool, error, extra = {}) {
  return {
    content: [{ type: 'text', text: JSON.stringify({ ok: false, tool, error, ...extra }) }],
    isError: true,
  }
}

// Wrap the uwacd envelope ({ok,data,error}) as an MCP CallToolResult.
function envelopeResult(envelope) {
  const isError = !!(envelope && envelope.ok === false)
  return {
    content: [{ type: 'text', text: JSON.stringify(envelope) }],
    isError,
  }
}

// ── HTTP client to uwacd ─────────────────────────────────────────────────────
async function uwacFetch(method, path, body, principalToken) {
  if (!REMOTE_URL) throw new Error('uwac control plane not configured')
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS)
  const headers = { 'Content-Type': 'application/json', Accept: 'application/json' }
  if (REMOTE_TOKEN) headers.Authorization = `Bearer ${REMOTE_TOKEN}`
  if (principalToken) headers['X-UWAC-Agent'] = principalToken
  let res
  try {
    res = await fetch(`${REMOTE_URL}${path}`, {
      method,
      headers,
      body: body != null ? JSON.stringify(body) : undefined,
      signal: controller.signal,
    })
  } catch (e) {
    clearTimeout(timer)
    const reason = e && e.name === 'AbortError' ? `timed out after ${TIMEOUT_MS}ms` : (e && e.message) || String(e)
    throw new Error(`POST ${hostOf(REMOTE_URL)}${path} failed: ${reason}`)
  }
  clearTimeout(timer)
  const raw = await safeText(res)
  let msg
  try {
    msg = raw ? JSON.parse(raw) : null
  } catch {
    throw new Error(`uwacd returned non-JSON (${res.status}): ${raw.slice(0, 200)}`)
  }
  return { status: res.status, body: msg }
}

async function safeText(res) {
  try {
    return await res.text()
  } catch {
    return ''
  }
}
function hostOf(url) {
  try {
    return new URL(url).host
  } catch {
    return url
  }
}

// ── agent-native DID auth (mints the per-owner principal token) ──────────────
// Mirrors tools/paxeer/lib/agentauth.mjs + tools/tachyon/tachyon.mjs and the Go
// daemon identity: a 64-hex ed25519 SEED on disk; DID = did:matrix:<label>:<hex(pub)[:16]>.
// The challenge message MUST match uwac/internal/identity.ChallengeMessage:
//   "matrix-uwac-auth:" + did + ":" + nonce
const ED25519_PKCS8_PREFIX = Buffer.from('302e020100300506032b657004220420', 'hex')

const AGENT = {
  keyfile:
    pickEnv('UWAC_AGENT_KEYFILE', 'MATRIX_EXECUTOR_KEYFILE') ||
    `${pickEnv('MATRIX_DATA_DIR') || '/data'}/.matrix/executor.key`,
  label: pickEnv('MATRIX_USER_ID', 'UWAC_AGENT_LABEL', 'MATRIX_DID_LABEL') || 'executor',
  disabled: pickEnv('UWAC_AGENT_AUTH_DISABLE') === '1',
}

function pickEnv(...names) {
  for (const n of names) {
    const v = process.env[n]
    if (v != null && String(v).trim() !== '') return String(v).trim()
  }
  return undefined
}

let _identity = null
let _principalToken = null

function loadIdentity() {
  if (_identity) return _identity
  const raw = readFileSync(AGENT.keyfile, 'utf8').trim()
  if (!/^[0-9a-fA-F]{64}$/.test(raw)) {
    throw new Error(`uwac agent auth: ${AGENT.keyfile} is not a 64-hex ed25519 seed`)
  }
  const seed = Buffer.from(raw, 'hex')
  const privateKey = createPrivateKey({
    key: Buffer.concat([ED25519_PKCS8_PREFIX, seed]),
    format: 'der',
    type: 'pkcs8',
  })
  const spki = createPublicKey(privateKey).export({ format: 'der', type: 'spki' })
  const pubHex = Buffer.from(spki.subarray(spki.length - 32)).toString('hex')
  _identity = { did: `did:matrix:${AGENT.label}:${pubHex.slice(0, 16)}`, pubHex, privateKey }
  return _identity
}

function isAgentConfigured() {
  if (AGENT.disabled) return false
  try {
    loadIdentity()
    return true
  } catch {
    return false
  }
}

async function mintPrincipalToken(force = false) {
  if (_principalToken && !force) return _principalToken
  const id = loadIdentity()
  const ch = await uwacFetch('POST', '/v1/agent/auth/challenge', { did: id.did })
  if (ch.status !== 200 || !ch.body || ch.body.ok === false || !ch.body.data) {
    throw new Error(`uwac challenge failed (${ch.status}): ${JSON.stringify(ch.body?.error ?? ch.body)}`)
  }
  const { message, nonce } = ch.body.data
  if (!message || !nonce) throw new Error('uwac challenge returned no message/nonce')
  const signature = edSign(null, Buffer.from(message, 'utf8'), id.privateKey).toString('hex')
  const vr = await uwacFetch('POST', '/v1/agent/auth/verify', {
    did: id.did,
    public_key: id.pubHex,
    nonce,
    signature,
  })
  if (vr.status !== 200 || !vr.body || vr.body.ok === false || !vr.body.data?.token) {
    throw new Error(`uwac verify failed (${vr.status}): ${JSON.stringify(vr.body?.error ?? vr.body)}`)
  }
  _principalToken = vr.body.data.token
  return _principalToken
}

// ── tool dispatch ────────────────────────────────────────────────────────────
async function callRemoteTool(name, args) {
  if (AGENT.disabled) {
    return errResult(name, 'uwac principal auth is disabled (UWAC_AGENT_AUTH_DISABLE=1)')
  }
  if (!isAgentConfigured()) {
    return errResult(name, 'uwac requires an agent identity, but no ed25519 executor key is available', {
      hint: `expected a 64-hex seed at ${AGENT.keyfile}`,
    })
  }
  // The agent may pass `confirmed: true` (after the user approves an
  // irreversible/external-money action); lift it out of args to the top level.
  const a = { ...(args || {}) }
  const confirmed = a.confirmed === true
  delete a.confirmed

  let token
  try {
    token = await mintPrincipalToken()
  } catch (e) {
    return errResult(name, `uwac agent auth failed: ${e?.message ?? String(e)}`)
  }

  let res = await uwacFetch('POST', '/v1/invoke', { tool: name, args: a, confirmed }, token)
  // Re-auth once on a 401 (expired principal token).
  if (res.status === 401) {
    try {
      token = await mintPrincipalToken(true)
    } catch (e) {
      return errResult(name, `uwac re-auth failed: ${e?.message ?? String(e)}`)
    }
    res = await uwacFetch('POST', '/v1/invoke', { tool: name, args: a, confirmed }, token)
  }
  if (!res.body) {
    return errResult(name, `uwacd returned an empty body (status ${res.status})`)
  }
  return envelopeResult(res.body)
}

// ── JSON-RPC stdio server (daemon-facing) ─────────────────────────────────────
const handlers = {
  initialize: (params) => ({
    protocolVersion: params?.protocolVersion ?? PROTOCOL_VERSION,
    serverInfo: { name: SERVER_NAME, version: SERVER_VERSION },
    capabilities: { tools: {} },
  }),
  'tools/list': () => ({ tools }),
  'tools/call': async (params) => {
    const name = params?.name
    const args = params?.arguments || {}
    if (!TOOL_SET.has(name)) {
      return errResult(name, `unknown tool: ${name}`)
    }
    if (!REMOTE_URL) {
      return errResult(name, 'uwac control plane not configured', {
        hint: 'set MATRIX_UWAC_URL to the shared uwacd (e.g. http://matrix-uwac.internal:8646)',
      })
    }
    try {
      return await callRemoteTool(name, args)
    } catch (err) {
      return errResult(name, err?.message ?? String(err))
    }
  },
  'notifications/initialized': () => null,
  ping: () => ({}),
}

function send(obj) {
  process.stdout.write(JSON.stringify(obj) + '\n')
}
const rpcOk = (id, result) => ({ jsonrpc: '2.0', id, result })
const rpcErr = (id, code, message) => ({ jsonrpc: '2.0', id, error: { code, message } })

function startStdioServer() {
  const rl = createInterface({ input: process.stdin })
  rl.on('line', async (line) => {
    if (!line.trim()) return
    let req
    try {
      req = JSON.parse(line)
    } catch (err) {
      send(rpcErr(null, -32700, 'parse error: ' + err.message))
      return
    }
    const fn = handlers[req.method]
    if (!fn) {
      if (req.id !== undefined) send(rpcErr(req.id, -32601, `method not found: ${req.method}`))
      return
    }
    try {
      const result = await fn(req.params)
      if (req.id !== undefined && result !== null) send(rpcOk(req.id, result))
    } catch (err) {
      if (req.id !== undefined) send(rpcErr(req.id, -32000, err?.message ?? String(err)))
    }
  })
  process.stdin.on('end', () => process.exit(0))
  process.on('SIGINT', () => process.exit(0))
  process.on('SIGTERM', () => process.exit(0))
}

// `--selftest`: list the registry, then verify it against every agent manifest
// that ships a uwac server. executor/mcp Manager.verifyTools makes any
// bridge<->manifest tool-set drift a FATAL daemon boot; this guard turns the
// same drift into a non-zero exit at build/CI time. Offline (no network).
// MATRIX_UWAC_AGENTS_DIR overrides the manifest dir (used by tests).
function runSelftest() {
  console.log(`uwac: ${tools.length} tools (remote=${REMOTE_URL || 'UNSET'})`)
  for (const t of tools) console.log(`  - ${t.name}`)

  const bridge = new Set(TOOL_NAMES)
  const agentsDir = process.env.MATRIX_UWAC_AGENTS_DIR ?? fileURLToPath(new URL('../../agents/', import.meta.url))
  let files
  try {
    files = readdirSync(agentsDir).filter((f) => f.endsWith('.json'))
  } catch (err) {
    console.error(`uwac SELFTEST FAILED: cannot read agents dir ${agentsDir}: ${err.message}`)
    process.exit(1)
  }

  let checked = 0
  let drift = false
  for (const file of files) {
    let doc
    try {
      doc = JSON.parse(readFileSync(join(agentsDir, file), 'utf8'))
    } catch (err) {
      console.error(`uwac FAIL: ${file} is not valid JSON: ${err.message}`)
      drift = true
      continue
    }
    const server = (doc.servers || []).find((s) => s.alias === 'uwac')
    if (!server) continue
    checked++
    const declared = new Set((server.tools || []).map((t) => t.name))
    const bridgeOnly = [...bridge].filter((n) => !declared.has(n))
    const manifestOnly = [...declared].filter((n) => !bridge.has(n))
    if (bridgeOnly.length || manifestOnly.length) {
      drift = true
      console.error(`uwac FAIL: ${file} drifts from the bridge registry`)
      if (bridgeOnly.length) console.error(`  bridge advertises, manifest omits (boot: "unexpected tool"): ${bridgeOnly.join(', ')}`)
      if (manifestOnly.length) console.error(`  manifest expects, bridge omits (boot: "missing expected tool"): ${manifestOnly.join(', ')}`)
    } else {
      console.log(`uwac: ${file} matches (${declared.size} tools)`)
    }
  }

  if (checked === 0) {
    console.error(`uwac SELFTEST FAILED: no manifest under ${agentsDir} declares a uwac server`)
    process.exit(1)
  }
  if (drift) {
    console.error('uwac SELFTEST FAILED: manifest drift would crash the daemon at boot (Manager.verifyTools)')
    process.exit(1)
  }
  console.log(`uwac OK (${checked} manifest${checked === 1 ? '' : 's'} verified)`)
  process.exit(0)
}

if (process.argv.includes('--selftest')) {
  runSelftest()
} else {
  startStdioServer()
}
