// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type Approval struct {
	_tab flatbuffers.Table
}

func GetRootAsApproval(buf []byte, offset flatbuffers.UOffsetT) *Approval {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Approval{}
	x.Init(buf, n+offset)
	return x
}

func FinishApprovalBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsApproval(buf []byte, offset flatbuffers.UOffsetT) *Approval {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Approval{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedApprovalBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Approval) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Approval) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Approval) EffectId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Approval) EffectIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Approval) EffectIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Approval) MutateEffectId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Approval) Decision() ApprovalDecision {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ApprovalDecision(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Approval) MutateDecision(n ApprovalDecision) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func ApprovalStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ApprovalAddEffectId(builder *flatbuffers.Builder, effectId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(effectId), 0)
}
func ApprovalStartEffectIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ApprovalAddDecision(builder *flatbuffers.Builder, decision ApprovalDecision) {
	builder.PrependByteSlot(1, byte(decision), 0)
}
func ApprovalEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
