// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type AssertionClaim byte

const (
	AssertionClaimaffirmative        AssertionClaim = 0
	AssertionClaimnegative_existence AssertionClaim = 1
)

var EnumNamesAssertionClaim = map[AssertionClaim]string{
	AssertionClaimaffirmative:        "affirmative",
	AssertionClaimnegative_existence: "negative_existence",
}

var EnumValuesAssertionClaim = map[string]AssertionClaim{
	"affirmative":        AssertionClaimaffirmative,
	"negative_existence": AssertionClaimnegative_existence,
}

func (v AssertionClaim) String() string {
	if s, ok := EnumNamesAssertionClaim[v]; ok {
		return s
	}
	return "AssertionClaim(" + strconv.FormatInt(int64(v), 10) + ")"
}
