// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type Assertion struct {
	_tab flatbuffers.Table
}

func GetRootAsAssertion(buf []byte, offset flatbuffers.UOffsetT) *Assertion {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Assertion{}
	x.Init(buf, n+offset)
	return x
}

func FinishAssertionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAssertion(buf []byte, offset flatbuffers.UOffsetT) *Assertion {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Assertion{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAssertionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Assertion) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Assertion) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Assertion) BeliefId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Assertion) BeliefIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Assertion) BeliefIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Assertion) MutateBeliefId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Assertion) BeliefType() BeliefType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return BeliefType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Assertion) MutateBeliefType(n BeliefType) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *Assertion) CanonicalIdentity() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Assertion) Value(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Assertion) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Assertion) ValueBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Assertion) MutateValue(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Assertion) ValidFromNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Assertion) MutateValidFromNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *Assertion) ValidToNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Assertion) MutateValidToNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *Assertion) Provenance(obj *ProvenanceRange, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 16
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Assertion) ProvenanceLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Assertion) ConflictDomain() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Assertion) Claim() AssertionClaim {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return AssertionClaim(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Assertion) MutateClaim(n AssertionClaim) bool {
	return rcv._tab.MutateByteSlot(20, byte(n))
}

func AssertionStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func AssertionAddBeliefId(builder *flatbuffers.Builder, beliefId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(beliefId), 0)
}
func AssertionStartBeliefIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func AssertionAddBeliefType(builder *flatbuffers.Builder, beliefType BeliefType) {
	builder.PrependByteSlot(1, byte(beliefType), 0)
}
func AssertionAddCanonicalIdentity(builder *flatbuffers.Builder, canonicalIdentity flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(canonicalIdentity), 0)
}
func AssertionAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(value), 0)
}
func AssertionStartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func AssertionAddValidFromNs(builder *flatbuffers.Builder, validFromNs int64) {
	builder.PrependInt64Slot(4, validFromNs, 0)
}
func AssertionAddValidToNs(builder *flatbuffers.Builder, validToNs int64) {
	builder.PrependInt64Slot(5, validToNs, 0)
}
func AssertionAddProvenance(builder *flatbuffers.Builder, provenance flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(provenance), 0)
}
func AssertionStartProvenanceVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(16, numElems, 8)
}
func AssertionAddConflictDomain(builder *flatbuffers.Builder, conflictDomain flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(conflictDomain), 0)
}
func AssertionAddClaim(builder *flatbuffers.Builder, claim AssertionClaim) {
	builder.PrependByteSlot(8, byte(claim), 0)
}
func AssertionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
