// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type Attestation struct {
	_tab flatbuffers.Table
}

func GetRootAsAttestation(buf []byte, offset flatbuffers.UOffsetT) *Attestation {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Attestation{}
	x.Init(buf, n+offset)
	return x
}

func FinishAttestationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAttestation(buf []byte, offset flatbuffers.UOffsetT) *Attestation {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Attestation{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAttestationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Attestation) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Attestation) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Attestation) TargetLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Attestation) MutateTargetLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Attestation) Disposition() AttestationDisposition {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return AttestationDisposition(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Attestation) MutateDisposition(n AttestationDisposition) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func AttestationStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AttestationAddTargetLsn(builder *flatbuffers.Builder, targetLsn uint64) {
	builder.PrependUint64Slot(0, targetLsn, 0)
}
func AttestationAddDisposition(builder *flatbuffers.Builder, disposition AttestationDisposition) {
	builder.PrependByteSlot(1, byte(disposition), 0)
}
func AttestationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
