// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type BeliefType byte

const (
	BeliefTypefact       BeliefType = 0
	BeliefTypepreference BeliefType = 1
	BeliefTypeconstraint BeliefType = 2
	BeliefTypegoal       BeliefType = 3
	BeliefTypeidentity   BeliefType = 4
)

var EnumNamesBeliefType = map[BeliefType]string{
	BeliefTypefact:       "fact",
	BeliefTypepreference: "preference",
	BeliefTypeconstraint: "constraint",
	BeliefTypegoal:       "goal",
	BeliefTypeidentity:   "identity",
}

var EnumValuesBeliefType = map[string]BeliefType{
	"fact":       BeliefTypefact,
	"preference": BeliefTypepreference,
	"constraint": BeliefTypeconstraint,
	"goal":       BeliefTypegoal,
	"identity":   BeliefTypeidentity,
}

func (v BeliefType) String() string {
	if s, ok := EnumNamesBeliefType[v]; ok {
		return s
	}
	return "BeliefType(" + strconv.FormatInt(int64(v), 10) + ")"
}
