// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type EffectState byte

const (
	EffectStatedispatched      EffectState = 0
	EffectStatecommitted       EffectState = 1
	EffectStatereturned        EffectState = 2
	EffectStateoutcome_unknown EffectState = 3
)

var EnumNamesEffectState = map[EffectState]string{
	EffectStatedispatched:      "dispatched",
	EffectStatecommitted:       "committed",
	EffectStatereturned:        "returned",
	EffectStateoutcome_unknown: "outcome_unknown",
}

var EnumValuesEffectState = map[string]EffectState{
	"dispatched":      EffectStatedispatched,
	"committed":       EffectStatecommitted,
	"returned":        EffectStatereturned,
	"outcome_unknown": EffectStateoutcome_unknown,
}

func (v EffectState) String() string {
	if s, ok := EnumNamesEffectState[v]; ok {
		return s
	}
	return "EffectState(" + strconv.FormatInt(int64(v), 10) + ")"
}
