// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type Effect struct {
	_tab flatbuffers.Table
}

func GetRootAsEffect(buf []byte, offset flatbuffers.UOffsetT) *Effect {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Effect{}
	x.Init(buf, n+offset)
	return x
}

func FinishEffectBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEffect(buf []byte, offset flatbuffers.UOffsetT) *Effect {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Effect{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEffectBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Effect) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Effect) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Effect) EffectId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Effect) EffectIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Effect) EffectIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Effect) MutateEffectId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Effect) ToolCallLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Effect) MutateToolCallLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Effect) State() EffectState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return EffectState(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Effect) MutateState(n EffectState) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func EffectStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func EffectAddEffectId(builder *flatbuffers.Builder, effectId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(effectId), 0)
}
func EffectStartEffectIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func EffectAddToolCallLsn(builder *flatbuffers.Builder, toolCallLsn uint64) {
	builder.PrependUint64Slot(1, toolCallLsn, 0)
}
func EffectAddState(builder *flatbuffers.Builder, state EffectState) {
	builder.PrependByteSlot(2, byte(state), 0)
}
func EffectEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
