// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type EventEnvelope struct {
	_tab flatbuffers.Table
}

const EventEnvelopeIdentifier = "NCEV"

func GetRootAsEventEnvelope(buf []byte, offset flatbuffers.UOffsetT) *EventEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EventEnvelope{}
	x.Init(buf, n+offset)
	return x
}

func FinishEventEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(EventEnvelopeIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func EventEnvelopeBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, EventEnvelopeIdentifier)
}

func GetSizePrefixedRootAsEventEnvelope(buf []byte, offset flatbuffers.UOffsetT) *EventEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EventEnvelope{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEventEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(EventEnvelopeIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedEventEnvelopeBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, EventEnvelopeIdentifier)
}

func (rcv *EventEnvelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EventEnvelope) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EventEnvelope) SchemaVersion() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *EventEnvelope) MutateSchemaVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *EventEnvelope) PayloadType() EventPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return EventPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *EventEnvelope) MutatePayloadType(n EventPayload) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *EventEnvelope) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *EventEnvelope) ConnectionId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *EventEnvelope) ConnectionIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *EventEnvelope) ConnectionIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *EventEnvelope) MutateConnectionId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *EventEnvelope) ClientSeq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EventEnvelope) MutateClientSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *EventEnvelope) ClientEventIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EventEnvelope) MutateClientEventIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *EventEnvelope) ClientEventCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EventEnvelope) MutateClientEventCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func EventEnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func EventEnvelopeAddSchemaVersion(builder *flatbuffers.Builder, schemaVersion uint16) {
	builder.PrependUint16Slot(0, schemaVersion, 1)
}
func EventEnvelopeAddPayloadType(builder *flatbuffers.Builder, payloadType EventPayload) {
	builder.PrependByteSlot(1, byte(payloadType), 0)
}
func EventEnvelopeAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(payload), 0)
}
func EventEnvelopeAddConnectionId(builder *flatbuffers.Builder, connectionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(connectionId), 0)
}
func EventEnvelopeStartConnectionIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func EventEnvelopeAddClientSeq(builder *flatbuffers.Builder, clientSeq uint64) {
	builder.PrependUint64Slot(4, clientSeq, 0)
}
func EventEnvelopeAddClientEventIndex(builder *flatbuffers.Builder, clientEventIndex uint32) {
	builder.PrependUint32Slot(5, clientEventIndex, 0)
}
func EventEnvelopeAddClientEventCount(builder *flatbuffers.Builder, clientEventCount uint32) {
	builder.PrependUint32Slot(6, clientEventCount, 0)
}
func EventEnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
