// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type LoopCloseReason byte

const (
	LoopCloseReasondone       LoopCloseReason = 0
	LoopCloseReasonabandoned  LoopCloseReason = 1
	LoopCloseReasonhanded_off LoopCloseReason = 2
	LoopCloseReasonsuperseded LoopCloseReason = 3
)

var EnumNamesLoopCloseReason = map[LoopCloseReason]string{
	LoopCloseReasondone:       "done",
	LoopCloseReasonabandoned:  "abandoned",
	LoopCloseReasonhanded_off: "handed_off",
	LoopCloseReasonsuperseded: "superseded",
}

var EnumValuesLoopCloseReason = map[string]LoopCloseReason{
	"done":       LoopCloseReasondone,
	"abandoned":  LoopCloseReasonabandoned,
	"handed_off": LoopCloseReasonhanded_off,
	"superseded": LoopCloseReasonsuperseded,
}

func (v LoopCloseReason) String() string {
	if s, ok := EnumNamesLoopCloseReason[v]; ok {
		return s
	}
	return "LoopCloseReason(" + strconv.FormatInt(int64(v), 10) + ")"
}
