// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type ProvenanceRange struct {
	_tab flatbuffers.Struct
}

func (rcv *ProvenanceRange) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProvenanceRange) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ProvenanceRange) FirstLsn() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *ProvenanceRange) MutateFirstLsn(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *ProvenanceRange) LastLsn() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *ProvenanceRange) MutateLastLsn(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateProvenanceRange(builder *flatbuffers.Builder, firstLsn uint64, lastLsn uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependUint64(lastLsn)
	builder.PrependUint64(firstLsn)
	return builder.Offset()
}
