// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type Recovery struct {
	_tab flatbuffers.Table
}

func GetRootAsRecovery(buf []byte, offset flatbuffers.UOffsetT) *Recovery {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Recovery{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecoveryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRecovery(buf []byte, offset flatbuffers.UOffsetT) *Recovery {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Recovery{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecoveryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Recovery) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Recovery) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Recovery) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Recovery) TargetLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Recovery) MutateTargetLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func RecoveryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RecoveryAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(code), 0)
}
func RecoveryAddTargetLsn(builder *flatbuffers.Builder, targetLsn uint64) {
	builder.PrependUint64Slot(1, targetLsn, 0)
}
func RecoveryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
