// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type ResultStatus byte

const (
	ResultStatusok              ResultStatus = 0
	ResultStatuserror           ResultStatus = 1
	ResultStatusoutcome_unknown ResultStatus = 2
)

var EnumNamesResultStatus = map[ResultStatus]string{
	ResultStatusok:              "ok",
	ResultStatuserror:           "error",
	ResultStatusoutcome_unknown: "outcome_unknown",
}

var EnumValuesResultStatus = map[string]ResultStatus{
	"ok":              ResultStatusok,
	"error":           ResultStatuserror,
	"outcome_unknown": ResultStatusoutcome_unknown,
}

func (v ResultStatus) String() string {
	if s, ok := EnumNamesResultStatus[v]; ok {
		return s
	}
	return "ResultStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
