/**
 * Construct renderers — the human's alphabet.
 *
 * A trusted, deterministic React renderer per frozen primitive (Narration,
 * Metric, Entity, Structure, Stream, Timeline, Canvas, Ask), plus the
 * `SurfaceRenderer` dispatcher and the `ConstructSurfaces` list container the
 * live workspace mounts. The agent fills these primitives; it never emits
 * arbitrary UI (invariant i2). Types come from `@/lib/construct/types.gen`
 * (generated by `construct codegen`); never hand-edited.
 */
export {
  SurfaceRenderer,
  ConstructSurfaces,
  type SurfaceHandlers,
} from '@/components/matrix/construct/surface-renderer'
export { NarrationView } from '@/components/matrix/construct/narration'
export { MetricView } from '@/components/matrix/construct/metric'
export { EntityView } from '@/components/matrix/construct/entity'
export { StructureView } from '@/components/matrix/construct/structure'
export { StreamView } from '@/components/matrix/construct/stream'
export { TimelineView } from '@/components/matrix/construct/timeline'
export { CanvasView } from '@/components/matrix/construct/canvas'
export { AskView } from '@/components/matrix/construct/ask'
export { DecorationRow } from '@/components/matrix/construct/decoration'
