[package]
name = "keith-channel-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
keith-agent-types = { path = "../agent-types" }
keith-connection = { path = "../connection" }
keith-protocol = { path = "../protocol" }
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
