apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ion-data
  namespace: ion
  labels:
    app.kubernetes.io/name: ion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard
