/**
 * self-model-graph — pure data layer for the Neo self-model brain.
 *
 * Loads the static codegraph JSON (generated by scripts/build-self-model-graph.mjs
 * from /root/matrix/graph/self-model — no daemon API involved) and computes a
 * deterministic, brain-shaped 3D layout:
 *
 *   - neo      → left cerebral hemisphere
 *   - cody     → right cerebral hemisphere
 *   - cortex   → limbic core (deep centre — fitting for the memory organ)
 *   - executor → cerebellum (motor control — fitting for the tool executor)
 *
 * Packages cluster as cortical columns; symbols scatter around their package
 * anchor and are pulled toward the region surface with a gyri-like radial
 * wrinkle so the point cloud reads as folded cortex. Everything is seeded —
 * the same graph always produces the same brain.
 */

/* ------------------------------- types ------------------------------ */

export interface GraphNode {
  /** full codegraph id, e.g. matrix/neo/internal/agent.Agent#activeGoal */
  id: string
  /** short display name */
  n: string
  /** kind: package | file | type | interface | method | func | field | const | var */
  k: string
  /** source file path */
  f: string
  /** line range "start:end" */
  l: string
  /** module index into meta.modules */
  m: number
  /** package node index (-1 when unknown) */
  pk: number
  /** parent node index (-1 at roots) */
  p: number
  /** signature */
  s?: string
  /** doc comment */
  d?: string
  /** child node indices */
  c?: number[]
}

export interface SelfModelGraph {
  meta: {
    summary: string
    merkle: string
    scope: string[]
    generated: string
    modules: { id: string; count: number }[]
  }
  nodes: GraphNode[]
  impl: [number, number][]
}

export interface BrainRegion {
  module: string
  center: [number, number, number]
  radii: [number, number, number]
  /** 0..1 — how strongly points are pulled to the surface (cortex shell) */
  shell: number
  /** radial wrinkle amplitude (gyri/sulci) */
  wrinkle: number
  color: string
}

export interface BrainLayout {
  /** xyz per node */
  positions: Float32Array
  /** world radius per node */
  scales: Float32Array
  /** rgb per node */
  colors: Float32Array
  /** package-anchor xyz per package node index */
  anchors: Map<number, [number, number, number]>
  regions: BrainRegion[]
}

/* ----------------------- GLB neuron layout -------------------------- */

/** One neuron in the GLB neural network — represents one or more codegraph packages. */
export interface NeuronMapping {
  /** Neuron index in the GLB (0..53) */
  neuronIdx: number
  /** Which Cloner layer (0–3) */
  layer: number
  /** Codegraph package node indices mapped to this neuron */
  packageIndices: number[]
  /** Module index (0–3) */
  moduleIdx: number
}

/** Layout data derived from the GLB neural network model. */
export interface NeuronLayout {
  /** World-space positions for each neuron [x,y,z,...] flat, count*3 */
  positions: Float32Array
  /** Neuron count */
  count: number
  /** Per-neuron mapping to codegraph packages */
  mappings: NeuronMapping[]
  /** Module index per neuron (for coloring) */
  moduleIndices: number[]
}

/**
 * GLB neuron positions extracted from the artificial_neural_network_ann.glb
 * model. 4 Cloner layers with [25, 9, 16, 4] cube nodes. Positions are in
 * model space (units of ~1000). The component normalises them to scene scale.
 */
const GLB_NEURON_POSITIONS: [number, number, number][] = [
  // Cloner (25) — layer 0
  [-1000, -1000, 0],
  [-500, -1000, 0],
  [0, -1000, 0],
  [500, -1000, 0],
  [1000, -1000, 0],
  [-1000, -500, 0],
  [-500, -500, 0],
  [0, -500, 0],
  [500, -500, 0],
  [1000, -500, 0],
  [-1000, 0, 0],
  [-500, 0, 0],
  [0, 0, 0],
  [500, 0, 0],
  [1000, 0, 0],
  [-1000, 500, 0],
  [-500, 500, 0],
  [0, 500, 0],
  [500, 500, 0],
  [1000, 500, 0],
  [-1000, 1000, 0],
  [-500, 1000, 0],
  [0, 1000, 0],
  [500, 1000, 0],
  [1000, 1000, 0],
  // Cloner_1 (9) — layer 1
  [-500, -500, -2000],
  [0, -500, -2000],
  [500, -500, -2000],
  [-500, 0, -2000],
  [0, 0, -2000],
  [500, 0, -2000],
  [-500, 500, -2000],
  [0, 500, -2000],
  [500, 500, -2000],
  // Cloner_2 (16) — layer 2
  [-750, -750, -4000],
  [-250, -750, -4000],
  [250, -750, -4000],
  [750, -750, -4000],
  [-750, -250, -4000],
  [-250, -250, -4000],
  [250, -250, -4000],
  [750, -250, -4000],
  [-750, 250, -4000],
  [-250, 250, -4000],
  [250, 250, -4000],
  [750, 250, -4000],
  [-750, 750, -4000],
  [-250, 750, -4000],
  [250, 750, -4000],
  [750, 750, -4000],
  // Cloner_3 (4) — layer 3
  [-250, -250, -6000],
  [250, -250, -6000],
  [-250, 250, -6000],
  [250, 250, -6000],
]

const GLB_LAYER_SIZES = [25, 9, 16, 4]

/** Module assignment per Cloner layer. Maps layer index → module index. */
// layer 0 (25) → cody (0), layer 1 (9) → executor (1? no...)
// modules: 0=cody(19), 1=cortex(18), 2=executor(11), 3=neo(18)
// Best fit: layer0(25)→cody(19), layer1(9)→executor(11-2overflow),
//           layer2(16)→neo(18-2overflow), layer3(4)→cortex(18-heavygroup)
// Reorder: layer0→0(cody), layer1→2(executor), layer2→3(neo), layer3→1(cortex)

/** Map packages to GLB neurons. Returns a NeuronLayout ready for rendering. */
export function mapPackagesToNeurons(graph: SelfModelGraph): NeuronLayout {
  const { nodes } = graph
  const positions = new Float32Array(GLB_NEURON_POSITIONS.length * 3)
  const mappings: NeuronMapping[] = []
  const moduleIndices: number[] = []

  // Apply the GLB root transform (node 0 * node 1 = 0.01 scale with axis swap).
  // World-space bounds: X=[-10,10] Y=[-10,10] Z=[-60,0].
  const WORLD_SCALE = 0.01
  for (let i = 0; i < GLB_NEURON_POSITIONS.length; i++) {
    const [x, y, z] = GLB_NEURON_POSITIONS[i]
    positions[i * 3] = x * WORLD_SCALE
    positions[i * 3 + 1] = y * WORLD_SCALE
    positions[i * 3 + 2] = z * WORLD_SCALE
  }

  // Collect package indices per module.
  const pkgsByModule = new Map<number, number[]>()
  nodes.forEach((node, i) => {
    if (node.k === 'package') {
      const list = pkgsByModule.get(node.m) ?? []
      list.push(i)
      pkgsByModule.set(node.m, list)
    }
  })

  // Layer→module assignment:
  //   layer 0 (25 neurons) → module 0 (cody, 19 pkgs)
  //   layer 1 (9 neurons)  → module 2 (executor, 11 pkgs)
  //   layer 2 (16 neurons) → module 3 (neo, 18 pkgs)
  //   layer 3 (4 neurons)  → module 1 (cortex, 18 pkgs)
  const layerModule = [0, 2, 3, 1]

  let globalNeuronIdx = 0
  for (let layer = 0; layer < 4; layer++) {
    const modIdx = layerModule[layer]
    const neuronCount = GLB_LAYER_SIZES[layer]
    const pkgs = pkgsByModule.get(modIdx) ?? []

    if (pkgs.length === 0) {
      // No packages — empty neurons for this layer.
      for (let j = 0; j < neuronCount; j++) {
        mappings.push({ neuronIdx: globalNeuronIdx, layer, packageIndices: [], moduleIdx: modIdx })
        moduleIndices.push(modIdx)
        globalNeuronIdx++
      }
      continue
    }

    // Distribute packages across neurons. Each neuron gets at least one
    // package until we run out; excess packages share the last neuron.
    const neuronsWithOne = Math.min(neuronCount, pkgs.length)
    let pkgCursor = 0
    for (let j = 0; j < neuronCount; j++) {
      const pkgCount = j < neuronsWithOne ? 1 : 0
      const assigned: number[] = []
      if (pkgCount > 0) {
        assigned.push(pkgs[pkgCursor++])
      }
      // If more packages than neurons, overflow onto the last neuron.
      if (j === neuronCount - 1 && pkgCursor < pkgs.length) {
        while (pkgCursor < pkgs.length) assigned.push(pkgs[pkgCursor++])
      }
      mappings.push({
        neuronIdx: globalNeuronIdx,
        layer,
        packageIndices: assigned,
        moduleIdx: modIdx,
      })
      moduleIndices.push(modIdx)
      globalNeuronIdx++
    }
  }

  return { positions, count: GLB_NEURON_POSITIONS.length, mappings, moduleIndices }
}

/** Given a neuron index, return all codegraph node indices belonging to it
 *  (the neuron's packages + all their descendants). */
export function neuronNodeIndices(graph: SelfModelGraph, mapping: NeuronMapping): number[] {
  const result: number[] = []
  const visited = new Set<number>()
  const walk = (idx: number) => {
    if (visited.has(idx)) return
    visited.add(idx)
    result.push(idx)
    for (const child of graph.nodes[idx].c ?? []) walk(child)
  }
  for (const pkgIdx of mapping.packageIndices) walk(pkgIdx)
  return result
}

/** Find which neuron a codegraph node belongs to (by its package ancestry). */
export function findNeuronForNode(
  nodeIdx: number,
  graph: SelfModelGraph,
  mappings: NeuronMapping[],
): number {
  const node = graph.nodes[nodeIdx]
  // Walk up to find the package.
  let cur = nodeIdx
  while (cur >= 0 && graph.nodes[cur].k !== 'package') {
    cur = graph.nodes[cur].p
  }
  const pkgIdx = cur >= 0 ? cur : nodeIdx
  for (let i = 0; i < mappings.length; i++) {
    if (mappings[i].packageIndices.includes(pkgIdx)) return i
  }
  // Fallback: match by module.
  for (let i = 0; i < mappings.length; i++) {
    if (mappings[i].moduleIdx === node.m) return i
  }
  return -1
}

/* ------------------------------ loading ----------------------------- */

export const SELF_MODEL_GRAPH_URL = '/self-model/graph.json'

export async function loadSelfModelGraph(signal?: AbortSignal): Promise<SelfModelGraph | null> {
  try {
    const res = await fetch(SELF_MODEL_GRAPH_URL, { signal })
    if (!res.ok) return null
    return (await res.json()) as SelfModelGraph
  } catch {
    return null
  }
}

/* ---------------------------- brain anatomy ------------------------- */

export const MODULE_COLORS: Record<string, string> = {
  neo: '#5b8cff',
  cody: '#2fe6b0',
  cortex: '#c07bff',
  executor: '#ffb84d',
}

const ANATOMY: Record<string, Omit<BrainRegion, 'module' | 'color'>> = {
  // Left cerebral hemisphere — the conversational mind.
  neo: {
    center: [-0.62, 0.34, 0.05],
    radii: [0.72, 1.0, 1.38],
    shell: 0.82,
    wrinkle: 0.055,
  },
  // Right cerebral hemisphere — the coding mind.
  cody: {
    center: [0.62, 0.34, 0.05],
    radii: [0.72, 1.0, 1.38],
    shell: 0.82,
    wrinkle: 0.055,
  },
  // Limbic core — memory, deep centre.
  cortex: {
    center: [0, -0.18, 0.12],
    radii: [0.52, 0.46, 0.72],
    shell: 0.35,
    wrinkle: 0.02,
  },
  // Cerebellum — execution, lower back.
  executor: {
    center: [0, -0.72, -1.02],
    radii: [0.78, 0.5, 0.58],
    shell: 0.68,
    wrinkle: 0.09,
  },
}

const FALLBACK_REGION: Omit<BrainRegion, 'module' | 'color'> = {
  center: [0, 0, 0],
  radii: [0.6, 0.6, 0.6],
  shell: 0.5,
  wrinkle: 0.03,
}

export function regionsFor(modules: { id: string }[]): BrainRegion[] {
  return modules.map(({ id }) => ({
    module: id,
    color: MODULE_COLORS[id] ?? '#9aa4b2',
    ...(ANATOMY[id] ?? FALLBACK_REGION),
  }))
}

/* --------------------------- deterministic rng ---------------------- */

function mulberry32(seed: number) {
  let a = seed >>> 0
  return () => {
    a += 0x6d2b79f5
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function hashString(s: string): number {
  let h = 2166136261
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return h >>> 0
}

/** Box–Muller gaussian from a uniform rng. */
function gaussian(rng: () => number): number {
  const u = Math.max(rng(), 1e-9)
  const v = rng()
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v)
}

/* ------------------------------ sizing ------------------------------ */

const KIND_SCALE: Record<string, number> = {
  package: 0.05,
  interface: 0.038,
  type: 0.03,
  file: 0.026,
  method: 0.02,
  func: 0.02,
  const: 0.015,
  var: 0.015,
  field: 0.011,
}

export function kindScale(kind: string): number {
  return KIND_SCALE[kind] ?? 0.018
}

/** Kind-based brightness so structure pops out of the field haze. */
const KIND_LUMA: Record<string, number> = {
  package: 1.45,
  interface: 1.3,
  type: 1.2,
  file: 1.0,
  method: 0.95,
  func: 0.95,
  const: 0.7,
  var: 0.7,
  field: 0.55,
}

function hexToRgb(hex: string): [number, number, number] {
  const v = parseInt(hex.slice(1), 16)
  return [((v >> 16) & 255) / 255, ((v >> 8) & 255) / 255, (v & 255) / 255]
}

/* ---------------------------- gyri wrinkle -------------------------- */

/** Pseudo-noise radial fold pattern from a direction on the unit sphere. */
function gyri(x: number, y: number, z: number): number {
  const theta = Math.atan2(z, x)
  const phi = Math.acos(Math.min(1, Math.max(-1, y)))
  return (
    Math.sin(6 * theta + 2.3 * Math.sin(3 * phi)) * Math.sin(4.5 * phi + 1.7 * Math.sin(2 * theta))
  )
}

/* ------------------------------ layout ------------------------------ */

export function computeBrainLayout(graph: SelfModelGraph): BrainLayout {
  const { nodes, meta } = graph
  const regions = regionsFor(meta.modules)

  const positions = new Float32Array(nodes.length * 3)
  const scales = new Float32Array(nodes.length)
  const colors = new Float32Array(nodes.length * 3)
  const anchors = new Map<number, [number, number, number]>()

  // Group package indices per module, then members per package.
  const pkgsByModule = new Map<number, number[]>()
  const membersByPkg = new Map<number, number[]>()
  nodes.forEach((node, i) => {
    if (node.k === 'package') {
      const list = pkgsByModule.get(node.m) ?? []
      list.push(i)
      pkgsByModule.set(node.m, list)
    }
    const pk = node.pk >= 0 ? node.pk : -1
    const members = membersByPkg.get(pk) ?? []
    members.push(i)
    membersByPkg.set(pk, members)
  })

  // Package anchors — fibonacci sphere directions inside each region.
  const GOLDEN = Math.PI * (3 - Math.sqrt(5))
  regions.forEach((region, mi) => {
    const pkgs = pkgsByModule.get(mi) ?? []
    const n = pkgs.length
    pkgs.forEach((pkgIdx, j) => {
      const rng = mulberry32(hashString(nodes[pkgIdx].id))
      // Even sphere coverage with a hash jitter so clusters feel organic.
      const t = n > 1 ? j / (n - 1) : 0.5
      const y = 1 - 2 * t
      const r = Math.sqrt(Math.max(0, 1 - y * y))
      const a = GOLDEN * j + rng() * 0.35
      const dir: [number, number, number] = [Math.cos(a) * r, y, Math.sin(a) * r]
      const depth = 0.45 + 0.4 * rng() // radial placement inside the region
      anchors.set(pkgIdx, [
        region.center[0] + dir[0] * region.radii[0] * depth,
        region.center[1] + dir[1] * region.radii[1] * depth,
        region.center[2] + dir[2] * region.radii[2] * depth,
      ])
    })
  })

  // Node placement — gaussian cloud around the package anchor, pulled to
  // the region surface and wrinkled.
  nodes.forEach((node, i) => {
    const region = regions[node.m] ?? regions[0]
    const anchor = (node.pk >= 0 ? anchors.get(node.pk) : undefined) ?? region.center
    const memberCount = membersByPkg.get(node.pk >= 0 ? node.pk : -1)?.length ?? 1
    const clusterR = Math.min(0.42, 0.075 * Math.cbrt(memberCount))

    const rng = mulberry32(hashString(node.id))
    let x = anchor[0] + gaussian(rng) * clusterR
    let y = anchor[1] + gaussian(rng) * clusterR
    let z = anchor[2] + gaussian(rng) * clusterR * 1.25

    // Normalise into region-ellipsoid space.
    let ux = (x - region.center[0]) / region.radii[0]
    let uy = (y - region.center[1]) / region.radii[1]
    let uz = (z - region.center[2]) / region.radii[2]
    const rho = Math.sqrt(ux * ux + uy * uy + uz * uz) || 1e-6

    // Surface pull: blend the radius toward the cortex shell.
    const shellRho = 0.62 + 0.4 * Math.min(1, rho)
    let targetRho = (1 - region.shell) * Math.min(rho, 1) + region.shell * shellRho

    // Gyri wrinkle along the fold pattern.
    const nx = ux / rho
    const ny = uy / rho
    const nz = uz / rho
    targetRho *= 1 + region.wrinkle * gyri(nx, ny, nz)
    targetRho = Math.min(targetRho, 1.04)

    ux = nx * targetRho
    uy = ny * targetRho
    uz = nz * targetRho
    x = region.center[0] + ux * region.radii[0]
    y = region.center[1] + uy * region.radii[1]
    z = region.center[2] + uz * region.radii[2]

    positions[i * 3] = x
    positions[i * 3 + 1] = y
    positions[i * 3 + 2] = z
    scales[i] = kindScale(node.k)

    const [cr, cg, cb] = hexToRgb(region.color)
    const luma = KIND_LUMA[node.k] ?? 0.8
    colors[i * 3] = Math.min(1, cr * luma)
    colors[i * 3 + 1] = Math.min(1, cg * luma)
    colors[i * 3 + 2] = Math.min(1, cb * luma)
  })

  // Package nodes sit exactly on their anchor (cluster nucleus).
  for (const [pkgIdx, anchor] of anchors) {
    positions[pkgIdx * 3] = anchor[0]
    positions[pkgIdx * 3 + 1] = anchor[1]
    positions[pkgIdx * 3 + 2] = anchor[2]
  }

  return { positions, scales, colors, anchors, regions }
}

/* ---------------------------- graph queries ------------------------- */

/** Breadcrumb chain root→node following parent edges (cycle-safe). */
export function nodePath(graph: SelfModelGraph, idx: number): number[] {
  const path: number[] = []
  const seen = new Set<number>()
  let cur = idx
  while (cur >= 0 && cur < graph.nodes.length && !seen.has(cur)) {
    path.push(cur)
    seen.add(cur)
    cur = graph.nodes[cur].p
  }
  return path.reverse()
}

export interface SearchHit {
  idx: number
  score: number
}

/** Rank nodes by name match: exact > prefix > substring; ties prefer
 *  structural kinds (package/type) over leaf fields. */
export function searchNodes(graph: SelfModelGraph, query: string, limit = 12): SearchHit[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  const hits: SearchHit[] = []
  const kindBoost: Record<string, number> = {
    package: 3,
    interface: 2.5,
    type: 2,
    file: 1.5,
    method: 1,
    func: 1,
  }
  for (let i = 0; i < graph.nodes.length; i++) {
    const name = graph.nodes[i].n.toLowerCase()
    let score = 0
    if (name === q) score = 100
    else if (name.startsWith(q)) score = 50
    else if (name.includes(q)) score = 20
    else if (graph.nodes[i].id.toLowerCase().includes(q)) score = 8
    if (score > 0) {
      hits.push({ idx: i, score: score + (kindBoost[graph.nodes[i].k] ?? 0) })
    }
  }
  hits.sort((a, b) => b.score - a.score)
  return hits.slice(0, limit)
}

/** Edge list to draw when a node is selected: parent chain, children
 *  (capped), and implements links. Returns index pairs. */
export function selectionEdges(
  graph: SelfModelGraph,
  idx: number,
  childCap = 80,
): [number, number][] {
  const pairs: [number, number][] = []
  const node = graph.nodes[idx]
  if (!node) return pairs
  if (node.p >= 0) pairs.push([idx, node.p])
  for (const child of (node.c ?? []).slice(0, childCap)) pairs.push([idx, child])
  for (const [a, b] of graph.impl) {
    if (a === idx || b === idx) pairs.push([a, b])
  }
  return pairs
}
