// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EVENTS_NEOCORTEX_SCHEMA_H_
#define FLATBUFFERS_GENERATED_EVENTS_NEOCORTEX_SCHEMA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace neocortex {
namespace schema {

struct ProvenanceRange;

struct UserMsg;
struct UserMsgBuilder;

struct DeliveredMsg;
struct DeliveredMsgBuilder;

struct ToolCall;
struct ToolCallBuilder;

struct ToolResult;
struct ToolResultBuilder;

struct Reasoning;
struct ReasoningBuilder;

struct ProviderFrame;
struct ProviderFrameBuilder;

struct MediaRef;
struct MediaRefBuilder;

struct Effect;
struct EffectBuilder;

struct Approval;
struct ApprovalBuilder;

struct Outcome;
struct OutcomeBuilder;

struct Checkpoint;
struct CheckpointBuilder;

struct Supervisor;
struct SupervisorBuilder;

struct Recovery;
struct RecoveryBuilder;

struct IntentSet;
struct IntentSetBuilder;

struct LoopOpened;
struct LoopOpenedBuilder;

struct LoopClosed;
struct LoopClosedBuilder;

struct Assertion;
struct AssertionBuilder;

struct Consolidation;
struct ConsolidationBuilder;

struct Embedding;
struct EmbeddingBuilder;

struct Retract;
struct RetractBuilder;

struct Attestation;
struct AttestationBuilder;

struct EventEnvelope;
struct EventEnvelopeBuilder;

enum class ResultStatus : uint8_t {
  ok = 0,
  error = 1,
  outcome_unknown = 2,
  MIN = ok,
  MAX = outcome_unknown
};

inline const ResultStatus (&EnumValuesResultStatus())[3] {
  static const ResultStatus values[] = {
    ResultStatus::ok,
    ResultStatus::error,
    ResultStatus::outcome_unknown
  };
  return values;
}

inline const char * const *EnumNamesResultStatus() {
  static const char * const names[4] = {
    "ok",
    "error",
    "outcome_unknown",
    nullptr
  };
  return names;
}

inline const char *EnumNameResultStatus(ResultStatus e) {
  if (::flatbuffers::IsOutRange(e, ResultStatus::ok, ResultStatus::outcome_unknown)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesResultStatus()[index];
}

enum class ApprovalDecision : uint8_t {
  approved = 0,
  denied = 1,
  MIN = approved,
  MAX = denied
};

inline const ApprovalDecision (&EnumValuesApprovalDecision())[2] {
  static const ApprovalDecision values[] = {
    ApprovalDecision::approved,
    ApprovalDecision::denied
  };
  return values;
}

inline const char * const *EnumNamesApprovalDecision() {
  static const char * const names[3] = {
    "approved",
    "denied",
    nullptr
  };
  return names;
}

inline const char *EnumNameApprovalDecision(ApprovalDecision e) {
  if (::flatbuffers::IsOutRange(e, ApprovalDecision::approved, ApprovalDecision::denied)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesApprovalDecision()[index];
}

enum class EffectState : uint8_t {
  dispatched = 0,
  committed = 1,
  returned = 2,
  outcome_unknown = 3,
  MIN = dispatched,
  MAX = outcome_unknown
};

inline const EffectState (&EnumValuesEffectState())[4] {
  static const EffectState values[] = {
    EffectState::dispatched,
    EffectState::committed,
    EffectState::returned,
    EffectState::outcome_unknown
  };
  return values;
}

inline const char * const *EnumNamesEffectState() {
  static const char * const names[5] = {
    "dispatched",
    "committed",
    "returned",
    "outcome_unknown",
    nullptr
  };
  return names;
}

inline const char *EnumNameEffectState(EffectState e) {
  if (::flatbuffers::IsOutRange(e, EffectState::dispatched, EffectState::outcome_unknown)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEffectState()[index];
}

enum class LoopCloseReason : uint8_t {
  done = 0,
  abandoned = 1,
  handed_off = 2,
  superseded = 3,
  MIN = done,
  MAX = superseded
};

inline const LoopCloseReason (&EnumValuesLoopCloseReason())[4] {
  static const LoopCloseReason values[] = {
    LoopCloseReason::done,
    LoopCloseReason::abandoned,
    LoopCloseReason::handed_off,
    LoopCloseReason::superseded
  };
  return values;
}

inline const char * const *EnumNamesLoopCloseReason() {
  static const char * const names[5] = {
    "done",
    "abandoned",
    "handed_off",
    "superseded",
    nullptr
  };
  return names;
}

inline const char *EnumNameLoopCloseReason(LoopCloseReason e) {
  if (::flatbuffers::IsOutRange(e, LoopCloseReason::done, LoopCloseReason::superseded)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLoopCloseReason()[index];
}

enum class BeliefType : uint8_t {
  fact = 0,
  preference = 1,
  constraint = 2,
  goal = 3,
  identity = 4,
  MIN = fact,
  MAX = identity
};

inline const BeliefType (&EnumValuesBeliefType())[5] {
  static const BeliefType values[] = {
    BeliefType::fact,
    BeliefType::preference,
    BeliefType::constraint,
    BeliefType::goal,
    BeliefType::identity
  };
  return values;
}

inline const char * const *EnumNamesBeliefType() {
  static const char * const names[6] = {
    "fact",
    "preference",
    "constraint",
    "goal",
    "identity",
    nullptr
  };
  return names;
}

inline const char *EnumNameBeliefType(BeliefType e) {
  if (::flatbuffers::IsOutRange(e, BeliefType::fact, BeliefType::identity)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBeliefType()[index];
}

enum class AssertionClaim : uint8_t {
  affirmative = 0,
  negative_existence = 1,
  MIN = affirmative,
  MAX = negative_existence
};

inline const AssertionClaim (&EnumValuesAssertionClaim())[2] {
  static const AssertionClaim values[] = {
    AssertionClaim::affirmative,
    AssertionClaim::negative_existence
  };
  return values;
}

inline const char * const *EnumNamesAssertionClaim() {
  static const char * const names[3] = {
    "affirmative",
    "negative_existence",
    nullptr
  };
  return names;
}

inline const char *EnumNameAssertionClaim(AssertionClaim e) {
  if (::flatbuffers::IsOutRange(e, AssertionClaim::affirmative, AssertionClaim::negative_existence)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAssertionClaim()[index];
}

enum class AttestationDisposition : uint8_t {
  used = 0,
  ignored = 1,
  MIN = used,
  MAX = ignored
};

inline const AttestationDisposition (&EnumValuesAttestationDisposition())[2] {
  static const AttestationDisposition values[] = {
    AttestationDisposition::used,
    AttestationDisposition::ignored
  };
  return values;
}

inline const char * const *EnumNamesAttestationDisposition() {
  static const char * const names[3] = {
    "used",
    "ignored",
    nullptr
  };
  return names;
}

inline const char *EnumNameAttestationDisposition(AttestationDisposition e) {
  if (::flatbuffers::IsOutRange(e, AttestationDisposition::used, AttestationDisposition::ignored)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAttestationDisposition()[index];
}

enum class EventPayload : uint8_t {
  NONE = 0,
  UserMsg = 1,
  DeliveredMsg = 2,
  ToolCall = 3,
  ToolResult = 4,
  Reasoning = 5,
  ProviderFrame = 6,
  MediaRef = 7,
  Effect = 8,
  Approval = 9,
  Outcome = 10,
  Checkpoint = 11,
  Supervisor = 12,
  Recovery = 13,
  IntentSet = 14,
  LoopOpened = 15,
  LoopClosed = 16,
  Assertion = 17,
  Consolidation = 18,
  Embedding = 19,
  Retract = 20,
  Attestation = 21,
  MIN = NONE,
  MAX = Attestation
};

inline const EventPayload (&EnumValuesEventPayload())[22] {
  static const EventPayload values[] = {
    EventPayload::NONE,
    EventPayload::UserMsg,
    EventPayload::DeliveredMsg,
    EventPayload::ToolCall,
    EventPayload::ToolResult,
    EventPayload::Reasoning,
    EventPayload::ProviderFrame,
    EventPayload::MediaRef,
    EventPayload::Effect,
    EventPayload::Approval,
    EventPayload::Outcome,
    EventPayload::Checkpoint,
    EventPayload::Supervisor,
    EventPayload::Recovery,
    EventPayload::IntentSet,
    EventPayload::LoopOpened,
    EventPayload::LoopClosed,
    EventPayload::Assertion,
    EventPayload::Consolidation,
    EventPayload::Embedding,
    EventPayload::Retract,
    EventPayload::Attestation
  };
  return values;
}

inline const char * const *EnumNamesEventPayload() {
  static const char * const names[23] = {
    "NONE",
    "UserMsg",
    "DeliveredMsg",
    "ToolCall",
    "ToolResult",
    "Reasoning",
    "ProviderFrame",
    "MediaRef",
    "Effect",
    "Approval",
    "Outcome",
    "Checkpoint",
    "Supervisor",
    "Recovery",
    "IntentSet",
    "LoopOpened",
    "LoopClosed",
    "Assertion",
    "Consolidation",
    "Embedding",
    "Retract",
    "Attestation",
    nullptr
  };
  return names;
}

inline const char *EnumNameEventPayload(EventPayload e) {
  if (::flatbuffers::IsOutRange(e, EventPayload::NONE, EventPayload::Attestation)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEventPayload()[index];
}

template<typename T> struct EventPayloadTraits {
  static const EventPayload enum_value = EventPayload::NONE;
};

template<> struct EventPayloadTraits<neocortex::schema::UserMsg> {
  static const EventPayload enum_value = EventPayload::UserMsg;
};

template<> struct EventPayloadTraits<neocortex::schema::DeliveredMsg> {
  static const EventPayload enum_value = EventPayload::DeliveredMsg;
};

template<> struct EventPayloadTraits<neocortex::schema::ToolCall> {
  static const EventPayload enum_value = EventPayload::ToolCall;
};

template<> struct EventPayloadTraits<neocortex::schema::ToolResult> {
  static const EventPayload enum_value = EventPayload::ToolResult;
};

template<> struct EventPayloadTraits<neocortex::schema::Reasoning> {
  static const EventPayload enum_value = EventPayload::Reasoning;
};

template<> struct EventPayloadTraits<neocortex::schema::ProviderFrame> {
  static const EventPayload enum_value = EventPayload::ProviderFrame;
};

template<> struct EventPayloadTraits<neocortex::schema::MediaRef> {
  static const EventPayload enum_value = EventPayload::MediaRef;
};

template<> struct EventPayloadTraits<neocortex::schema::Effect> {
  static const EventPayload enum_value = EventPayload::Effect;
};

template<> struct EventPayloadTraits<neocortex::schema::Approval> {
  static const EventPayload enum_value = EventPayload::Approval;
};

template<> struct EventPayloadTraits<neocortex::schema::Outcome> {
  static const EventPayload enum_value = EventPayload::Outcome;
};

template<> struct EventPayloadTraits<neocortex::schema::Checkpoint> {
  static const EventPayload enum_value = EventPayload::Checkpoint;
};

template<> struct EventPayloadTraits<neocortex::schema::Supervisor> {
  static const EventPayload enum_value = EventPayload::Supervisor;
};

template<> struct EventPayloadTraits<neocortex::schema::Recovery> {
  static const EventPayload enum_value = EventPayload::Recovery;
};

template<> struct EventPayloadTraits<neocortex::schema::IntentSet> {
  static const EventPayload enum_value = EventPayload::IntentSet;
};

template<> struct EventPayloadTraits<neocortex::schema::LoopOpened> {
  static const EventPayload enum_value = EventPayload::LoopOpened;
};

template<> struct EventPayloadTraits<neocortex::schema::LoopClosed> {
  static const EventPayload enum_value = EventPayload::LoopClosed;
};

template<> struct EventPayloadTraits<neocortex::schema::Assertion> {
  static const EventPayload enum_value = EventPayload::Assertion;
};

template<> struct EventPayloadTraits<neocortex::schema::Consolidation> {
  static const EventPayload enum_value = EventPayload::Consolidation;
};

template<> struct EventPayloadTraits<neocortex::schema::Embedding> {
  static const EventPayload enum_value = EventPayload::Embedding;
};

template<> struct EventPayloadTraits<neocortex::schema::Retract> {
  static const EventPayload enum_value = EventPayload::Retract;
};

template<> struct EventPayloadTraits<neocortex::schema::Attestation> {
  static const EventPayload enum_value = EventPayload::Attestation;
};

template <bool B = false>
bool VerifyEventPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EventPayload type);
template <bool B = false>
bool VerifyEventPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<EventPayload> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) ProvenanceRange FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t first_lsn_;
  uint64_t last_lsn_;

 public:
  struct Traits;
  ProvenanceRange()
      : first_lsn_(0),
        last_lsn_(0) {
  }
  ProvenanceRange(uint64_t _first_lsn, uint64_t _last_lsn)
      : first_lsn_(::flatbuffers::EndianScalar(_first_lsn)),
        last_lsn_(::flatbuffers::EndianScalar(_last_lsn)) {
  }
  uint64_t first_lsn() const {
    return ::flatbuffers::EndianScalar(first_lsn_);
  }
  uint64_t last_lsn() const {
    return ::flatbuffers::EndianScalar(last_lsn_);
  }
};
FLATBUFFERS_STRUCT_END(ProvenanceRange, 16);

struct ProvenanceRange::Traits {
  using type = ProvenanceRange;
};

struct UserMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UserMsgBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTENT = 4
  };
  const ::flatbuffers::Vector<uint8_t> *content() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CONTENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CONTENT) &&
           verifier.VerifyVector(content()) &&
           verifier.EndTable();
  }
};

struct UserMsgBuilder {
  typedef UserMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_content(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> content) {
    fbb_.AddOffset(UserMsg::VT_CONTENT, content);
  }
  explicit UserMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UserMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UserMsg>(end);
    fbb_.Required(o, UserMsg::VT_CONTENT);
    return o;
  }
};

inline ::flatbuffers::Offset<UserMsg> CreateUserMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> content = 0) {
  UserMsgBuilder builder_(_fbb);
  builder_.add_content(content);
  return builder_.Finish();
}

struct UserMsg::Traits {
  using type = UserMsg;
  static auto constexpr Create = CreateUserMsg;
};

inline ::flatbuffers::Offset<UserMsg> CreateUserMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *content = nullptr) {
  auto content__ = content ? _fbb.CreateVector<uint8_t>(*content) : 0;
  return neocortex::schema::CreateUserMsg(
      _fbb,
      content__);
}

struct DeliveredMsg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeliveredMsgBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTENT = 4
  };
  const ::flatbuffers::Vector<uint8_t> *content() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CONTENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CONTENT) &&
           verifier.VerifyVector(content()) &&
           verifier.EndTable();
  }
};

struct DeliveredMsgBuilder {
  typedef DeliveredMsg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_content(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> content) {
    fbb_.AddOffset(DeliveredMsg::VT_CONTENT, content);
  }
  explicit DeliveredMsgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeliveredMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeliveredMsg>(end);
    fbb_.Required(o, DeliveredMsg::VT_CONTENT);
    return o;
  }
};

inline ::flatbuffers::Offset<DeliveredMsg> CreateDeliveredMsg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> content = 0) {
  DeliveredMsgBuilder builder_(_fbb);
  builder_.add_content(content);
  return builder_.Finish();
}

struct DeliveredMsg::Traits {
  using type = DeliveredMsg;
  static auto constexpr Create = CreateDeliveredMsg;
};

inline ::flatbuffers::Offset<DeliveredMsg> CreateDeliveredMsgDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *content = nullptr) {
  auto content__ = content ? _fbb.CreateVector<uint8_t>(*content) : 0;
  return neocortex::schema::CreateDeliveredMsg(
      _fbb,
      content__);
}

struct ToolCall FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ToolCallBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CALL_ID = 4,
    VT_TOOL_NAME = 6,
    VT_ARGUMENTS = 8
  };
  const ::flatbuffers::Vector<uint8_t> *call_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CALL_ID);
  }
  const ::flatbuffers::String *tool_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TOOL_NAME);
  }
  const ::flatbuffers::Vector<uint8_t> *arguments() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_ARGUMENTS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CALL_ID) &&
           verifier.VerifyVector(call_id()) &&
           VerifyOffsetRequired(verifier, VT_TOOL_NAME) &&
           verifier.VerifyString(tool_name()) &&
           VerifyOffsetRequired(verifier, VT_ARGUMENTS) &&
           verifier.VerifyVector(arguments()) &&
           verifier.EndTable();
  }
};

struct ToolCallBuilder {
  typedef ToolCall Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_call_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> call_id) {
    fbb_.AddOffset(ToolCall::VT_CALL_ID, call_id);
  }
  void add_tool_name(::flatbuffers::Offset<::flatbuffers::String> tool_name) {
    fbb_.AddOffset(ToolCall::VT_TOOL_NAME, tool_name);
  }
  void add_arguments(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> arguments) {
    fbb_.AddOffset(ToolCall::VT_ARGUMENTS, arguments);
  }
  explicit ToolCallBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ToolCall> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ToolCall>(end);
    fbb_.Required(o, ToolCall::VT_CALL_ID);
    fbb_.Required(o, ToolCall::VT_TOOL_NAME);
    fbb_.Required(o, ToolCall::VT_ARGUMENTS);
    return o;
  }
};

inline ::flatbuffers::Offset<ToolCall> CreateToolCall(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> call_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> tool_name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> arguments = 0) {
  ToolCallBuilder builder_(_fbb);
  builder_.add_arguments(arguments);
  builder_.add_tool_name(tool_name);
  builder_.add_call_id(call_id);
  return builder_.Finish();
}

struct ToolCall::Traits {
  using type = ToolCall;
  static auto constexpr Create = CreateToolCall;
};

inline ::flatbuffers::Offset<ToolCall> CreateToolCallDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *call_id = nullptr,
    const char *tool_name = nullptr,
    const std::vector<uint8_t> *arguments = nullptr) {
  auto call_id__ = call_id ? _fbb.CreateVector<uint8_t>(*call_id) : 0;
  auto tool_name__ = tool_name ? _fbb.CreateString(tool_name) : 0;
  auto arguments__ = arguments ? _fbb.CreateVector<uint8_t>(*arguments) : 0;
  return neocortex::schema::CreateToolCall(
      _fbb,
      call_id__,
      tool_name__,
      arguments__);
}

struct ToolResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ToolResultBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CALL_ID = 4,
    VT_TOOL_CALL_LSN = 6,
    VT_STATUS = 8,
    VT_RESULT = 10
  };
  const ::flatbuffers::Vector<uint8_t> *call_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CALL_ID);
  }
  uint64_t tool_call_lsn() const {
    return GetField<uint64_t>(VT_TOOL_CALL_LSN, 0);
  }
  neocortex::schema::ResultStatus status() const {
    return static_cast<neocortex::schema::ResultStatus>(GetField<uint8_t>(VT_STATUS, 0));
  }
  const ::flatbuffers::Vector<uint8_t> *result() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_RESULT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CALL_ID) &&
           verifier.VerifyVector(call_id()) &&
           VerifyField<uint64_t>(verifier, VT_TOOL_CALL_LSN, 8) &&
           VerifyField<uint8_t>(verifier, VT_STATUS, 1) &&
           VerifyOffsetRequired(verifier, VT_RESULT) &&
           verifier.VerifyVector(result()) &&
           verifier.EndTable();
  }
};

struct ToolResultBuilder {
  typedef ToolResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_call_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> call_id) {
    fbb_.AddOffset(ToolResult::VT_CALL_ID, call_id);
  }
  void add_tool_call_lsn(uint64_t tool_call_lsn) {
    fbb_.AddElement<uint64_t>(ToolResult::VT_TOOL_CALL_LSN, tool_call_lsn, 0);
  }
  void add_status(neocortex::schema::ResultStatus status) {
    fbb_.AddElement<uint8_t>(ToolResult::VT_STATUS, static_cast<uint8_t>(status), 0);
  }
  void add_result(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> result) {
    fbb_.AddOffset(ToolResult::VT_RESULT, result);
  }
  explicit ToolResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ToolResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ToolResult>(end);
    fbb_.Required(o, ToolResult::VT_CALL_ID);
    fbb_.Required(o, ToolResult::VT_RESULT);
    return o;
  }
};

inline ::flatbuffers::Offset<ToolResult> CreateToolResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> call_id = 0,
    uint64_t tool_call_lsn = 0,
    neocortex::schema::ResultStatus status = neocortex::schema::ResultStatus::ok,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> result = 0) {
  ToolResultBuilder builder_(_fbb);
  builder_.add_tool_call_lsn(tool_call_lsn);
  builder_.add_result(result);
  builder_.add_call_id(call_id);
  builder_.add_status(status);
  return builder_.Finish();
}

struct ToolResult::Traits {
  using type = ToolResult;
  static auto constexpr Create = CreateToolResult;
};

inline ::flatbuffers::Offset<ToolResult> CreateToolResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *call_id = nullptr,
    uint64_t tool_call_lsn = 0,
    neocortex::schema::ResultStatus status = neocortex::schema::ResultStatus::ok,
    const std::vector<uint8_t> *result = nullptr) {
  auto call_id__ = call_id ? _fbb.CreateVector<uint8_t>(*call_id) : 0;
  auto result__ = result ? _fbb.CreateVector<uint8_t>(*result) : 0;
  return neocortex::schema::CreateToolResult(
      _fbb,
      call_id__,
      tool_call_lsn,
      status,
      result__);
}

struct Reasoning FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReasoningBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTENT = 4
  };
  const ::flatbuffers::Vector<uint8_t> *content() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CONTENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CONTENT) &&
           verifier.VerifyVector(content()) &&
           verifier.EndTable();
  }
};

struct ReasoningBuilder {
  typedef Reasoning Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_content(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> content) {
    fbb_.AddOffset(Reasoning::VT_CONTENT, content);
  }
  explicit ReasoningBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Reasoning> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Reasoning>(end);
    fbb_.Required(o, Reasoning::VT_CONTENT);
    return o;
  }
};

inline ::flatbuffers::Offset<Reasoning> CreateReasoning(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> content = 0) {
  ReasoningBuilder builder_(_fbb);
  builder_.add_content(content);
  return builder_.Finish();
}

struct Reasoning::Traits {
  using type = Reasoning;
  static auto constexpr Create = CreateReasoning;
};

inline ::flatbuffers::Offset<Reasoning> CreateReasoningDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *content = nullptr) {
  auto content__ = content ? _fbb.CreateVector<uint8_t>(*content) : 0;
  return neocortex::schema::CreateReasoning(
      _fbb,
      content__);
}

struct ProviderFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ProviderFrameBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROVIDER = 4,
    VT_API_CONTENT = 6
  };
  const ::flatbuffers::String *provider() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROVIDER);
  }
  const ::flatbuffers::Vector<uint8_t> *api_content() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_API_CONTENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_PROVIDER) &&
           verifier.VerifyString(provider()) &&
           VerifyOffsetRequired(verifier, VT_API_CONTENT) &&
           verifier.VerifyVector(api_content()) &&
           verifier.EndTable();
  }
};

struct ProviderFrameBuilder {
  typedef ProviderFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_provider(::flatbuffers::Offset<::flatbuffers::String> provider) {
    fbb_.AddOffset(ProviderFrame::VT_PROVIDER, provider);
  }
  void add_api_content(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> api_content) {
    fbb_.AddOffset(ProviderFrame::VT_API_CONTENT, api_content);
  }
  explicit ProviderFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ProviderFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ProviderFrame>(end);
    fbb_.Required(o, ProviderFrame::VT_PROVIDER);
    fbb_.Required(o, ProviderFrame::VT_API_CONTENT);
    return o;
  }
};

inline ::flatbuffers::Offset<ProviderFrame> CreateProviderFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> provider = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> api_content = 0) {
  ProviderFrameBuilder builder_(_fbb);
  builder_.add_api_content(api_content);
  builder_.add_provider(provider);
  return builder_.Finish();
}

struct ProviderFrame::Traits {
  using type = ProviderFrame;
  static auto constexpr Create = CreateProviderFrame;
};

inline ::flatbuffers::Offset<ProviderFrame> CreateProviderFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *provider = nullptr,
    const std::vector<uint8_t> *api_content = nullptr) {
  auto provider__ = provider ? _fbb.CreateString(provider) : 0;
  auto api_content__ = api_content ? _fbb.CreateVector<uint8_t>(*api_content) : 0;
  return neocortex::schema::CreateProviderFrame(
      _fbb,
      provider__,
      api_content__);
}

struct MediaRef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MediaRefBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_URI = 4,
    VT_MEDIA_TYPE = 6,
    VT_DIGEST = 8
  };
  const ::flatbuffers::String *uri() const {
    return GetPointer<const ::flatbuffers::String *>(VT_URI);
  }
  const ::flatbuffers::String *media_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MEDIA_TYPE);
  }
  const ::flatbuffers::Vector<uint8_t> *digest() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DIGEST);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_URI) &&
           verifier.VerifyString(uri()) &&
           VerifyOffsetRequired(verifier, VT_MEDIA_TYPE) &&
           verifier.VerifyString(media_type()) &&
           VerifyOffsetRequired(verifier, VT_DIGEST) &&
           verifier.VerifyVector(digest()) &&
           verifier.EndTable();
  }
};

struct MediaRefBuilder {
  typedef MediaRef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uri(::flatbuffers::Offset<::flatbuffers::String> uri) {
    fbb_.AddOffset(MediaRef::VT_URI, uri);
  }
  void add_media_type(::flatbuffers::Offset<::flatbuffers::String> media_type) {
    fbb_.AddOffset(MediaRef::VT_MEDIA_TYPE, media_type);
  }
  void add_digest(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> digest) {
    fbb_.AddOffset(MediaRef::VT_DIGEST, digest);
  }
  explicit MediaRefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MediaRef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MediaRef>(end);
    fbb_.Required(o, MediaRef::VT_URI);
    fbb_.Required(o, MediaRef::VT_MEDIA_TYPE);
    fbb_.Required(o, MediaRef::VT_DIGEST);
    return o;
  }
};

inline ::flatbuffers::Offset<MediaRef> CreateMediaRef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> uri = 0,
    ::flatbuffers::Offset<::flatbuffers::String> media_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> digest = 0) {
  MediaRefBuilder builder_(_fbb);
  builder_.add_digest(digest);
  builder_.add_media_type(media_type);
  builder_.add_uri(uri);
  return builder_.Finish();
}

struct MediaRef::Traits {
  using type = MediaRef;
  static auto constexpr Create = CreateMediaRef;
};

inline ::flatbuffers::Offset<MediaRef> CreateMediaRefDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *uri = nullptr,
    const char *media_type = nullptr,
    const std::vector<uint8_t> *digest = nullptr) {
  auto uri__ = uri ? _fbb.CreateString(uri) : 0;
  auto media_type__ = media_type ? _fbb.CreateString(media_type) : 0;
  auto digest__ = digest ? _fbb.CreateVector<uint8_t>(*digest) : 0;
  return neocortex::schema::CreateMediaRef(
      _fbb,
      uri__,
      media_type__,
      digest__);
}

struct Effect FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EffectBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EFFECT_ID = 4,
    VT_TOOL_CALL_LSN = 6,
    VT_STATE = 8
  };
  const ::flatbuffers::Vector<uint8_t> *effect_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_EFFECT_ID);
  }
  uint64_t tool_call_lsn() const {
    return GetField<uint64_t>(VT_TOOL_CALL_LSN, 0);
  }
  neocortex::schema::EffectState state() const {
    return static_cast<neocortex::schema::EffectState>(GetField<uint8_t>(VT_STATE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_EFFECT_ID) &&
           verifier.VerifyVector(effect_id()) &&
           VerifyField<uint64_t>(verifier, VT_TOOL_CALL_LSN, 8) &&
           VerifyField<uint8_t>(verifier, VT_STATE, 1) &&
           verifier.EndTable();
  }
};

struct EffectBuilder {
  typedef Effect Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_effect_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> effect_id) {
    fbb_.AddOffset(Effect::VT_EFFECT_ID, effect_id);
  }
  void add_tool_call_lsn(uint64_t tool_call_lsn) {
    fbb_.AddElement<uint64_t>(Effect::VT_TOOL_CALL_LSN, tool_call_lsn, 0);
  }
  void add_state(neocortex::schema::EffectState state) {
    fbb_.AddElement<uint8_t>(Effect::VT_STATE, static_cast<uint8_t>(state), 0);
  }
  explicit EffectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Effect> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Effect>(end);
    fbb_.Required(o, Effect::VT_EFFECT_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<Effect> CreateEffect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> effect_id = 0,
    uint64_t tool_call_lsn = 0,
    neocortex::schema::EffectState state = neocortex::schema::EffectState::dispatched) {
  EffectBuilder builder_(_fbb);
  builder_.add_tool_call_lsn(tool_call_lsn);
  builder_.add_effect_id(effect_id);
  builder_.add_state(state);
  return builder_.Finish();
}

struct Effect::Traits {
  using type = Effect;
  static auto constexpr Create = CreateEffect;
};

inline ::flatbuffers::Offset<Effect> CreateEffectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *effect_id = nullptr,
    uint64_t tool_call_lsn = 0,
    neocortex::schema::EffectState state = neocortex::schema::EffectState::dispatched) {
  auto effect_id__ = effect_id ? _fbb.CreateVector<uint8_t>(*effect_id) : 0;
  return neocortex::schema::CreateEffect(
      _fbb,
      effect_id__,
      tool_call_lsn,
      state);
}

struct Approval FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ApprovalBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EFFECT_ID = 4,
    VT_DECISION = 6
  };
  const ::flatbuffers::Vector<uint8_t> *effect_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_EFFECT_ID);
  }
  neocortex::schema::ApprovalDecision decision() const {
    return static_cast<neocortex::schema::ApprovalDecision>(GetField<uint8_t>(VT_DECISION, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_EFFECT_ID) &&
           verifier.VerifyVector(effect_id()) &&
           VerifyField<uint8_t>(verifier, VT_DECISION, 1) &&
           verifier.EndTable();
  }
};

struct ApprovalBuilder {
  typedef Approval Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_effect_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> effect_id) {
    fbb_.AddOffset(Approval::VT_EFFECT_ID, effect_id);
  }
  void add_decision(neocortex::schema::ApprovalDecision decision) {
    fbb_.AddElement<uint8_t>(Approval::VT_DECISION, static_cast<uint8_t>(decision), 0);
  }
  explicit ApprovalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Approval> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Approval>(end);
    fbb_.Required(o, Approval::VT_EFFECT_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<Approval> CreateApproval(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> effect_id = 0,
    neocortex::schema::ApprovalDecision decision = neocortex::schema::ApprovalDecision::approved) {
  ApprovalBuilder builder_(_fbb);
  builder_.add_effect_id(effect_id);
  builder_.add_decision(decision);
  return builder_.Finish();
}

struct Approval::Traits {
  using type = Approval;
  static auto constexpr Create = CreateApproval;
};

inline ::flatbuffers::Offset<Approval> CreateApprovalDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *effect_id = nullptr,
    neocortex::schema::ApprovalDecision decision = neocortex::schema::ApprovalDecision::approved) {
  auto effect_id__ = effect_id ? _fbb.CreateVector<uint8_t>(*effect_id) : 0;
  return neocortex::schema::CreateApproval(
      _fbb,
      effect_id__,
      decision);
}

struct Outcome FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OutcomeBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EFFECT_ID = 4,
    VT_STATUS = 6,
    VT_DETAIL = 8
  };
  const ::flatbuffers::Vector<uint8_t> *effect_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_EFFECT_ID);
  }
  neocortex::schema::ResultStatus status() const {
    return static_cast<neocortex::schema::ResultStatus>(GetField<uint8_t>(VT_STATUS, 0));
  }
  const ::flatbuffers::Vector<uint8_t> *detail() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DETAIL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_EFFECT_ID) &&
           verifier.VerifyVector(effect_id()) &&
           VerifyField<uint8_t>(verifier, VT_STATUS, 1) &&
           VerifyOffsetRequired(verifier, VT_DETAIL) &&
           verifier.VerifyVector(detail()) &&
           verifier.EndTable();
  }
};

struct OutcomeBuilder {
  typedef Outcome Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_effect_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> effect_id) {
    fbb_.AddOffset(Outcome::VT_EFFECT_ID, effect_id);
  }
  void add_status(neocortex::schema::ResultStatus status) {
    fbb_.AddElement<uint8_t>(Outcome::VT_STATUS, static_cast<uint8_t>(status), 0);
  }
  void add_detail(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> detail) {
    fbb_.AddOffset(Outcome::VT_DETAIL, detail);
  }
  explicit OutcomeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Outcome> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Outcome>(end);
    fbb_.Required(o, Outcome::VT_EFFECT_ID);
    fbb_.Required(o, Outcome::VT_DETAIL);
    return o;
  }
};

inline ::flatbuffers::Offset<Outcome> CreateOutcome(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> effect_id = 0,
    neocortex::schema::ResultStatus status = neocortex::schema::ResultStatus::ok,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> detail = 0) {
  OutcomeBuilder builder_(_fbb);
  builder_.add_detail(detail);
  builder_.add_effect_id(effect_id);
  builder_.add_status(status);
  return builder_.Finish();
}

struct Outcome::Traits {
  using type = Outcome;
  static auto constexpr Create = CreateOutcome;
};

inline ::flatbuffers::Offset<Outcome> CreateOutcomeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *effect_id = nullptr,
    neocortex::schema::ResultStatus status = neocortex::schema::ResultStatus::ok,
    const std::vector<uint8_t> *detail = nullptr) {
  auto effect_id__ = effect_id ? _fbb.CreateVector<uint8_t>(*effect_id) : 0;
  auto detail__ = detail ? _fbb.CreateVector<uint8_t>(*detail) : 0;
  return neocortex::schema::CreateOutcome(
      _fbb,
      effect_id__,
      status,
      detail__);
}

struct Checkpoint FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CheckpointBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CURSOR = 4
  };
  const ::flatbuffers::Vector<uint8_t> *cursor() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CURSOR);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CURSOR) &&
           verifier.VerifyVector(cursor()) &&
           verifier.EndTable();
  }
};

struct CheckpointBuilder {
  typedef Checkpoint Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cursor(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> cursor) {
    fbb_.AddOffset(Checkpoint::VT_CURSOR, cursor);
  }
  explicit CheckpointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Checkpoint> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Checkpoint>(end);
    fbb_.Required(o, Checkpoint::VT_CURSOR);
    return o;
  }
};

inline ::flatbuffers::Offset<Checkpoint> CreateCheckpoint(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> cursor = 0) {
  CheckpointBuilder builder_(_fbb);
  builder_.add_cursor(cursor);
  return builder_.Finish();
}

struct Checkpoint::Traits {
  using type = Checkpoint;
  static auto constexpr Create = CreateCheckpoint;
};

inline ::flatbuffers::Offset<Checkpoint> CreateCheckpointDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *cursor = nullptr) {
  auto cursor__ = cursor ? _fbb.CreateVector<uint8_t>(*cursor) : 0;
  return neocortex::schema::CreateCheckpoint(
      _fbb,
      cursor__);
}

struct Supervisor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SupervisorBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODE = 4,
    VT_EVIDENCE = 6
  };
  const ::flatbuffers::String *code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CODE);
  }
  const ::flatbuffers::Vector<uint8_t> *evidence() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_EVIDENCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CODE) &&
           verifier.VerifyString(code()) &&
           VerifyOffsetRequired(verifier, VT_EVIDENCE) &&
           verifier.VerifyVector(evidence()) &&
           verifier.EndTable();
  }
};

struct SupervisorBuilder {
  typedef Supervisor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_code(::flatbuffers::Offset<::flatbuffers::String> code) {
    fbb_.AddOffset(Supervisor::VT_CODE, code);
  }
  void add_evidence(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> evidence) {
    fbb_.AddOffset(Supervisor::VT_EVIDENCE, evidence);
  }
  explicit SupervisorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Supervisor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Supervisor>(end);
    fbb_.Required(o, Supervisor::VT_CODE);
    fbb_.Required(o, Supervisor::VT_EVIDENCE);
    return o;
  }
};

inline ::flatbuffers::Offset<Supervisor> CreateSupervisor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> code = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> evidence = 0) {
  SupervisorBuilder builder_(_fbb);
  builder_.add_evidence(evidence);
  builder_.add_code(code);
  return builder_.Finish();
}

struct Supervisor::Traits {
  using type = Supervisor;
  static auto constexpr Create = CreateSupervisor;
};

inline ::flatbuffers::Offset<Supervisor> CreateSupervisorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *code = nullptr,
    const std::vector<uint8_t> *evidence = nullptr) {
  auto code__ = code ? _fbb.CreateString(code) : 0;
  auto evidence__ = evidence ? _fbb.CreateVector<uint8_t>(*evidence) : 0;
  return neocortex::schema::CreateSupervisor(
      _fbb,
      code__,
      evidence__);
}

struct Recovery FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RecoveryBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODE = 4,
    VT_TARGET_LSN = 6
  };
  const ::flatbuffers::String *code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CODE);
  }
  uint64_t target_lsn() const {
    return GetField<uint64_t>(VT_TARGET_LSN, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CODE) &&
           verifier.VerifyString(code()) &&
           VerifyField<uint64_t>(verifier, VT_TARGET_LSN, 8) &&
           verifier.EndTable();
  }
};

struct RecoveryBuilder {
  typedef Recovery Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_code(::flatbuffers::Offset<::flatbuffers::String> code) {
    fbb_.AddOffset(Recovery::VT_CODE, code);
  }
  void add_target_lsn(uint64_t target_lsn) {
    fbb_.AddElement<uint64_t>(Recovery::VT_TARGET_LSN, target_lsn, 0);
  }
  explicit RecoveryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Recovery> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Recovery>(end);
    fbb_.Required(o, Recovery::VT_CODE);
    return o;
  }
};

inline ::flatbuffers::Offset<Recovery> CreateRecovery(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> code = 0,
    uint64_t target_lsn = 0) {
  RecoveryBuilder builder_(_fbb);
  builder_.add_target_lsn(target_lsn);
  builder_.add_code(code);
  return builder_.Finish();
}

struct Recovery::Traits {
  using type = Recovery;
  static auto constexpr Create = CreateRecovery;
};

inline ::flatbuffers::Offset<Recovery> CreateRecoveryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *code = nullptr,
    uint64_t target_lsn = 0) {
  auto code__ = code ? _fbb.CreateString(code) : 0;
  return neocortex::schema::CreateRecovery(
      _fbb,
      code__,
      target_lsn);
}

struct IntentSet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IntentSetBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECTIVE = 4
  };
  const ::flatbuffers::Vector<uint8_t> *objective() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_OBJECTIVE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_OBJECTIVE) &&
           verifier.VerifyVector(objective()) &&
           verifier.EndTable();
  }
};

struct IntentSetBuilder {
  typedef IntentSet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_objective(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> objective) {
    fbb_.AddOffset(IntentSet::VT_OBJECTIVE, objective);
  }
  explicit IntentSetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IntentSet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IntentSet>(end);
    fbb_.Required(o, IntentSet::VT_OBJECTIVE);
    return o;
  }
};

inline ::flatbuffers::Offset<IntentSet> CreateIntentSet(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> objective = 0) {
  IntentSetBuilder builder_(_fbb);
  builder_.add_objective(objective);
  return builder_.Finish();
}

struct IntentSet::Traits {
  using type = IntentSet;
  static auto constexpr Create = CreateIntentSet;
};

inline ::flatbuffers::Offset<IntentSet> CreateIntentSetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *objective = nullptr) {
  auto objective__ = objective ? _fbb.CreateVector<uint8_t>(*objective) : 0;
  return neocortex::schema::CreateIntentSet(
      _fbb,
      objective__);
}

struct LoopOpened FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoopOpenedBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LOOP_ID = 4,
    VT_OBJECTIVE = 6
  };
  const ::flatbuffers::Vector<uint8_t> *loop_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_LOOP_ID);
  }
  const ::flatbuffers::Vector<uint8_t> *objective() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_OBJECTIVE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_LOOP_ID) &&
           verifier.VerifyVector(loop_id()) &&
           VerifyOffsetRequired(verifier, VT_OBJECTIVE) &&
           verifier.VerifyVector(objective()) &&
           verifier.EndTable();
  }
};

struct LoopOpenedBuilder {
  typedef LoopOpened Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_loop_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> loop_id) {
    fbb_.AddOffset(LoopOpened::VT_LOOP_ID, loop_id);
  }
  void add_objective(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> objective) {
    fbb_.AddOffset(LoopOpened::VT_OBJECTIVE, objective);
  }
  explicit LoopOpenedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoopOpened> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoopOpened>(end);
    fbb_.Required(o, LoopOpened::VT_LOOP_ID);
    fbb_.Required(o, LoopOpened::VT_OBJECTIVE);
    return o;
  }
};

inline ::flatbuffers::Offset<LoopOpened> CreateLoopOpened(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> loop_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> objective = 0) {
  LoopOpenedBuilder builder_(_fbb);
  builder_.add_objective(objective);
  builder_.add_loop_id(loop_id);
  return builder_.Finish();
}

struct LoopOpened::Traits {
  using type = LoopOpened;
  static auto constexpr Create = CreateLoopOpened;
};

inline ::flatbuffers::Offset<LoopOpened> CreateLoopOpenedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *loop_id = nullptr,
    const std::vector<uint8_t> *objective = nullptr) {
  auto loop_id__ = loop_id ? _fbb.CreateVector<uint8_t>(*loop_id) : 0;
  auto objective__ = objective ? _fbb.CreateVector<uint8_t>(*objective) : 0;
  return neocortex::schema::CreateLoopOpened(
      _fbb,
      loop_id__,
      objective__);
}

struct LoopClosed FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoopClosedBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LOOP_ID = 4,
    VT_REASON = 6,
    VT_CAUSE = 8
  };
  const ::flatbuffers::Vector<uint8_t> *loop_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_LOOP_ID);
  }
  neocortex::schema::LoopCloseReason reason() const {
    return static_cast<neocortex::schema::LoopCloseReason>(GetField<uint8_t>(VT_REASON, 0));
  }
  const ::flatbuffers::Vector<uint8_t> *cause() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CAUSE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_LOOP_ID) &&
           verifier.VerifyVector(loop_id()) &&
           VerifyField<uint8_t>(verifier, VT_REASON, 1) &&
           VerifyOffsetRequired(verifier, VT_CAUSE) &&
           verifier.VerifyVector(cause()) &&
           verifier.EndTable();
  }
};

struct LoopClosedBuilder {
  typedef LoopClosed Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_loop_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> loop_id) {
    fbb_.AddOffset(LoopClosed::VT_LOOP_ID, loop_id);
  }
  void add_reason(neocortex::schema::LoopCloseReason reason) {
    fbb_.AddElement<uint8_t>(LoopClosed::VT_REASON, static_cast<uint8_t>(reason), 0);
  }
  void add_cause(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> cause) {
    fbb_.AddOffset(LoopClosed::VT_CAUSE, cause);
  }
  explicit LoopClosedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoopClosed> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoopClosed>(end);
    fbb_.Required(o, LoopClosed::VT_LOOP_ID);
    fbb_.Required(o, LoopClosed::VT_CAUSE);
    return o;
  }
};

inline ::flatbuffers::Offset<LoopClosed> CreateLoopClosed(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> loop_id = 0,
    neocortex::schema::LoopCloseReason reason = neocortex::schema::LoopCloseReason::done,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> cause = 0) {
  LoopClosedBuilder builder_(_fbb);
  builder_.add_cause(cause);
  builder_.add_loop_id(loop_id);
  builder_.add_reason(reason);
  return builder_.Finish();
}

struct LoopClosed::Traits {
  using type = LoopClosed;
  static auto constexpr Create = CreateLoopClosed;
};

inline ::flatbuffers::Offset<LoopClosed> CreateLoopClosedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *loop_id = nullptr,
    neocortex::schema::LoopCloseReason reason = neocortex::schema::LoopCloseReason::done,
    const std::vector<uint8_t> *cause = nullptr) {
  auto loop_id__ = loop_id ? _fbb.CreateVector<uint8_t>(*loop_id) : 0;
  auto cause__ = cause ? _fbb.CreateVector<uint8_t>(*cause) : 0;
  return neocortex::schema::CreateLoopClosed(
      _fbb,
      loop_id__,
      reason,
      cause__);
}

struct Assertion FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AssertionBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BELIEF_ID = 4,
    VT_BELIEF_TYPE = 6,
    VT_CANONICAL_IDENTITY = 8,
    VT_VALUE = 10,
    VT_VALID_FROM_NS = 12,
    VT_VALID_TO_NS = 14,
    VT_PROVENANCE = 16,
    VT_CONFLICT_DOMAIN = 18,
    VT_CLAIM = 20
  };
  const ::flatbuffers::Vector<uint8_t> *belief_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BELIEF_ID);
  }
  neocortex::schema::BeliefType belief_type() const {
    return static_cast<neocortex::schema::BeliefType>(GetField<uint8_t>(VT_BELIEF_TYPE, 0));
  }
  const ::flatbuffers::String *canonical_identity() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CANONICAL_IDENTITY);
  }
  const ::flatbuffers::Vector<uint8_t> *value() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_VALUE);
  }
  int64_t valid_from_ns() const {
    return GetField<int64_t>(VT_VALID_FROM_NS, 0);
  }
  int64_t valid_to_ns() const {
    return GetField<int64_t>(VT_VALID_TO_NS, 0);
  }
  const ::flatbuffers::Vector<const neocortex::schema::ProvenanceRange *> *provenance() const {
    return GetPointer<const ::flatbuffers::Vector<const neocortex::schema::ProvenanceRange *> *>(VT_PROVENANCE);
  }
  const ::flatbuffers::String *conflict_domain() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONFLICT_DOMAIN);
  }
  neocortex::schema::AssertionClaim claim() const {
    return static_cast<neocortex::schema::AssertionClaim>(GetField<uint8_t>(VT_CLAIM, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BELIEF_ID) &&
           verifier.VerifyVector(belief_id()) &&
           VerifyField<uint8_t>(verifier, VT_BELIEF_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_CANONICAL_IDENTITY) &&
           verifier.VerifyString(canonical_identity()) &&
           VerifyOffsetRequired(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           VerifyField<int64_t>(verifier, VT_VALID_FROM_NS, 8) &&
           VerifyField<int64_t>(verifier, VT_VALID_TO_NS, 8) &&
           VerifyOffsetRequired(verifier, VT_PROVENANCE) &&
           verifier.VerifyVector(provenance()) &&
           VerifyOffset(verifier, VT_CONFLICT_DOMAIN) &&
           verifier.VerifyString(conflict_domain()) &&
           VerifyField<uint8_t>(verifier, VT_CLAIM, 1) &&
           verifier.EndTable();
  }
};

struct AssertionBuilder {
  typedef Assertion Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_belief_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> belief_id) {
    fbb_.AddOffset(Assertion::VT_BELIEF_ID, belief_id);
  }
  void add_belief_type(neocortex::schema::BeliefType belief_type) {
    fbb_.AddElement<uint8_t>(Assertion::VT_BELIEF_TYPE, static_cast<uint8_t>(belief_type), 0);
  }
  void add_canonical_identity(::flatbuffers::Offset<::flatbuffers::String> canonical_identity) {
    fbb_.AddOffset(Assertion::VT_CANONICAL_IDENTITY, canonical_identity);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> value) {
    fbb_.AddOffset(Assertion::VT_VALUE, value);
  }
  void add_valid_from_ns(int64_t valid_from_ns) {
    fbb_.AddElement<int64_t>(Assertion::VT_VALID_FROM_NS, valid_from_ns, 0);
  }
  void add_valid_to_ns(int64_t valid_to_ns) {
    fbb_.AddElement<int64_t>(Assertion::VT_VALID_TO_NS, valid_to_ns, 0);
  }
  void add_provenance(::flatbuffers::Offset<::flatbuffers::Vector<const neocortex::schema::ProvenanceRange *>> provenance) {
    fbb_.AddOffset(Assertion::VT_PROVENANCE, provenance);
  }
  void add_conflict_domain(::flatbuffers::Offset<::flatbuffers::String> conflict_domain) {
    fbb_.AddOffset(Assertion::VT_CONFLICT_DOMAIN, conflict_domain);
  }
  void add_claim(neocortex::schema::AssertionClaim claim) {
    fbb_.AddElement<uint8_t>(Assertion::VT_CLAIM, static_cast<uint8_t>(claim), 0);
  }
  explicit AssertionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Assertion> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Assertion>(end);
    fbb_.Required(o, Assertion::VT_BELIEF_ID);
    fbb_.Required(o, Assertion::VT_CANONICAL_IDENTITY);
    fbb_.Required(o, Assertion::VT_VALUE);
    fbb_.Required(o, Assertion::VT_PROVENANCE);
    return o;
  }
};

inline ::flatbuffers::Offset<Assertion> CreateAssertion(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> belief_id = 0,
    neocortex::schema::BeliefType belief_type = neocortex::schema::BeliefType::fact,
    ::flatbuffers::Offset<::flatbuffers::String> canonical_identity = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> value = 0,
    int64_t valid_from_ns = 0,
    int64_t valid_to_ns = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const neocortex::schema::ProvenanceRange *>> provenance = 0,
    ::flatbuffers::Offset<::flatbuffers::String> conflict_domain = 0,
    neocortex::schema::AssertionClaim claim = neocortex::schema::AssertionClaim::affirmative) {
  AssertionBuilder builder_(_fbb);
  builder_.add_valid_to_ns(valid_to_ns);
  builder_.add_valid_from_ns(valid_from_ns);
  builder_.add_conflict_domain(conflict_domain);
  builder_.add_provenance(provenance);
  builder_.add_value(value);
  builder_.add_canonical_identity(canonical_identity);
  builder_.add_belief_id(belief_id);
  builder_.add_claim(claim);
  builder_.add_belief_type(belief_type);
  return builder_.Finish();
}

struct Assertion::Traits {
  using type = Assertion;
  static auto constexpr Create = CreateAssertion;
};

inline ::flatbuffers::Offset<Assertion> CreateAssertionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *belief_id = nullptr,
    neocortex::schema::BeliefType belief_type = neocortex::schema::BeliefType::fact,
    const char *canonical_identity = nullptr,
    const std::vector<uint8_t> *value = nullptr,
    int64_t valid_from_ns = 0,
    int64_t valid_to_ns = 0,
    const std::vector<neocortex::schema::ProvenanceRange> *provenance = nullptr,
    const char *conflict_domain = nullptr,
    neocortex::schema::AssertionClaim claim = neocortex::schema::AssertionClaim::affirmative) {
  auto belief_id__ = belief_id ? _fbb.CreateVector<uint8_t>(*belief_id) : 0;
  auto canonical_identity__ = canonical_identity ? _fbb.CreateString(canonical_identity) : 0;
  auto value__ = value ? _fbb.CreateVector<uint8_t>(*value) : 0;
  auto provenance__ = provenance ? _fbb.CreateVectorOfStructs<neocortex::schema::ProvenanceRange>(*provenance) : 0;
  auto conflict_domain__ = conflict_domain ? _fbb.CreateString(conflict_domain) : 0;
  return neocortex::schema::CreateAssertion(
      _fbb,
      belief_id__,
      belief_type,
      canonical_identity__,
      value__,
      valid_from_ns,
      valid_to_ns,
      provenance__,
      conflict_domain__,
      claim);
}

struct Consolidation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConsolidationBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ASSERTIONS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<neocortex::schema::Assertion>> *assertions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<neocortex::schema::Assertion>> *>(VT_ASSERTIONS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ASSERTIONS) &&
           verifier.VerifyVector(assertions()) &&
           verifier.VerifyVectorOfTables(assertions()) &&
           verifier.EndTable();
  }
};

struct ConsolidationBuilder {
  typedef Consolidation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_assertions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<neocortex::schema::Assertion>>> assertions) {
    fbb_.AddOffset(Consolidation::VT_ASSERTIONS, assertions);
  }
  explicit ConsolidationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Consolidation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Consolidation>(end);
    fbb_.Required(o, Consolidation::VT_ASSERTIONS);
    return o;
  }
};

inline ::flatbuffers::Offset<Consolidation> CreateConsolidation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<neocortex::schema::Assertion>>> assertions = 0) {
  ConsolidationBuilder builder_(_fbb);
  builder_.add_assertions(assertions);
  return builder_.Finish();
}

struct Consolidation::Traits {
  using type = Consolidation;
  static auto constexpr Create = CreateConsolidation;
};

inline ::flatbuffers::Offset<Consolidation> CreateConsolidationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<neocortex::schema::Assertion>> *assertions = nullptr) {
  auto assertions__ = assertions ? _fbb.CreateVector<::flatbuffers::Offset<neocortex::schema::Assertion>>(*assertions) : 0;
  return neocortex::schema::CreateConsolidation(
      _fbb,
      assertions__);
}

struct Embedding FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EmbeddingBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_LSN = 4,
    VT_DIMENSION = 6,
    VT_QUANTIZED = 8,
    VT_BINARY_PREFILTER = 10
  };
  uint64_t target_lsn() const {
    return GetField<uint64_t>(VT_TARGET_LSN, 0);
  }
  uint32_t dimension() const {
    return GetField<uint32_t>(VT_DIMENSION, 0);
  }
  const ::flatbuffers::Vector<int8_t> *quantized() const {
    return GetPointer<const ::flatbuffers::Vector<int8_t> *>(VT_QUANTIZED);
  }
  const ::flatbuffers::Vector<uint8_t> *binary_prefilter() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BINARY_PREFILTER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TARGET_LSN, 8) &&
           VerifyField<uint32_t>(verifier, VT_DIMENSION, 4) &&
           VerifyOffsetRequired(verifier, VT_QUANTIZED) &&
           verifier.VerifyVector(quantized()) &&
           VerifyOffsetRequired(verifier, VT_BINARY_PREFILTER) &&
           verifier.VerifyVector(binary_prefilter()) &&
           verifier.EndTable();
  }
};

struct EmbeddingBuilder {
  typedef Embedding Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_lsn(uint64_t target_lsn) {
    fbb_.AddElement<uint64_t>(Embedding::VT_TARGET_LSN, target_lsn, 0);
  }
  void add_dimension(uint32_t dimension) {
    fbb_.AddElement<uint32_t>(Embedding::VT_DIMENSION, dimension, 0);
  }
  void add_quantized(::flatbuffers::Offset<::flatbuffers::Vector<int8_t>> quantized) {
    fbb_.AddOffset(Embedding::VT_QUANTIZED, quantized);
  }
  void add_binary_prefilter(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> binary_prefilter) {
    fbb_.AddOffset(Embedding::VT_BINARY_PREFILTER, binary_prefilter);
  }
  explicit EmbeddingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Embedding> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Embedding>(end);
    fbb_.Required(o, Embedding::VT_QUANTIZED);
    fbb_.Required(o, Embedding::VT_BINARY_PREFILTER);
    return o;
  }
};

inline ::flatbuffers::Offset<Embedding> CreateEmbedding(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t target_lsn = 0,
    uint32_t dimension = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int8_t>> quantized = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> binary_prefilter = 0) {
  EmbeddingBuilder builder_(_fbb);
  builder_.add_target_lsn(target_lsn);
  builder_.add_binary_prefilter(binary_prefilter);
  builder_.add_quantized(quantized);
  builder_.add_dimension(dimension);
  return builder_.Finish();
}

struct Embedding::Traits {
  using type = Embedding;
  static auto constexpr Create = CreateEmbedding;
};

inline ::flatbuffers::Offset<Embedding> CreateEmbeddingDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t target_lsn = 0,
    uint32_t dimension = 0,
    const std::vector<int8_t> *quantized = nullptr,
    const std::vector<uint8_t> *binary_prefilter = nullptr) {
  auto quantized__ = quantized ? _fbb.CreateVector<int8_t>(*quantized) : 0;
  auto binary_prefilter__ = binary_prefilter ? _fbb.CreateVector<uint8_t>(*binary_prefilter) : 0;
  return neocortex::schema::CreateEmbedding(
      _fbb,
      target_lsn,
      dimension,
      quantized__,
      binary_prefilter__);
}

struct Retract FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RetractBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BELIEF_ID = 4,
    VT_PROVENANCE = 6
  };
  const ::flatbuffers::Vector<uint8_t> *belief_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BELIEF_ID);
  }
  const ::flatbuffers::Vector<const neocortex::schema::ProvenanceRange *> *provenance() const {
    return GetPointer<const ::flatbuffers::Vector<const neocortex::schema::ProvenanceRange *> *>(VT_PROVENANCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BELIEF_ID) &&
           verifier.VerifyVector(belief_id()) &&
           VerifyOffsetRequired(verifier, VT_PROVENANCE) &&
           verifier.VerifyVector(provenance()) &&
           verifier.EndTable();
  }
};

struct RetractBuilder {
  typedef Retract Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_belief_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> belief_id) {
    fbb_.AddOffset(Retract::VT_BELIEF_ID, belief_id);
  }
  void add_provenance(::flatbuffers::Offset<::flatbuffers::Vector<const neocortex::schema::ProvenanceRange *>> provenance) {
    fbb_.AddOffset(Retract::VT_PROVENANCE, provenance);
  }
  explicit RetractBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Retract> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Retract>(end);
    fbb_.Required(o, Retract::VT_BELIEF_ID);
    fbb_.Required(o, Retract::VT_PROVENANCE);
    return o;
  }
};

inline ::flatbuffers::Offset<Retract> CreateRetract(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> belief_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const neocortex::schema::ProvenanceRange *>> provenance = 0) {
  RetractBuilder builder_(_fbb);
  builder_.add_provenance(provenance);
  builder_.add_belief_id(belief_id);
  return builder_.Finish();
}

struct Retract::Traits {
  using type = Retract;
  static auto constexpr Create = CreateRetract;
};

inline ::flatbuffers::Offset<Retract> CreateRetractDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *belief_id = nullptr,
    const std::vector<neocortex::schema::ProvenanceRange> *provenance = nullptr) {
  auto belief_id__ = belief_id ? _fbb.CreateVector<uint8_t>(*belief_id) : 0;
  auto provenance__ = provenance ? _fbb.CreateVectorOfStructs<neocortex::schema::ProvenanceRange>(*provenance) : 0;
  return neocortex::schema::CreateRetract(
      _fbb,
      belief_id__,
      provenance__);
}

struct Attestation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AttestationBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_LSN = 4,
    VT_DISPOSITION = 6
  };
  uint64_t target_lsn() const {
    return GetField<uint64_t>(VT_TARGET_LSN, 0);
  }
  neocortex::schema::AttestationDisposition disposition() const {
    return static_cast<neocortex::schema::AttestationDisposition>(GetField<uint8_t>(VT_DISPOSITION, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TARGET_LSN, 8) &&
           VerifyField<uint8_t>(verifier, VT_DISPOSITION, 1) &&
           verifier.EndTable();
  }
};

struct AttestationBuilder {
  typedef Attestation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_lsn(uint64_t target_lsn) {
    fbb_.AddElement<uint64_t>(Attestation::VT_TARGET_LSN, target_lsn, 0);
  }
  void add_disposition(neocortex::schema::AttestationDisposition disposition) {
    fbb_.AddElement<uint8_t>(Attestation::VT_DISPOSITION, static_cast<uint8_t>(disposition), 0);
  }
  explicit AttestationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Attestation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Attestation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Attestation> CreateAttestation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t target_lsn = 0,
    neocortex::schema::AttestationDisposition disposition = neocortex::schema::AttestationDisposition::used) {
  AttestationBuilder builder_(_fbb);
  builder_.add_target_lsn(target_lsn);
  builder_.add_disposition(disposition);
  return builder_.Finish();
}

struct Attestation::Traits {
  using type = Attestation;
  static auto constexpr Create = CreateAttestation;
};

struct EventEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventEnvelopeBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHEMA_VERSION = 4,
    VT_PAYLOAD_TYPE = 6,
    VT_PAYLOAD = 8,
    VT_CONNECTION_ID = 10,
    VT_CLIENT_SEQ = 12,
    VT_CLIENT_EVENT_INDEX = 14,
    VT_CLIENT_EVENT_COUNT = 16
  };
  uint16_t schema_version() const {
    return GetField<uint16_t>(VT_SCHEMA_VERSION, 1);
  }
  neocortex::schema::EventPayload payload_type() const {
    return static_cast<neocortex::schema::EventPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const neocortex::schema::UserMsg *payload_as_UserMsg() const {
    return payload_type() == neocortex::schema::EventPayload::UserMsg ? static_cast<const neocortex::schema::UserMsg *>(payload()) : nullptr;
  }
  const neocortex::schema::DeliveredMsg *payload_as_DeliveredMsg() const {
    return payload_type() == neocortex::schema::EventPayload::DeliveredMsg ? static_cast<const neocortex::schema::DeliveredMsg *>(payload()) : nullptr;
  }
  const neocortex::schema::ToolCall *payload_as_ToolCall() const {
    return payload_type() == neocortex::schema::EventPayload::ToolCall ? static_cast<const neocortex::schema::ToolCall *>(payload()) : nullptr;
  }
  const neocortex::schema::ToolResult *payload_as_ToolResult() const {
    return payload_type() == neocortex::schema::EventPayload::ToolResult ? static_cast<const neocortex::schema::ToolResult *>(payload()) : nullptr;
  }
  const neocortex::schema::Reasoning *payload_as_Reasoning() const {
    return payload_type() == neocortex::schema::EventPayload::Reasoning ? static_cast<const neocortex::schema::Reasoning *>(payload()) : nullptr;
  }
  const neocortex::schema::ProviderFrame *payload_as_ProviderFrame() const {
    return payload_type() == neocortex::schema::EventPayload::ProviderFrame ? static_cast<const neocortex::schema::ProviderFrame *>(payload()) : nullptr;
  }
  const neocortex::schema::MediaRef *payload_as_MediaRef() const {
    return payload_type() == neocortex::schema::EventPayload::MediaRef ? static_cast<const neocortex::schema::MediaRef *>(payload()) : nullptr;
  }
  const neocortex::schema::Effect *payload_as_Effect() const {
    return payload_type() == neocortex::schema::EventPayload::Effect ? static_cast<const neocortex::schema::Effect *>(payload()) : nullptr;
  }
  const neocortex::schema::Approval *payload_as_Approval() const {
    return payload_type() == neocortex::schema::EventPayload::Approval ? static_cast<const neocortex::schema::Approval *>(payload()) : nullptr;
  }
  const neocortex::schema::Outcome *payload_as_Outcome() const {
    return payload_type() == neocortex::schema::EventPayload::Outcome ? static_cast<const neocortex::schema::Outcome *>(payload()) : nullptr;
  }
  const neocortex::schema::Checkpoint *payload_as_Checkpoint() const {
    return payload_type() == neocortex::schema::EventPayload::Checkpoint ? static_cast<const neocortex::schema::Checkpoint *>(payload()) : nullptr;
  }
  const neocortex::schema::Supervisor *payload_as_Supervisor() const {
    return payload_type() == neocortex::schema::EventPayload::Supervisor ? static_cast<const neocortex::schema::Supervisor *>(payload()) : nullptr;
  }
  const neocortex::schema::Recovery *payload_as_Recovery() const {
    return payload_type() == neocortex::schema::EventPayload::Recovery ? static_cast<const neocortex::schema::Recovery *>(payload()) : nullptr;
  }
  const neocortex::schema::IntentSet *payload_as_IntentSet() const {
    return payload_type() == neocortex::schema::EventPayload::IntentSet ? static_cast<const neocortex::schema::IntentSet *>(payload()) : nullptr;
  }
  const neocortex::schema::LoopOpened *payload_as_LoopOpened() const {
    return payload_type() == neocortex::schema::EventPayload::LoopOpened ? static_cast<const neocortex::schema::LoopOpened *>(payload()) : nullptr;
  }
  const neocortex::schema::LoopClosed *payload_as_LoopClosed() const {
    return payload_type() == neocortex::schema::EventPayload::LoopClosed ? static_cast<const neocortex::schema::LoopClosed *>(payload()) : nullptr;
  }
  const neocortex::schema::Assertion *payload_as_Assertion() const {
    return payload_type() == neocortex::schema::EventPayload::Assertion ? static_cast<const neocortex::schema::Assertion *>(payload()) : nullptr;
  }
  const neocortex::schema::Consolidation *payload_as_Consolidation() const {
    return payload_type() == neocortex::schema::EventPayload::Consolidation ? static_cast<const neocortex::schema::Consolidation *>(payload()) : nullptr;
  }
  const neocortex::schema::Embedding *payload_as_Embedding() const {
    return payload_type() == neocortex::schema::EventPayload::Embedding ? static_cast<const neocortex::schema::Embedding *>(payload()) : nullptr;
  }
  const neocortex::schema::Retract *payload_as_Retract() const {
    return payload_type() == neocortex::schema::EventPayload::Retract ? static_cast<const neocortex::schema::Retract *>(payload()) : nullptr;
  }
  const neocortex::schema::Attestation *payload_as_Attestation() const {
    return payload_type() == neocortex::schema::EventPayload::Attestation ? static_cast<const neocortex::schema::Attestation *>(payload()) : nullptr;
  }
  const ::flatbuffers::Vector<uint8_t> *connection_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CONNECTION_ID);
  }
  uint64_t client_seq() const {
    return GetField<uint64_t>(VT_CLIENT_SEQ, 0);
  }
  uint32_t client_event_index() const {
    return GetField<uint32_t>(VT_CLIENT_EVENT_INDEX, 0);
  }
  uint32_t client_event_count() const {
    return GetField<uint32_t>(VT_CLIENT_EVENT_COUNT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_SCHEMA_VERSION, 2) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_PAYLOAD) &&
           VerifyEventPayload(verifier, payload(), payload_type()) &&
           VerifyOffset(verifier, VT_CONNECTION_ID) &&
           verifier.VerifyVector(connection_id()) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_SEQ, 8) &&
           VerifyField<uint32_t>(verifier, VT_CLIENT_EVENT_INDEX, 4) &&
           VerifyField<uint32_t>(verifier, VT_CLIENT_EVENT_COUNT, 4) &&
           verifier.EndTable();
  }
};

template<> inline const neocortex::schema::UserMsg *EventEnvelope::payload_as<neocortex::schema::UserMsg>() const {
  return payload_as_UserMsg();
}

template<> inline const neocortex::schema::DeliveredMsg *EventEnvelope::payload_as<neocortex::schema::DeliveredMsg>() const {
  return payload_as_DeliveredMsg();
}

template<> inline const neocortex::schema::ToolCall *EventEnvelope::payload_as<neocortex::schema::ToolCall>() const {
  return payload_as_ToolCall();
}

template<> inline const neocortex::schema::ToolResult *EventEnvelope::payload_as<neocortex::schema::ToolResult>() const {
  return payload_as_ToolResult();
}

template<> inline const neocortex::schema::Reasoning *EventEnvelope::payload_as<neocortex::schema::Reasoning>() const {
  return payload_as_Reasoning();
}

template<> inline const neocortex::schema::ProviderFrame *EventEnvelope::payload_as<neocortex::schema::ProviderFrame>() const {
  return payload_as_ProviderFrame();
}

template<> inline const neocortex::schema::MediaRef *EventEnvelope::payload_as<neocortex::schema::MediaRef>() const {
  return payload_as_MediaRef();
}

template<> inline const neocortex::schema::Effect *EventEnvelope::payload_as<neocortex::schema::Effect>() const {
  return payload_as_Effect();
}

template<> inline const neocortex::schema::Approval *EventEnvelope::payload_as<neocortex::schema::Approval>() const {
  return payload_as_Approval();
}

template<> inline const neocortex::schema::Outcome *EventEnvelope::payload_as<neocortex::schema::Outcome>() const {
  return payload_as_Outcome();
}

template<> inline const neocortex::schema::Checkpoint *EventEnvelope::payload_as<neocortex::schema::Checkpoint>() const {
  return payload_as_Checkpoint();
}

template<> inline const neocortex::schema::Supervisor *EventEnvelope::payload_as<neocortex::schema::Supervisor>() const {
  return payload_as_Supervisor();
}

template<> inline const neocortex::schema::Recovery *EventEnvelope::payload_as<neocortex::schema::Recovery>() const {
  return payload_as_Recovery();
}

template<> inline const neocortex::schema::IntentSet *EventEnvelope::payload_as<neocortex::schema::IntentSet>() const {
  return payload_as_IntentSet();
}

template<> inline const neocortex::schema::LoopOpened *EventEnvelope::payload_as<neocortex::schema::LoopOpened>() const {
  return payload_as_LoopOpened();
}

template<> inline const neocortex::schema::LoopClosed *EventEnvelope::payload_as<neocortex::schema::LoopClosed>() const {
  return payload_as_LoopClosed();
}

template<> inline const neocortex::schema::Assertion *EventEnvelope::payload_as<neocortex::schema::Assertion>() const {
  return payload_as_Assertion();
}

template<> inline const neocortex::schema::Consolidation *EventEnvelope::payload_as<neocortex::schema::Consolidation>() const {
  return payload_as_Consolidation();
}

template<> inline const neocortex::schema::Embedding *EventEnvelope::payload_as<neocortex::schema::Embedding>() const {
  return payload_as_Embedding();
}

template<> inline const neocortex::schema::Retract *EventEnvelope::payload_as<neocortex::schema::Retract>() const {
  return payload_as_Retract();
}

template<> inline const neocortex::schema::Attestation *EventEnvelope::payload_as<neocortex::schema::Attestation>() const {
  return payload_as_Attestation();
}

struct EventEnvelopeBuilder {
  typedef EventEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schema_version(uint16_t schema_version) {
    fbb_.AddElement<uint16_t>(EventEnvelope::VT_SCHEMA_VERSION, schema_version, 1);
  }
  void add_payload_type(neocortex::schema::EventPayload payload_type) {
    fbb_.AddElement<uint8_t>(EventEnvelope::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(EventEnvelope::VT_PAYLOAD, payload);
  }
  void add_connection_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> connection_id) {
    fbb_.AddOffset(EventEnvelope::VT_CONNECTION_ID, connection_id);
  }
  void add_client_seq(uint64_t client_seq) {
    fbb_.AddElement<uint64_t>(EventEnvelope::VT_CLIENT_SEQ, client_seq, 0);
  }
  void add_client_event_index(uint32_t client_event_index) {
    fbb_.AddElement<uint32_t>(EventEnvelope::VT_CLIENT_EVENT_INDEX, client_event_index, 0);
  }
  void add_client_event_count(uint32_t client_event_count) {
    fbb_.AddElement<uint32_t>(EventEnvelope::VT_CLIENT_EVENT_COUNT, client_event_count, 0);
  }
  explicit EventEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventEnvelope>(end);
    fbb_.Required(o, EventEnvelope::VT_PAYLOAD);
    return o;
  }
};

inline ::flatbuffers::Offset<EventEnvelope> CreateEventEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t schema_version = 1,
    neocortex::schema::EventPayload payload_type = neocortex::schema::EventPayload::NONE,
    ::flatbuffers::Offset<void> payload = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> connection_id = 0,
    uint64_t client_seq = 0,
    uint32_t client_event_index = 0,
    uint32_t client_event_count = 0) {
  EventEnvelopeBuilder builder_(_fbb);
  builder_.add_client_seq(client_seq);
  builder_.add_client_event_count(client_event_count);
  builder_.add_client_event_index(client_event_index);
  builder_.add_connection_id(connection_id);
  builder_.add_payload(payload);
  builder_.add_schema_version(schema_version);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

struct EventEnvelope::Traits {
  using type = EventEnvelope;
  static auto constexpr Create = CreateEventEnvelope;
};

inline ::flatbuffers::Offset<EventEnvelope> CreateEventEnvelopeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t schema_version = 1,
    neocortex::schema::EventPayload payload_type = neocortex::schema::EventPayload::NONE,
    ::flatbuffers::Offset<void> payload = 0,
    const std::vector<uint8_t> *connection_id = nullptr,
    uint64_t client_seq = 0,
    uint32_t client_event_index = 0,
    uint32_t client_event_count = 0) {
  auto connection_id__ = connection_id ? _fbb.CreateVector<uint8_t>(*connection_id) : 0;
  return neocortex::schema::CreateEventEnvelope(
      _fbb,
      schema_version,
      payload_type,
      payload,
      connection_id__,
      client_seq,
      client_event_index,
      client_event_count);
}

template <bool B>
inline bool VerifyEventPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EventPayload type) {
  switch (type) {
    case EventPayload::NONE: {
      return true;
    }
    case EventPayload::UserMsg: {
      auto ptr = reinterpret_cast<const neocortex::schema::UserMsg *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::DeliveredMsg: {
      auto ptr = reinterpret_cast<const neocortex::schema::DeliveredMsg *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::ToolCall: {
      auto ptr = reinterpret_cast<const neocortex::schema::ToolCall *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::ToolResult: {
      auto ptr = reinterpret_cast<const neocortex::schema::ToolResult *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Reasoning: {
      auto ptr = reinterpret_cast<const neocortex::schema::Reasoning *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::ProviderFrame: {
      auto ptr = reinterpret_cast<const neocortex::schema::ProviderFrame *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::MediaRef: {
      auto ptr = reinterpret_cast<const neocortex::schema::MediaRef *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Effect: {
      auto ptr = reinterpret_cast<const neocortex::schema::Effect *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Approval: {
      auto ptr = reinterpret_cast<const neocortex::schema::Approval *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Outcome: {
      auto ptr = reinterpret_cast<const neocortex::schema::Outcome *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Checkpoint: {
      auto ptr = reinterpret_cast<const neocortex::schema::Checkpoint *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Supervisor: {
      auto ptr = reinterpret_cast<const neocortex::schema::Supervisor *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Recovery: {
      auto ptr = reinterpret_cast<const neocortex::schema::Recovery *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::IntentSet: {
      auto ptr = reinterpret_cast<const neocortex::schema::IntentSet *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::LoopOpened: {
      auto ptr = reinterpret_cast<const neocortex::schema::LoopOpened *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::LoopClosed: {
      auto ptr = reinterpret_cast<const neocortex::schema::LoopClosed *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Assertion: {
      auto ptr = reinterpret_cast<const neocortex::schema::Assertion *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Consolidation: {
      auto ptr = reinterpret_cast<const neocortex::schema::Consolidation *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Embedding: {
      auto ptr = reinterpret_cast<const neocortex::schema::Embedding *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Retract: {
      auto ptr = reinterpret_cast<const neocortex::schema::Retract *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventPayload::Attestation: {
      auto ptr = reinterpret_cast<const neocortex::schema::Attestation *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyEventPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<EventPayload> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyEventPayload(
        verifier,  values->Get(i), types->GetEnum<EventPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const neocortex::schema::EventEnvelope *GetEventEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<neocortex::schema::EventEnvelope>(buf);
}

inline const neocortex::schema::EventEnvelope *GetSizePrefixedEventEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<neocortex::schema::EventEnvelope>(buf);
}

inline const char *EventEnvelopeIdentifier() {
  return "NCEV";
}

inline bool EventEnvelopeBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, EventEnvelopeIdentifier());
}

inline bool SizePrefixedEventEnvelopeBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, EventEnvelopeIdentifier(), true);
}

template <bool B = false>
inline bool VerifyEventEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<neocortex::schema::EventEnvelope>(EventEnvelopeIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedEventEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<neocortex::schema::EventEnvelope>(EventEnvelopeIdentifier());
}

inline void FinishEventEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<neocortex::schema::EventEnvelope> root) {
  fbb.Finish(root, EventEnvelopeIdentifier());
}

inline void FinishSizePrefixedEventEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<neocortex::schema::EventEnvelope> root) {
  fbb.FinishSizePrefixed(root, EventEnvelopeIdentifier());
}

}  // namespace schema
}  // namespace neocortex

#endif  // FLATBUFFERS_GENERATED_EVENTS_NEOCORTEX_SCHEMA_H_
