// kindle bridge — custom optical authoring template.
//
// Produces a BaseOptical-derived Solidity contract for the custom-optical tier
// (spec req.10). The output is SELF-CONTAINED — it inlines a faithful minimal
// IOptical + BaseOptical (semantically matching contracts/opticals/BaseOptical.sol:
// immutable poolRegistry+owner, onlyPool via PoolRegistry.getPoolMetadata
// staticcall, onlyOwner, no-op hook defaults) — so it compiles with plain solc
// and runs under Forge through Tachyon without needing the full contracts repo
// in the build context.
//
// Invariants enforced by the generator (req.10 ac_1/ac_6):
//   - getFlags() returns a bitmap whose set bits EXACTLY match overridden hooks.
//   - value-gating hooks (beforeSwap, beforeFeeDistribution) keep onlyPool.
//   - the contract stays immutable (only immutable/constant state).

export const HOOK_BITS = {
  beforeSwap: 0b0001,
  afterSwap: 0b0010,
  beforeFeeDistribution: 0b0100,
  afterFeeDistribution: 0b1000,
}

// Hooks that gate or adjust value — must keep onlyPool so only registered pools
// can drive them.
const VALUE_GATING = new Set(['beforeSwap', 'beforeFeeDistribution'])

const HOOK_SIGNATURES = {
  beforeSwap: {
    decl: 'function beforeSwap(address pool, address sender, bool isBuy, uint256 amountIn)',
    rets: 'returns (bool proceed, int256 amountDelta)',
    defaultBody: 'return (true, 0);',
  },
  afterSwap: {
    decl: 'function afterSwap(address pool, address sender, bool isBuy, uint256 amountIn, uint256 amountOut)',
    rets: 'returns (bytes4)',
    defaultBody: 'return IOptical.afterSwap.selector;',
  },
  beforeFeeDistribution: {
    decl: 'function beforeFeeDistribution(address pool, uint256 feeAmount)',
    rets: 'returns (uint256 adjustedFee)',
    defaultBody: 'return feeAmount;',
  },
  afterFeeDistribution: {
    decl: 'function afterFeeDistribution(address pool, uint256 feeAmount)',
    rets: 'returns (bytes4)',
    defaultBody: 'return IOptical.afterFeeDistribution.selector;',
  },
}

const SOLC_VERSION = '^0.8.24'

function flagsFor(hooks) {
  let f = 0
  for (const h of hooks) f |= HOOK_BITS[h] | 0
  return f
}

// buildCustomOptical(spec) -> { contractName, flags, source, ctorArgs, hooks }
//   spec.name              : contract name (default "CustomOptical")
//   spec.hooks             : array subset of the 4 hook names to override
//   spec.bodies            : { <hook>: "<solidity statements>" } override bodies
//   spec.immutables        : [{ type, name }] extra immutable config (ctor args)
//   spec.notes             : free-text doc comment (sanitised)
export function buildCustomOptical(spec = {}) {
  const contractName = sanitiseIdent(spec.name || 'CustomOptical')
  const hooks = [...new Set((spec.hooks || []).filter((h) => HOOK_BITS[h] !== undefined))]
  if (hooks.length === 0) {
    throw new Error('kindle optical: at least one hook must be overridden (beforeSwap, afterSwap, beforeFeeDistribution, afterFeeDistribution)')
  }
  const bodies = spec.bodies || {}
  const extraImmutables = (spec.immutables || []).map((m) => ({
    type: String(m.type).trim(),
    name: sanitiseIdent(m.name),
  }))
  const flags = flagsFor(hooks)

  const immutableDecls = extraImmutables
    .map((m) => `    ${m.type} public immutable ${m.name};`)
    .join('\n')
  const ctorExtraParams = extraImmutables.map((m) => `${m.type} _${m.name}`)
  const ctorExtraAssigns = extraImmutables
    .map((m) => `        ${m.name} = _${m.name};`)
    .join('\n')

  const hookFns = hooks.map((h) => renderHook(h, bodies[h])).join('\n\n')

  const ctorParams = ['address _poolRegistry', 'address _owner', ...ctorExtraParams].join(', ')

  const source = `// SPDX-License-Identifier: MIT
pragma solidity ${SOLC_VERSION};

// Generated by the Matrix kindle bridge (custom optical authoring template).
// Self-contained: inlines a minimal IOptical + BaseOptical matching
// KindleLaunch's contracts/opticals/BaseOptical.sol. Immutable once deployed.
${spec.notes ? '// ' + sanitiseComment(spec.notes) + '\n' : ''}
interface IOptical {
    function beforeSwap(address pool, address sender, bool isBuy, uint256 amountIn)
        external returns (bool proceed, int256 amountDelta);
    function afterSwap(address pool, address sender, bool isBuy, uint256 amountIn, uint256 amountOut)
        external returns (bytes4);
    function beforeFeeDistribution(address pool, uint256 feeAmount)
        external returns (uint256 adjustedFee);
    function afterFeeDistribution(address pool, uint256 feeAmount)
        external returns (bytes4);
    function getFlags() external view returns (uint8 flags);
}

abstract contract BaseOptical is IOptical {
    error NotPool();
    error NotOwner();

    address public immutable poolRegistry;
    address public immutable owner;

    constructor(address _poolRegistry, address _owner) {
        poolRegistry = _poolRegistry;
        owner = _owner;
    }

    modifier onlyPool() {
        if (!_isRegisteredPool(msg.sender)) revert NotPool();
        _;
    }

    modifier onlyOwner() {
        if (msg.sender != owner) revert NotOwner();
        _;
    }

    function beforeSwap(address, address, bool, uint256) external virtual override returns (bool, int256) {
        return (true, 0);
    }

    function afterSwap(address, address, bool, uint256, uint256) external virtual override returns (bytes4) {
        return IOptical.afterSwap.selector;
    }

    function beforeFeeDistribution(address, uint256 feeAmount) external virtual override returns (uint256) {
        return feeAmount;
    }

    function afterFeeDistribution(address, uint256) external virtual override returns (bytes4) {
        return IOptical.afterFeeDistribution.selector;
    }

    function getFlags() external view virtual override returns (uint8) {
        return 0;
    }

    function _isRegisteredPool(address pool) internal view returns (bool) {
        if (poolRegistry == address(0)) return true;
        (bool success, bytes memory data) = poolRegistry.staticcall(
            abi.encodeWithSignature("getPoolMetadata(address)", pool)
        );
        if (!success || data.length < 32) return false;
        (address creator,,,,) = abi.decode(data, (address, address, address, uint256, uint256));
        return creator != address(0);
    }
}

/// @notice ${contractName} — custom optical (override hooks: ${hooks.join(', ')}).
contract ${contractName} is BaseOptical {
${immutableDecls ? immutableDecls + '\n' : ''}
    constructor(${ctorParams}) BaseOptical(_poolRegistry, _owner) {
${ctorExtraAssigns ? ctorExtraAssigns + '\n' : ''}    }

${hookFns}

    /// @notice Bitmap of active hooks. Bit0 beforeSwap, bit1 afterSwap, bit2 beforeFeeDistribution, bit3 afterFeeDistribution.
    function getFlags() external pure override returns (uint8) {
        return ${flags}; // 0b${flags.toString(2).padStart(4, '0')}
    }
}
`

  return {
    contractName,
    flags,
    flagsBinary: '0b' + flags.toString(2).padStart(4, '0'),
    hooks,
    source,
    solcVersion: SOLC_VERSION,
    ctorArgs: [
      { name: 'poolRegistry', type: 'address', note: 'KindleLaunch PoolRegistry (CONTRACTS.poolRegistry)' },
      { name: 'owner', type: 'address', note: 'the embedded wallet (optical owner)' },
      ...extraImmutables.map((m) => ({ name: m.name, type: m.type, note: 'custom config' })),
    ],
  }
}

function renderHook(hook, body) {
  const sig = HOOK_SIGNATURES[hook]
  const mod = VALUE_GATING.has(hook) ? ' onlyPool' : ''
  const stmts = (body && String(body).trim()) || sig.defaultBody
  return `    ${sig.decl}\n        external override${mod} ${sig.rets}\n    {\n        ${stmts.split('\n').join('\n        ')}\n    }`
}

function sanitiseIdent(s) {
  const cleaned = String(s || '').replace(/[^0-9A-Za-z_]/g, '')
  if (!cleaned) return 'CustomOptical'
  return /^[0-9]/.test(cleaned) ? '_' + cleaned : cleaned
}

function sanitiseComment(s) {
  return String(s).replace(/[\r\n]+/g, ' ').slice(0, 240)
}

// A real, compilable+testable sample used by verification (task 6.3): a
// max-buy-cap optical (beforeSwap only; getFlags == 0b0001).
export function sampleMaxBuyOptical() {
  return buildCustomOptical({
    name: 'SampleMaxBuyOptical',
    notes: 'Rejects buys whose amountIn exceeds maxBuyAmount. Sells pass through.',
    hooks: ['beforeSwap'],
    immutables: [{ type: 'uint256', name: 'maxBuyAmount' }],
    bodies: {
      beforeSwap: [
        'pool; sender;',
        'if (isBuy && amountIn > maxBuyAmount) {',
        '    return (false, 0);',
        '}',
        'return (true, 0);',
      ].join('\n'),
    },
  })
}
