[package]
name = "keith-connection"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
interprocess.workspace = true
keith-framing = { path = "../framing" }
keith-protocol = { path = "../protocol" }
sha2.workspace = true
thiserror.workspace = true
tungstenite.workspace = true

[dev-dependencies]
keith-agent-types = { path = "../agent-types" }
os_pipe.workspace = true
tempfile.workspace = true

[lints]
workspace = true
