-- layerx 005_partition_transfers — convert `transfers` into a RANGE-partitioned
-- table keyed on `seq` (PHASE 8B). Done now, while the table is tiny, because
-- converting an empty/near-empty table is instant and risk-free, whereas
-- partitioning a billion-row table later is a migration nightmare. Each
-- partition holds a fixed span of 10,000,000 seqs; anchored, cold partitions can
-- later be detached / compressed / archived, and autovacuum + index maintenance
-- stay per-partition cheap. A DEFAULT partition is a safety net so an insert can
-- never fail for lack of a covering partition; layerxd's EnsureTransferPartitions
-- routine pre-creates partitions well ahead of the cursor so rows never actually
-- land in DEFAULT.
--
-- The identity column is also switched GENERATED ALWAYS -> GENERATED BY DEFAULT
-- so the hot Pay path can pre-allocate `seq` via nextval() and insert the row +
-- its Merkle leaf + signature in ONE statement (eliminating the prior
-- INSERT-then-UPDATE that produced a dead tuple per payment).
--
-- Forward-only. Runs inside the migration runner's single transaction
-- (transactional DDL): if any step fails the whole conversion rolls back cleanly
-- and the service simply fails to boot — no partial/corrupt state.
--
-- VERIFY AFTER DEPLOY (on the box):
--   \d+ transfers                         -- "Partition key: RANGE (seq)"
--   \d+ transfers_p0                       -- "Partition of: transfers FOR VALUES FROM (1) TO (10000001)"
--   SELECT count(*) FROM transfers;        -- preserved row count (the 2 test rows)
--   SELECT max(seq) FROM transfers;        -- preserved
--   INSERT smoke via a test pay -> new seq continues monotonically.

BEGIN;

-- Belt-and-suspenders: clear any artifact from a prior aborted attempt (the
-- runner is transactional, so this is normally a no-op).
DROP TABLE IF EXISTS transfers_new CASCADE;

-- New partitioned parent (temp name to avoid index/constraint name clashes with
-- the live table until the swap).
CREATE TABLE transfers_new (
    seq         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    batch_id    UUID REFERENCES batches(id),
    from_did    TEXT NOT NULL,
    to_did      TEXT NOT NULL,
    amount_usdx BIGINT NOT NULL,
    tier        TEXT NOT NULL CHECK (tier IN ('micropayment', 'material')),
    leaf_hash   TEXT,
    sig         TEXT,
    ts          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT transfers_amount_pos CHECK (amount_usdx > 0),
    PRIMARY KEY (seq)
) PARTITION BY RANGE (seq);

-- Initial partition (seqs 1..10,000,000) + a DEFAULT overflow partition.
CREATE TABLE transfers_new_p0 PARTITION OF transfers_new FOR VALUES FROM (1) TO (10000001);
CREATE TABLE transfers_new_pdefault PARTITION OF transfers_new DEFAULT;

-- Copy the existing rows, preserving seq (BY DEFAULT identity allows explicit seq).
INSERT INTO transfers_new (seq, batch_id, from_did, to_did, amount_usdx, tier, leaf_hash, sig, ts)
SELECT seq, batch_id, from_did, to_did, amount_usdx, tier, leaf_hash, sig, ts
FROM transfers;

-- Continue the identity sequence after the highest preserved seq (or at 1 when
-- empty). setval(..., n, false) makes the NEXT nextval() return exactly n.
DO $$
DECLARE mx BIGINT;
BEGIN
    SELECT COALESCE(MAX(seq), 0) FROM transfers_new INTO mx;
    PERFORM setval(pg_get_serial_sequence('transfers_new', 'seq'), mx + 1, false);
END $$;

-- Swap: drop the old table (frees the canonical names), promote the new one.
DROP TABLE transfers;
ALTER TABLE transfers_new RENAME TO transfers;
ALTER TABLE transfers_new_p0 RENAME TO transfers_p0;
ALTER TABLE transfers_new_pdefault RENAME TO transfers_pdefault;

-- Recreate the canonical index set on the partitioned parent (propagates to all
-- partitions). No transfers_seq_desc_idx: the PK btree serves ORDER BY seq DESC
-- via a backward scan.
CREATE INDEX transfers_from_idx      ON transfers (from_did, seq DESC);
CREATE INDEX transfers_to_idx        ON transfers (to_did, seq DESC);
CREATE INDEX transfers_unsettled_idx ON transfers (seq) WHERE batch_id IS NULL;
CREATE INDEX transfers_batch_seq_idx ON transfers (batch_id, seq);

COMMIT;
