// Copyright © 2026 Sidiora Labs. All rights reserved. SPDX-License-Identifier: LicenseRef-Centra-ai-Protocol
// Contact · license@Paxeer.app · legal@Paxeer.app

// Package codegen emits the TypeScript mirror of the Construct Go schema
// (schema + schema/primitives) into the client. The Go structs are the single
// source of truth (§1 decision 3: the daemon emits, the client only consumes);
// this package walks them by reflection and produces a deterministic,
// byte-stable .ts file with a --check mode for CI drift detection.
package codegen

import (
	"fmt"
	"reflect"
	"strings"

	"matrix/construct/schema"
	"matrix/construct/schema/primitives"
)

// DefaultOutPath is where the generated TS lands, relative to the construct
// module root (the client repo is the sibling directory).
const DefaultOutPath = "../client/lib/construct/types.gen.ts"

// enumDef is a Go string-enum type rendered as a TS string-literal union.
type enumDef struct {
	name   string
	values []string
}

// enums lists every Construct enum, in deterministic emit order. Values are
// read from the Go consts so a rename is a compile error here (authoritative,
// never drifts from the schema).
func enums() []enumDef {
	return []enumDef{
		{"Kind", kindStrings(schema.Kinds)},
		{"Stakes", stakesStrings(schema.StakesValues)},
		{"Temporality", temporalityStrings(schema.TemporalityValues)},
		{"NarrationRole", []string{
			string(primitives.NarrationThinking),
			string(primitives.NarrationIntent),
			string(primitives.NarrationAnswer),
		}},
		{"Trend", []string{
			string(primitives.TrendUp),
			string(primitives.TrendDown),
			string(primitives.TrendFlat),
		}},
		{"MetricDisplay", metricDisplayStrings(primitives.MetricDisplayValues)},
		{"AffordanceKind", []string{
			string(primitives.AffordanceLink),
			string(primitives.AffordanceAsk),
			string(primitives.AffordanceCopy),
		}},
		{"Shape", shapeStrings(primitives.ShapeValues)},
		{"StepStatus", stepStatusStrings(primitives.StepStatusValues)},
		{"MediaKind", []string{
			string(primitives.MediaImage),
			string(primitives.MediaVideo),
			string(primitives.MediaAudio),
			string(primitives.MediaPage),
			string(primitives.MediaChart),
		}},
		{"ChartKind", chartKindStrings(primitives.ChartKindValues)},
		{"AskKind", askKindStrings(primitives.AskKindValues)},
	}
}

// structs lists every Construct struct, in dependency-first emit order (a type
// is emitted before the types that reference it). Surface is last.
func structs() []reflect.Type {
	return []reflect.Type{
		reflect.TypeOf(schema.Cost{}),
		reflect.TypeOf(schema.Attributes{}),
		reflect.TypeOf(primitives.Narration{}),
		reflect.TypeOf(primitives.MetricThreshold{}),
		reflect.TypeOf(primitives.Metric{}),
		reflect.TypeOf(primitives.EntityField{}),
		reflect.TypeOf(primitives.Affordance{}),
		reflect.TypeOf(primitives.Entity{}),
		reflect.TypeOf(primitives.StructureNode{}),
		reflect.TypeOf(primitives.Structure{}),
		reflect.TypeOf(primitives.StreamChunk{}),
		reflect.TypeOf(primitives.Stream{}),
		reflect.TypeOf(primitives.TimelineStep{}),
		reflect.TypeOf(primitives.Timeline{}),
		reflect.TypeOf(primitives.CanvasMedia{}),
		reflect.TypeOf(primitives.ChartSeries{}),
		reflect.TypeOf(primitives.ChartPoint{}),
		reflect.TypeOf(primitives.Chart{}),
		reflect.TypeOf(primitives.CanvasRegion{}),
		reflect.TypeOf(primitives.Canvas{}),
		reflect.TypeOf(primitives.AskOption{}),
		reflect.TypeOf(primitives.AskResponse{}),
		reflect.TypeOf(primitives.Ask{}),
		reflect.TypeOf(schema.Surface{}),
		// Rehydration wire types (GET /construct/state). Frame is emitted
		// before StateResponse, which references it (dependency-first).
		reflect.TypeOf(schema.Frame{}),
		reflect.TypeOf(schema.StateResponse{}),
	}
}

const header = `/* eslint-disable */
// Code generated by ` + "`construct codegen`" + `; DO NOT EDIT.
//
// TypeScript mirror of the Construct wire schema. The Go structs in
// construct/schema (+ schema/primitives) are the single source of truth; this
// file is regenerated by ` + "`go run ./cmd/construct codegen`" + ` and checked for
// drift by ` + "`go run ./cmd/construct codegen --check`" + `. Edit the Go schema, not
// this file. See construct/construct.frozen.kvx for the frozen vocabulary.
`

// Generate produces the full TypeScript file as a deterministic byte-stable
// string.
func Generate() (string, error) {
	enumNames := map[string]bool{}
	for _, e := range enums() {
		enumNames[e.name] = true
	}
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("\n")

	for _, e := range enums() {
		b.WriteString(emitEnum(e))
		b.WriteString("\n")
	}
	for _, t := range structs() {
		s, err := emitStruct(t, enumNames)
		if err != nil {
			return "", err
		}
		b.WriteString(s)
		b.WriteString("\n")
	}
	return b.String(), nil
}

// emitEnum renders one string-literal union, one value per line for stable,
// readable output.
func emitEnum(e enumDef) string {
	var b strings.Builder
	fmt.Fprintf(&b, "export type %s =\n", e.name)
	for _, v := range e.values {
		fmt.Fprintf(&b, "  | '%s'\n", v)
	}
	return b.String()
}

// emitStruct renders one Go struct as a TS interface.
func emitStruct(t reflect.Type, enumNames map[string]bool) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "export interface %s {\n", t.Name())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		name, optional, skip := jsonField(f)
		if skip {
			continue
		}
		ts, err := tsType(f.Type, enumNames)
		if err != nil {
			return "", fmt.Errorf("%s.%s: %w", t.Name(), f.Name, err)
		}
		q := ""
		if optional {
			q = "?"
		}
		fmt.Fprintf(&b, "  %s%s: %s\n", name, q, ts)
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// jsonField extracts the JSON name, optionality, and skip flag from a struct
// field. A field is optional when it has `omitempty` or is a pointer.
func jsonField(f reflect.StructField) (name string, optional, skip bool) {
	tag := f.Tag.Get("json")
	if tag == "-" {
		return "", false, true
	}
	parts := strings.Split(tag, ",")
	name = parts[0]
	if name == "" {
		name = f.Name
	}
	for _, p := range parts[1:] {
		if p == "omitempty" {
			optional = true
		}
	}
	if f.Type.Kind() == reflect.Ptr {
		optional = true
	}
	return name, optional, false
}

// tsType maps a Go type to its TypeScript representation.
func tsType(t reflect.Type, enumNames map[string]bool) (string, error) {
	// Named enum types (e.g. Kind, Stakes) render as their union type name.
	if t.Name() != "" && enumNames[t.Name()] {
		return t.Name(), nil
	}
	switch t.Kind() {
	case reflect.Ptr:
		return tsType(t.Elem(), enumNames)
	case reflect.String:
		return "string", nil
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.Slice:
		elem, err := tsType(t.Elem(), enumNames)
		if err != nil {
			return "", err
		}
		return elem + "[]", nil
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			return "", fmt.Errorf("unsupported map key %s", t.Key().Kind())
		}
		elem, err := tsType(t.Elem(), enumNames)
		if err != nil {
			return "", err
		}
		return "Record<string, " + elem + ">", nil
	case reflect.Interface:
		// An empty interface (interface{}/any) is an opaque payload (e.g. a
		// Frame's Fields); the safe TS mirror is `unknown`.
		if t.NumMethod() == 0 {
			return "unknown", nil
		}
		return "", fmt.Errorf("unsupported non-empty interface %s", t.Name())
	case reflect.Struct:
		if t.Name() == "" {
			return "", fmt.Errorf("anonymous struct unsupported")
		}
		return t.Name(), nil
	default:
		return "", fmt.Errorf("unsupported kind %s", t.Kind())
	}
}

// --- typed-slice -> []string helpers (keep the enum value lists authoritative
// against the Go consts without an unsafe generic cast). ---

func kindStrings(in []schema.Kind) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}

func stakesStrings(in []schema.Stakes) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}

func temporalityStrings(in []schema.Temporality) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}

func shapeStrings(in []primitives.Shape) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}

func stepStatusStrings(in []primitives.StepStatus) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}

func askKindStrings(in []primitives.AskKind) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}

func metricDisplayStrings(in []primitives.MetricDisplay) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}

func chartKindStrings(in []primitives.ChartKind) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}
