// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type ApprovalDecision byte

const (
	ApprovalDecisionapproved ApprovalDecision = 0
	ApprovalDecisiondenied   ApprovalDecision = 1
)

var EnumNamesApprovalDecision = map[ApprovalDecision]string{
	ApprovalDecisionapproved: "approved",
	ApprovalDecisiondenied:   "denied",
}

var EnumValuesApprovalDecision = map[string]ApprovalDecision{
	"approved": ApprovalDecisionapproved,
	"denied":   ApprovalDecisiondenied,
}

func (v ApprovalDecision) String() string {
	if s, ok := EnumNamesApprovalDecision[v]; ok {
		return s
	}
	return "ApprovalDecision(" + strconv.FormatInt(int64(v), 10) + ")"
}
