// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type AttestationDisposition byte

const (
	AttestationDispositionused    AttestationDisposition = 0
	AttestationDispositionignored AttestationDisposition = 1
)

var EnumNamesAttestationDisposition = map[AttestationDisposition]string{
	AttestationDispositionused:    "used",
	AttestationDispositionignored: "ignored",
}

var EnumValuesAttestationDisposition = map[string]AttestationDisposition{
	"used":    AttestationDispositionused,
	"ignored": AttestationDispositionignored,
}

func (v AttestationDisposition) String() string {
	if s, ok := EnumNamesAttestationDisposition[v]; ok {
		return s
	}
	return "AttestationDisposition(" + strconv.FormatInt(int64(v), 10) + ")"
}
