// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import "strconv"

type EventPayload byte

const (
	EventPayloadNONE          EventPayload = 0
	EventPayloadUserMsg       EventPayload = 1
	EventPayloadDeliveredMsg  EventPayload = 2
	EventPayloadToolCall      EventPayload = 3
	EventPayloadToolResult    EventPayload = 4
	EventPayloadReasoning     EventPayload = 5
	EventPayloadProviderFrame EventPayload = 6
	EventPayloadMediaRef      EventPayload = 7
	EventPayloadEffect        EventPayload = 8
	EventPayloadApproval      EventPayload = 9
	EventPayloadOutcome       EventPayload = 10
	EventPayloadCheckpoint    EventPayload = 11
	EventPayloadSupervisor    EventPayload = 12
	EventPayloadRecovery      EventPayload = 13
	EventPayloadIntentSet     EventPayload = 14
	EventPayloadLoopOpened    EventPayload = 15
	EventPayloadLoopClosed    EventPayload = 16
	EventPayloadAssertion     EventPayload = 17
	EventPayloadConsolidation EventPayload = 18
	EventPayloadEmbedding     EventPayload = 19
	EventPayloadRetract       EventPayload = 20
	EventPayloadAttestation   EventPayload = 21
)

var EnumNamesEventPayload = map[EventPayload]string{
	EventPayloadNONE:          "NONE",
	EventPayloadUserMsg:       "UserMsg",
	EventPayloadDeliveredMsg:  "DeliveredMsg",
	EventPayloadToolCall:      "ToolCall",
	EventPayloadToolResult:    "ToolResult",
	EventPayloadReasoning:     "Reasoning",
	EventPayloadProviderFrame: "ProviderFrame",
	EventPayloadMediaRef:      "MediaRef",
	EventPayloadEffect:        "Effect",
	EventPayloadApproval:      "Approval",
	EventPayloadOutcome:       "Outcome",
	EventPayloadCheckpoint:    "Checkpoint",
	EventPayloadSupervisor:    "Supervisor",
	EventPayloadRecovery:      "Recovery",
	EventPayloadIntentSet:     "IntentSet",
	EventPayloadLoopOpened:    "LoopOpened",
	EventPayloadLoopClosed:    "LoopClosed",
	EventPayloadAssertion:     "Assertion",
	EventPayloadConsolidation: "Consolidation",
	EventPayloadEmbedding:     "Embedding",
	EventPayloadRetract:       "Retract",
	EventPayloadAttestation:   "Attestation",
}

var EnumValuesEventPayload = map[string]EventPayload{
	"NONE":          EventPayloadNONE,
	"UserMsg":       EventPayloadUserMsg,
	"DeliveredMsg":  EventPayloadDeliveredMsg,
	"ToolCall":      EventPayloadToolCall,
	"ToolResult":    EventPayloadToolResult,
	"Reasoning":     EventPayloadReasoning,
	"ProviderFrame": EventPayloadProviderFrame,
	"MediaRef":      EventPayloadMediaRef,
	"Effect":        EventPayloadEffect,
	"Approval":      EventPayloadApproval,
	"Outcome":       EventPayloadOutcome,
	"Checkpoint":    EventPayloadCheckpoint,
	"Supervisor":    EventPayloadSupervisor,
	"Recovery":      EventPayloadRecovery,
	"IntentSet":     EventPayloadIntentSet,
	"LoopOpened":    EventPayloadLoopOpened,
	"LoopClosed":    EventPayloadLoopClosed,
	"Assertion":     EventPayloadAssertion,
	"Consolidation": EventPayloadConsolidation,
	"Embedding":     EventPayloadEmbedding,
	"Retract":       EventPayloadRetract,
	"Attestation":   EventPayloadAttestation,
}

func (v EventPayload) String() string {
	if s, ok := EnumNamesEventPayload[v]; ok {
		return s
	}
	return "EventPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
