// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "matrix/cortexclient/internal/flatbuffers"
)

type LoopClosed struct {
	_tab flatbuffers.Table
}

func GetRootAsLoopClosed(buf []byte, offset flatbuffers.UOffsetT) *LoopClosed {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LoopClosed{}
	x.Init(buf, n+offset)
	return x
}

func FinishLoopClosedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLoopClosed(buf []byte, offset flatbuffers.UOffsetT) *LoopClosed {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LoopClosed{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLoopClosedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LoopClosed) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LoopClosed) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LoopClosed) LoopId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *LoopClosed) LoopIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *LoopClosed) LoopIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LoopClosed) MutateLoopId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *LoopClosed) Reason() LoopCloseReason {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return LoopCloseReason(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *LoopClosed) MutateReason(n LoopCloseReason) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *LoopClosed) Cause(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *LoopClosed) CauseLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *LoopClosed) CauseBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LoopClosed) MutateCause(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func LoopClosedStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func LoopClosedAddLoopId(builder *flatbuffers.Builder, loopId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(loopId), 0)
}
func LoopClosedStartLoopIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func LoopClosedAddReason(builder *flatbuffers.Builder, reason LoopCloseReason) {
	builder.PrependByteSlot(1, byte(reason), 0)
}
func LoopClosedAddCause(builder *flatbuffers.Builder, cause flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(cause), 0)
}
func LoopClosedStartCauseVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func LoopClosedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
