package controlplane

import (
	"fmt"
	"io"
	"strconv"
)

// GenerateTypeScript writes the deterministic client wire contract and runtime
// validators. It is deliberately generated from the closed Go catalogs.
func GenerateTypeScript(writer io.Writer) error {
	if writer == nil {
		return fmt.Errorf("controlplane: TypeScript writer is required")
	}
	operations := Operations()
	events := EventTypes()
	if _, err := fmt.Fprintln(writer, "// Code generated by cmd/controlplane-gen; DO NOT EDIT."); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(
		writer,
		"export const PROTOCOL_VERSION = %s as const\n\n",
		strconv.Quote(ProtocolVersion),
	); err != nil {
		return err
	}
	if err := writeStringArray(writer, "OPERATIONS", operations); err != nil {
		return err
	}
	if _, err := fmt.Fprint(writer, "export type Operation = (typeof OPERATIONS)[number]\n\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(writer, "export const OPERATION_KINDS = {"); err != nil {
		return err
	}
	for _, operation := range operations {
		kind, _ := operation.Kind()
		if _, err := fmt.Fprintf(
			writer, "  %s: %s,\n", strconv.Quote(string(operation)), strconv.Quote(string(kind)),
		); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprint(
		writer,
		"} as const satisfies Record<Operation, RequestKind>\n\n",
	); err != nil {
		return err
	}
	if err := writeStringArray(writer, "EVENT_TYPES", events); err != nil {
		return err
	}
	if _, err := fmt.Fprint(writer, "export type EventType = (typeof EVENT_TYPES)[number]\n\n"); err != nil {
		return err
	}
	_, err := io.WriteString(writer, typeScriptContract)
	return err
}

func writeStringArray[T ~string](writer io.Writer, name string, values []T) error {
	if _, err := fmt.Fprintf(writer, "export const %s = [\n", name); err != nil {
		return err
	}
	for _, value := range values {
		if _, err := fmt.Fprintf(writer, "  %s,\n", strconv.Quote(string(value))); err != nil {
			return err
		}
	}
	_, err := fmt.Fprint(writer, "] as const\n\n")
	return err
}

const typeScriptContract = `export type UUID = string
export type RequestKind = 'query' | 'command'

export const WORKSPACE_HOST_VERSION = 'ion.workspace-host.v1' as const
export type WorkspaceHostKind = 'direct_local' | 'container' | 'remote_worker'
export type WorkspaceCapabilityDomain =
  | 'project' | 'file' | 'process' | 'git' | 'preview'
  | 'artifact' | 'integration' | 'system'
export type WorkspacePolicyClassification = 'GREEN' | 'YELLOW' | 'RED'
export type WorkspaceHostOperation =
  | 'workspace.provision' | 'workspace.readiness' | 'workspace.pause'
  | 'workspace.resume' | 'workspace.stop' | 'workspace.archive' | 'workspace.destroy'

export interface WorkspaceResourceLimits {
  cpu_millis: number
  memory_bytes: number
  processes: number
  disk_bytes: number
  wall_time_seconds: number
  output_bytes: number
}

export interface WorkspaceNetworkPolicy {
  mode: string
  allowed_hosts?: string[]
  exposed_ports?: number[]
}

export interface WorkspaceCapability {
  domain: WorkspaceCapabilityDomain
  supported: boolean
  features: string[]
  reason?: string
}

export interface WorkspaceHostCapabilities {
  version: typeof WORKSPACE_HOST_VERSION
  kind: WorkspaceHostKind
  available: boolean
  reason?: string
  domains: WorkspaceCapability[]
  limits: WorkspaceResourceLimits
  network: WorkspaceNetworkPolicy
  non_root: boolean
  root_confined: boolean
  authority_disclosure?: string
}

export interface WorkspaceSecretGrant {
  id: UUID
  reference: string
  expires_at: string
  grant_token: string
}

export interface WorkspaceOperationEnvelope {
  version: typeof WORKSPACE_HOST_VERSION
  operation: WorkspaceHostOperation
  actor_id: UUID
  project_id: UUID
  workspace_revision: number
  request_id: UUID
  idempotency_key: string
  policy_classification: WorkspacePolicyClassification
  deadline: string
  correlation_id: UUID
  secret_grants?: WorkspaceSecretGrant[]
  payload?: unknown
}

export interface ProjectRecord {
  id: UUID
  name: string
  root: string
  source: 'template' | 'archive' | 'directory' | 'repository'
  source_reference?: string
  default_branch?: string
  stack_signals: string[]
  trust: 'untrusted' | 'reviewed' | 'trusted'
  workspace_revision: number
  host: WorkspaceHostKind
  host_reference?: string
  latest_archive?: string
  managed: boolean
  lifecycle: 'provisioning' | 'ready' | 'paused' | 'stopped' | 'archived' | 'destroy_pending' | 'failed'
  last_error?: string
  created_at: string
  updated_at: string
}

export const PROJECT_VERIFICATION_VERSION = 'ion.project-verification.v1' as const

export interface ProjectVerificationCriterion {
  id: string
  description: string
  kinds: string[]
}

export interface ProjectVerificationGate {
  id: string
  kind: string
  argv?: string[]
  working_directory?: string
  environment: string[]
  timeout_seconds: number
  required: boolean
  criteria: string[]
  evidence_kinds: string[]
  evidence_paths?: string[]
  available: boolean
  unavailable_reason?: string
}

export interface ProjectVerificationManifest {
  version: typeof PROJECT_VERIFICATION_VERSION
  id: UUID
  actor_id: UUID
  project_id: UUID
  workspace_revision: number
  inducing_patch_id?: UUID
  revision: number
  criteria: ProjectVerificationCriterion[]
  gates: ProjectVerificationGate[]
  created_at: string
}

export interface ProjectVerificationEvidence {
  kind: string
  reference: string
  sha256: string
  size_bytes: number
}

export interface ProjectVerificationGateResult {
  gate_id: string
  kind: string
  status: string
  terminal_id?: UUID
  exit_code?: number
  duration_millis: number
  logs?: string
  logs_truncated: boolean
  failure_signature?: string
  criteria_covered: string[]
  evidence: ProjectVerificationEvidence[]
  unavailable_reason?: string
  waiver_id?: UUID
}

export interface ProjectVerificationRun {
  version: typeof PROJECT_VERIFICATION_VERSION
  id: UUID
  actor_id: UUID
  project_id: UUID
  manifest_id: UUID
  manifest_revision: number
  workspace_revision: number
  inducing_patch_id?: UUID
  mode: string
  status: string
  results: ProjectVerificationGateResult[]
  criteria_covered: string[]
  uncovered_criteria: string[]
  repair: {
    state: string
    reason: string
    attempts: number
    max_attempts: number
    failure_signatures: string[]
  }
  started_at: string
  finished_at: string
}

export interface ProjectVerificationWaiver {
  id: UUID
  actor_id: UUID
  project_id: UUID
  manifest_id: UUID
  gate_ids: string[]
  criteria: string[]
  reason: string
  risk: string
  expires_at: string
  created_at: string
  revoked_at?: string
}

export const PROJECT_INTELLIGENCE_VERSION = 'ion.project-intelligence.v1' as const
export type ProjectContentClass =
  | 'source' | 'generated' | 'vendor' | 'binary' | 'oversized'
  | 'protected' | 'ignored' | 'unreadable'
export type ProjectSearchKind =
  | 'lexical' | 'regex' | 'filename' | 'symbol'
  | 'reference' | 'dependency' | 'diagnostic' | 'semantic'

export interface ProjectCitation {
  project_id: UUID
  workspace_revision: number
  index_revision: number
  path: string
  sha256: string
  line_start?: number
  line_end?: number
  symbol?: string
  source: string
}

export interface ProjectFileRecord {
  path: string
  sha256?: string
  size: number
  modified_unix_ns?: number
  class: ProjectContentClass
  reason?: string
  language?: string
  frameworks?: string[]
  secret_findings?: Array<{ path: string; line: number; kind: string }>
}

export interface ProjectIndex {
  version: typeof PROJECT_INTELLIGENCE_VERSION
  actor_id: UUID
  project_id: UUID
  workspace_revision: number
  index_revision: number
  root_digest: string
  denied_paths: string[]
  files: ProjectFileRecord[]
  languages: string[]
  frameworks: string[]
  entry_points: Array<{ path: string; line?: number; kind: string; command?: string }>
  ownership: Array<{ pattern: string; owners: string[]; source: string; line: number }>
  configuration: Array<{ path: string; kind: string; scope: string; sha256: string; owners?: string[] }>
  generated_ownership: Array<{ path: string; generator: string; owners?: string[] }>
  instructions: Array<{
    path: string
    scope: string
    sha256: string
    precedence: number
    content: string
    truncated: boolean
    repository_data: boolean
    cannot_override_safety: boolean
  }>
  omissions: Array<{ path?: string; class: string; reason: string; count?: number }>
  truncated: boolean
  updated_at: string
}

export interface ProjectSearchResponse {
  project_id: UUID
  workspace_revision: number
  index_revision: number
  matches: Array<{
    kind: ProjectSearchKind
    score: number
    path: string
    line_start?: number
    line_end?: number
    symbol?: string
    snippet: string
    citation: ProjectCitation
  }>
  omissions: Array<{ path?: string; class: string; reason: string; count?: number }>
  truncated: boolean
  result_bytes: number
}

export interface StudioContextPack {
  version: typeof PROJECT_INTELLIGENCE_VERSION
  project_id: UUID
  workspace_revision: number
  index_revision: number
  task: string
  items: Array<{
    kind: string
    title: string
    content: string
    citation: ProjectCitation
    verified: boolean
    bytes: number
    priority: number
  }>
  instructions: {
    target_path?: string
    precedence: string
    immutable_safety_wins: boolean
    user_authority_wins: boolean
    instructions: ProjectIndex['instructions']
  }
  omissions: Array<{ path?: string; class: string; reason: string; count?: number }>
  truncated: boolean
  expanded_for_mismatch: boolean
  bytes: number
  created_at: string
}

export const PATCH_SET_VERSION = 'ion.patch-set.v1' as const
export interface ProjectPatchSet {
  version: typeof PATCH_SET_VERSION
  id: UUID
  project_id: UUID
  baseline_revision: number
  criteria: string[]
  validation_plan: string[]
  members: Array<{
    operation: 'write' | 'exact_replace' | 'delete' | 'rename' | 'copy' | 'mkdir' | 'archive' | 'json_set'
    path: string
    destination?: string
    expected_sha256: string
    content?: string
    content_base64?: string
    media_type?: string
    archive_paths?: string[]
    archive_baseline_sha256?: string
    json_pointer?: string
    json_value?: unknown
    old_text?: string
    new_text?: string
    replace_all?: boolean
    generated?: boolean
  }>
}

export interface ProjectPatchRollbackRequest {
  project_id: UUID
  patch_set_id: UUID
  workspace_revision: number
}

export interface ProjectTerminalState {
  version: 'ion.project-terminal.v1'
  id: UUID
  actor_id: UUID
  project_id: UUID
  workspace_revision: number
  mode: 'one_shot' | 'pty'
  argv: string[]
  working_directory: string
  pid?: number
  status: string
  exit_code?: number
  started_at: string
  finished_at?: string
  output_cursor: number
  dropped_bytes: number
  truncated: boolean
  timed_out: boolean
}

export interface ProjectDependencyPlan {
  project_id: UUID
  workspace_revision: number
  working_directory: string
  manager: string
  lockfile: string
  lockfile_sha256: string
  argv: string[]
  packages: string[]
  lifecycle_scripts: string[]
  risks: string[]
  classification: WorkspacePolicyClassification
  requires_approval: boolean
  scripts_will_execute: boolean
}

export type ProjectEnvironmentScope =
  | 'development' | 'test' | 'preview' | 'staging' | 'production'
export type ProjectResourceKind =
  | 'database' | 'object_storage' | 'authentication' | 'email' | 'queue'
  | 'scheduled_job' | 'analytics' | 'payment' | 'external_api'

export interface ProjectDeliveryEvidence {
  kind: string
  reference: string
  sha256?: string
}

export interface ProjectEnvironmentSchema {
  version: 'ion.project-delivery.v1'
  revision: number
  actor_id: UUID
  project_id: UUID
  environment: ProjectEnvironmentScope
  variables: Array<{
    name: string
    kind: 'config_reference' | 'secret_reference'
    reference: string
    required: boolean
    description?: string
  }>
  schema_sha256: string
  created_at: string
}

export interface ProjectResourceReceipt {
  version: 'ion.project-delivery.v1'
  id: UUID
  plan_id: UUID
  project_id: UUID
  resource_id: UUID
  provider: string
  environment: ProjectEnvironmentScope
  state: string
  external_id?: string
  endpoint?: string
  classification: WorkspacePolicyClassification
  actual_cost_cents: number
  evidence: ProjectDeliveryEvidence[]
  created_at: string
  reconciled_at: string
}

export interface ProjectMigrationReceipt {
  version: 'ion.project-delivery.v1'
  id: UUID
  plan_id: UUID
  project_id: UUID
  environment: ProjectEnvironmentScope
  state: string
  backup_path: string
  backup_sha256: string
  schema_after: string[]
  rollback_evidence: ProjectDeliveryEvidence[]
  applied_at: string
  rolled_back_at?: string
}

export interface ProjectDeploymentReceipt {
  version: 'ion.project-delivery.v1'
  id: UUID
  plan_id: UUID
  project_id: UUID
  environment: ProjectEnvironmentScope
  provider: string
  release_version: string
  artifact_sha256: string
  state: string
  url?: string
  health: string
  logs?: string
  rollback_handle?: string
  previous_receipt?: UUID
  classification: WorkspacePolicyClassification
  actual_cost_cents: number
  evidence: ProjectDeliveryEvidence[]
  created_at: string
  reconciled_at: string
  rolled_back_at?: string
}

export interface ProjectReleaseReadiness {
  version: 'ion.project-delivery.v1'
  project_id: UUID
  release_version: string
  notes: string[]
  changelog: string[]
  domain?: string
  dns_state: string
  provider_checks: ProjectDeliveryEvidence[]
  portable_export?: string
  ready: boolean
  unmet: string[]
  created_at: string
}

export interface ProjectDeliverySnapshot {
  version: 'ion.project-delivery.v1'
  catalog: Array<{ kind: ProjectResourceKind; capabilities: string[]; data_risks: string[] }>
  resources: ProjectResourceReceipt[]
  environments: ProjectEnvironmentSchema[]
  migrations: ProjectMigrationReceipt[]
  deployments: ProjectDeploymentReceipt[]
  release?: ProjectReleaseReadiness
}

export interface ProjectCIPatchPlan {
  version: 'ion.project-delivery.v1'
  project_id: UUID
  workspace_revision: number
  path: string
  expected_sha256: string
  content: string
  classification: WorkspacePolicyClassification
  review_required: boolean
}

export interface ProjectGitPreview {
  version: 'ion.project-git.v1'
  id: UUID
  actor_id: UUID
  project_id: UUID
  repository_root: string
  path: string
  revision: string
  original_head: string
  original_branch?: string
  state: string
  created_at: string
  closed_at?: string
}

export interface ProjectGitMutationReceipt {
  version: 'ion.project-git.v1'
  project_id: UUID
  operation: string
  before_head: string
  after_head: string
  workspace_revision: number
  classification: WorkspacePolicyClassification
  applied_at: string
}

export type StudioProposalStatus = 'proposed' | 'accepted' | 'rejected' | 'superseded'
export type StudioCorrelationKind =
  | 'task' | 'patch' | 'tool' | 'review' | 'verification' | 'artifact'

export interface StudioAssumption {
  id: string
  statement: string
  reversible: boolean
  material: boolean
  consequence?: string
  decision_needed?: string
  resolution?: string
  resolved_at?: string
}

export interface StudioCriterion {
  id: string
  description: string
}

export interface StudioPlannedTask {
  id: string
  title: string
  criteria: string[]
  depends_on?: string[]
}

export interface StudioSpecDelta {
  user_visible_behavior: string[]
  non_goals: string[]
  constraints: string[]
  risks: string[]
  acceptance_criteria: StudioCriterion[]
  security_boundaries: string[]
  data_boundaries: string[]
  migration: string[]
  rollback: string[]
  verification_commands: string[]
  tasks: StudioPlannedTask[]
}

export interface StudioProposal {
  id: UUID
  version: number
  status: StudioProposalStatus
  rationale: string
  dependency_impact: string[]
  delta: StudioSpecDelta
  supersedes?: UUID
  created_at: string
  decided_at?: string
  decision_reason?: string
  applied_at?: string
  spec_sha256?: string
  generated_tasks_sha256?: string
}

export interface StudioIntent {
  id: UUID
  version: 'ion.software-intent.v1'
  project_id: UUID
  outcome_contract_id: UUID
  baseline_workspace_revision: number
  goal: string
  mapped_requirements: string[]
  assumptions: StudioAssumption[]
  proposals: StudioProposal[]
  active_proposal_id?: UUID
  correlations: Array<{
    id: UUID
    kind: StudioCorrelationKind
    reference: string
    criteria: string[]
    description: string
    workspace_revision: number
    spec_sha256: string
    generated_tasks_sha256: string
    implementation_sha256: string
    created_at: string
  }>
  created_at: string
  updated_at: string
}

export interface Scope {
  actor_id: UUID
  session_id?: UUID
  profile?: string
  channel?: string
}

export interface RequestEnvelope {
  protocol_version: typeof PROTOCOL_VERSION
  request_id: UUID
  kind: RequestKind
  operation: Operation
  scope: Scope
  idempotency_key?: string
  expected_revision?: number
  payload: unknown
}

export type ErrorCode =
  | 'invalid'
  | 'unauthorized'
  | 'forbidden'
  | 'not_found'
  | 'conflict'
  | 'rate_limited'
  | 'unavailable'
  | 'internal'

export interface ProtocolError {
  code: ErrorCode
  message: string
  retryable: boolean
}

export interface ResponseEnvelope<T = unknown> {
  protocol_version: typeof PROTOCOL_VERSION
  request_id: UUID
  revision: number
  result?: T
  error?: ProtocolError
}

export interface Correlation {
  actor_id: UUID
  session_id?: UUID
  turn_id?: UUID
  task_id?: UUID
  tool_id?: UUID
}

export const COMPUTER_EVENT_VERSION = 'ion.computer-event.v1' as const
export type ComputerPhase =
  | 'requested' | 'awaiting_approval' | 'started' | 'progress'
  | 'completed' | 'failed' | 'denied' | 'interrupted' | 'outcome_unknown'
export type ComputerTerminalStatus =
  | 'completed' | 'failed' | 'denied' | 'interrupted' | 'outcome_unknown'
export type ComputerRiskClass = 'GREEN' | 'YELLOW' | 'RED'

export interface ComputerScope {
  actor_id: UUID
  session_id?: UUID
  turn_id?: UUID
  task_id?: UUID
  outcome_id?: UUID
  agent_id: string
}

export interface ComputerSourceReference {
  kind: string
  id: string
}

export interface ComputerResultSummary {
  available: boolean
  bytes: number
  error_code?: string
  error?: string
}

export const DISPLAY_MODEL_VERSION = 'ion.display-model.v1' as const
export type DisplayKind =
  | 'search' | 'reader' | 'navigation' | 'repository' | 'code' | 'terminal'
  | 'diff' | 'process' | 'table' | 'chart' | 'document' | 'artifact' | 'task'
  | 'agent' | 'approval' | 'error' | 'degraded'
export type DisplayTruth =
  | 'observed' | 'generated' | 'summarized' | 'inferred' | 'unavailable'
export type DisplayFormat =
  | 'text' | 'url' | 'path' | 'integer' | 'number' | 'boolean' | 'timestamp'
  | 'status' | 'code' | 'terminal' | 'diff'
export type DisplayBlockKind =
  | 'text' | 'list' | 'code' | 'terminal' | 'diff' | 'table' | 'chart'
  | 'document' | 'empty'
export type DisplayCompatibility =
  | 'current' | 'migrated' | 'unsupported' | 'invalid'

export interface DisplayDatum {
  value: string
  truth: DisplayTruth
  format: DisplayFormat
  sources: number[]
}

export interface DisplayField {
  label: string
  value: DisplayDatum
}

export interface DisplayItem {
  fields: DisplayField[]
}

export interface DisplayBlock {
  kind: DisplayBlockKind
  label?: string
  language?: string
  content?: DisplayDatum
  fields?: DisplayField[]
  items?: DisplayItem[]
  columns?: string[]
  rows?: DisplayDatum[][]
}

export interface DisplayModel {
  protocol_version: typeof DISPLAY_MODEL_VERSION
  kind: DisplayKind
  title: DisplayDatum
  fields?: DisplayField[]
  blocks?: DisplayBlock[]
}

export interface ComputerEventPayload {
  protocol_version: typeof COMPUTER_EVENT_VERSION
  tool_event_id: UUID
  provider_tool_call_id: string
  tool: string
  operation: string
  scope: ComputerScope
  risk_class: ComputerRiskClass
  phase: ComputerPhase
  timestamp: string
  display_kind: string
  source_references: ComputerSourceReference[]
  terminal_status?: ComputerTerminalStatus
  progress?: unknown
  result?: ComputerResultSummary
  display_model?: unknown
}

export interface EventEnvelope<T = unknown> {
  sequence: number
  event_id: UUID
  type: EventType
  occurred_at: string
  correlation: Correlation
  payload: T
}

export interface ReplayEnvelope {
  after_sequence: number
  earliest_sequence: number
  latest_sequence: number
  head_sequence: number
  gap: boolean
  events: EventEnvelope[]
}

export interface GapMarker {
  requested_after: number
  available_from: number
  latest: number
}

export interface RecoveryEnvelope {
  replay: ReplayEnvelope
  gap_marker?: GapMarker
  snapshot?: unknown
}

export interface BrowserStreamFrame {
  type: 'recovery' | 'event' | 'error'
  recovery?: RecoveryEnvelope
  event?: EventEnvelope
  error?: ProtocolError
}

export type LocalClientFrame =
  | { type: 'rpc'; request: RequestEnvelope }
  | { type: 'subscribe'; after_sequence: number }
  | { type: 'ack'; client_id: string; sequence: number }

export interface LocalServerFrame {
  type: 'ready' | 'rpc' | 'recovery' | 'event' | 'ack' | 'error'
  protocol_version: typeof PROTOCOL_VERSION
  actor_id?: UUID
  response?: ResponseEnvelope
  recovery?: RecoveryEnvelope
  event?: EventEnvelope
  acknowledged?: number
  error?: ProtocolError
}

export interface CommandDescriptor {
  operation: Operation
  kind: RequestKind
  available: boolean
  description: string
}

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const operationSet = new Set<string>(OPERATIONS)
const eventTypeSet = new Set<string>(EVENT_TYPES)

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function isUUID(value: unknown): value is UUID {
  return typeof value === 'string' && UUID_PATTERN.test(value)
}

function isNonNegativeSafeInteger(value: unknown): value is number {
  return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0
}

function isScope(value: unknown): value is Scope {
  if (!isRecord(value) || !isUUID(value.actor_id)) return false
  if (value.session_id !== undefined && !isUUID(value.session_id)) return false
  if (value.profile !== undefined && typeof value.profile !== 'string') return false
  return value.channel === undefined || typeof value.channel === 'string'
}

function isCorrelation(value: unknown): value is Correlation {
  if (!isRecord(value) || !isUUID(value.actor_id)) return false
  return ['session_id', 'turn_id', 'task_id', 'tool_id'].every(
    (key) => value[key] === undefined || isUUID(value[key]),
  )
}

const computerPhases = new Set<ComputerPhase>([
  'requested', 'awaiting_approval', 'started', 'progress',
  'completed', 'failed', 'denied', 'interrupted', 'outcome_unknown',
])
const computerTerminalStatuses = new Set<ComputerTerminalStatus>([
  'completed', 'failed', 'denied', 'interrupted', 'outcome_unknown',
])
const computerEventTypeByPhase: Record<ComputerPhase, EventType> = {
  requested: 'tool.requested',
  awaiting_approval: 'tool.awaiting_approval',
  started: 'tool.started',
  progress: 'tool.delta',
  completed: 'tool.completed',
  failed: 'tool.failed',
  denied: 'tool.denied',
  interrupted: 'tool.interrupted',
  outcome_unknown: 'tool.outcome_unknown',
}
const computerEventTypes = new Set<EventType>(Object.values(computerEventTypeByPhase))
const displayKinds = new Set<DisplayKind>([
  'search', 'reader', 'navigation', 'repository', 'code', 'terminal', 'diff',
  'process', 'table', 'chart', 'document', 'artifact', 'task', 'agent',
  'approval', 'error', 'degraded',
])
const displayTruths = new Set<DisplayTruth>([
  'observed', 'generated', 'summarized', 'inferred', 'unavailable',
])
const displayFormats = new Set<DisplayFormat>([
  'text', 'url', 'path', 'integer', 'number', 'boolean', 'timestamp', 'status',
  'code', 'terminal', 'diff',
])
const displayBlockKinds = new Set<DisplayBlockKind>([
  'text', 'list', 'code', 'terminal', 'diff', 'table', 'chart', 'document',
  'empty',
])

function displayTextIsSafe(value: string, maximum = 16384): boolean {
  const credentialCheck = value.replaceAll('[REDACTED]', '')
  return value.trim().length > 0 &&
    new TextEncoder().encode(value).length <= maximum &&
    !/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f\u001b]/u.test(value) &&
    !/<\s*(?:script|style|iframe|object|embed|link|meta|[a-z][a-z0-9:-]*)(?:\s[^>]*)?>/iu.test(value) &&
    !/-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----/iu.test(value) &&
    !/\bbearer\s+[a-z0-9._~+/-]{8,}=*/iu.test(credentialCheck) &&
    !/\b(api[_-]?key|access[_-]?token|auth[_-]?token|password|passwd|secret)\b\s*[:=]\s*["']?[^\s"',;]{4,}/iu.test(credentialCheck)
}

function displayURLIsSafe(value: string): boolean {
  if (value.length > 2048 || value.includes('#')) return false
  try {
    const parsed = new URL(value)
    const sensitiveQuery = [...parsed.searchParams].some(([key, queryValue]) =>
      /(?:^|_)(?:api_?key|access_token|token|secret|password|passwd|authorization|signature|sig)$/iu
        .test(key) && queryValue !== '[REDACTED]'
    )
    return (parsed.protocol === 'http:' || parsed.protocol === 'https:') &&
      parsed.username === '' && parsed.password === '' &&
      parsed.hostname === parsed.hostname.toLowerCase() &&
      value.slice(0, value.indexOf(':')) === value.slice(0, value.indexOf(':')).toLowerCase() &&
      !sensitiveQuery
  } catch {
    return false
  }
}

function displayPathIsSafe(value: string): boolean {
  if (value.length === 0 || value.startsWith('/') || value.includes('\\')) return false
  const parts = value.split('/')
  return parts.every((part) => part !== '..' && part !== '' && part !== '.') ||
    value === '.'
}

function isDisplayDatum(value: unknown, sourceCount: number): value is DisplayDatum {
  if (!isRecord(value) || typeof value.value !== 'string' ||
    !displayTextIsSafe(value.value) || typeof value.truth !== 'string' ||
    !displayTruths.has(value.truth as DisplayTruth) ||
    typeof value.format !== 'string' ||
    !displayFormats.has(value.format as DisplayFormat) ||
    !Array.isArray(value.sources) || value.sources.length === 0 ||
    value.sources.length > 8) return false
  const sources = value.sources
  if (!sources.every((source) =>
    Number.isSafeInteger(source) && source >= 0 && source < sourceCount
  ) || new Set(sources).size !== sources.length) return false
  if (value.format === 'url' && !displayURLIsSafe(value.value)) return false
  return value.format !== 'path' || displayPathIsSafe(value.value)
}

function isDisplayField(value: unknown, sourceCount: number): value is DisplayField {
  return isRecord(value) && typeof value.label === 'string' &&
    displayTextIsSafe(value.label, 128) && isDisplayDatum(value.value, sourceCount)
}

function isDisplayItem(value: unknown, sourceCount: number): value is DisplayItem {
  return isRecord(value) && Array.isArray(value.fields) &&
    value.fields.length > 0 && value.fields.length <= 32 &&
    value.fields.every((field) => isDisplayField(field, sourceCount))
}

function isDisplayBlock(value: unknown, sourceCount: number): value is DisplayBlock {
  if (!isRecord(value) || typeof value.kind !== 'string' ||
    !displayBlockKinds.has(value.kind as DisplayBlockKind) ||
    (value.label !== undefined && (
      typeof value.label !== 'string' ||
      (value.label !== '' && !displayTextIsSafe(value.label, 128))
    )) || (value.language !== undefined && (
      typeof value.language !== 'string' ||
      (value.language !== '' && !displayTextIsSafe(value.language, 64))
    )) || (value.content !== undefined &&
      !isDisplayDatum(value.content, sourceCount))) return false
  if (value.fields !== undefined && (
    !Array.isArray(value.fields) || value.fields.length > 32 ||
    !value.fields.every((field) => isDisplayField(field, sourceCount))
  )) return false
  if (value.items !== undefined && (
    !Array.isArray(value.items) || value.items.length > 64 ||
    !value.items.every((item) => isDisplayItem(item, sourceCount))
  )) return false
  if (value.columns !== undefined && (
    !Array.isArray(value.columns) || value.columns.length > 16 ||
    !value.columns.every((column) =>
      typeof column === 'string' && displayTextIsSafe(column, 128)
    )
  )) return false
  if (value.rows !== undefined && (
    !Array.isArray(value.rows) || value.rows.length > 64 ||
    !value.rows.every((row) =>
      Array.isArray(row) && row.length > 0 && row.length <= 16 &&
      (value.columns === undefined ||
        row.length === (value.columns as unknown[]).length) &&
      row.every((datum) => isDisplayDatum(datum, sourceCount))
    )
  )) return false
  return true
}

export function isDisplayModel(
  value: unknown,
  sourceCount: number,
): value is DisplayModel {
  if (!isRecord(value) || value.protocol_version !== DISPLAY_MODEL_VERSION ||
    typeof value.kind !== 'string' || !displayKinds.has(value.kind as DisplayKind) ||
    !isDisplayDatum(value.title, sourceCount)) return false
  if (value.fields !== undefined && (
    !Array.isArray(value.fields) || value.fields.length > 32 ||
    !value.fields.every((field) => isDisplayField(field, sourceCount))
  )) return false
  if (value.blocks !== undefined && (
    !Array.isArray(value.blocks) || value.blocks.length > 16 ||
    !value.blocks.every((block) => isDisplayBlock(block, sourceCount))
  )) return false
  try {
    return new TextEncoder().encode(JSON.stringify(value)).length <= 65536
  } catch {
    return false
  }
}

export function displayModelCompatibility(
  value: unknown,
  sourceCount: number,
): DisplayCompatibility {
  if (!isRecord(value) || typeof value.protocol_version !== 'string' ||
    value.protocol_version.length === 0 || value.protocol_version.length > 128) {
    return 'invalid'
  }
  try {
    if (new TextEncoder().encode(JSON.stringify(value)).length > 65536) return 'invalid'
  } catch {
    return 'invalid'
  }
  if (value.protocol_version === DISPLAY_MODEL_VERSION) {
    return isDisplayModel(value, sourceCount) ? 'current' : 'invalid'
  }
  if (value.protocol_version === 'ion.display-model.v0') {
    return migrateDisplayModel(value, sourceCount) === undefined
      ? 'invalid'
      : 'migrated'
  }
  return 'unsupported'
}

export function migrateDisplayModel(
  value: unknown,
  sourceCount: number,
): DisplayModel | undefined {
  if (isDisplayModel(value, sourceCount)) return value
  if (!isRecord(value) ||
    value.protocol_version !== 'ion.display-model.v0' ||
    typeof value.kind !== 'string' || !displayKinds.has(value.kind as DisplayKind) ||
    typeof value.title !== 'string' || !displayTextIsSafe(value.title) ||
    (value.summary !== undefined && (
      typeof value.summary !== 'string' || !displayTextIsSafe(value.summary)
    )) || !Number.isSafeInteger(value.source) ||
    Number(value.source) < 0 || Number(value.source) >= sourceCount) return undefined
  const source = Number(value.source)
  const migrated: DisplayModel = {
    protocol_version: DISPLAY_MODEL_VERSION,
    kind: value.kind as DisplayKind,
    title: {
      value: value.title,
      truth: 'observed',
      format: 'text',
      sources: [source],
    },
  }
  if (typeof value.summary === 'string') {
    migrated.blocks = [{
      kind: 'text',
      content: {
        value: value.summary,
        truth: 'summarized',
        format: 'text',
        sources: [source],
      },
    }]
  }
  return isDisplayModel(migrated, sourceCount) ? migrated : undefined
}

export function isComputerEventPayload(value: unknown): value is ComputerEventPayload {
  if (!isRecord(value) || value.protocol_version !== COMPUTER_EVENT_VERSION) return false
  if (!isUUID(value.tool_event_id) || typeof value.provider_tool_call_id !== 'string' ||
    value.provider_tool_call_id.length === 0 || typeof value.tool !== 'string' ||
    value.tool.length === 0 || typeof value.operation !== 'string' ||
    value.operation.length === 0 || !isRecord(value.scope) ||
    !isUUID(value.scope.actor_id) || typeof value.scope.agent_id !== 'string' ||
    value.scope.agent_id.length === 0) return false
  for (const key of ['session_id', 'turn_id', 'task_id', 'outcome_id']) {
    if (value.scope[key] !== undefined && !isUUID(value.scope[key])) return false
  }
  if (value.scope.task_id === undefined && value.scope.outcome_id === undefined) return false
  if (!['GREEN', 'YELLOW', 'RED'].includes(String(value.risk_class)) ||
    typeof value.phase !== 'string' || !computerPhases.has(value.phase as ComputerPhase) ||
    typeof value.timestamp !== 'string' || Number.isNaN(Date.parse(value.timestamp)) ||
    typeof value.display_kind !== 'string' || value.display_kind.length === 0) return false
  if (!Array.isArray(value.source_references) || value.source_references.length === 0 ||
    value.source_references.length > 8 || value.source_references.some((reference) =>
      !isRecord(reference) || typeof reference.kind !== 'string' ||
      reference.kind.length === 0 || typeof reference.id !== 'string' ||
      reference.id.length === 0)) return false
  if (!value.source_references.some((reference) =>
    isRecord(reference) && reference.kind === 'tool_event' &&
    reference.id === value.tool_event_id)) return false
  const terminal = computerTerminalStatuses.has(value.phase as ComputerTerminalStatus)
  if (terminal !== (value.terminal_status === value.phase) ||
    terminal !== isRecord(value.result)) return false
  if (isRecord(value.result) && (
    typeof value.result.available !== 'boolean' ||
    !isNonNegativeSafeInteger(value.result.bytes) ||
    (value.result.error_code !== undefined && typeof value.result.error_code !== 'string') ||
    (value.result.error !== undefined && (
      typeof value.result.error !== 'string' || value.result.error.length > 1024
    ))
  )) return false
  if (value.phase === 'progress') {
    if (!Object.prototype.hasOwnProperty.call(value, 'progress')) return false
    try {
      if (JSON.stringify(value.progress).length > 16384) return false
    } catch {
      return false
    }
  } else if (value.progress !== undefined) return false
  if (value.display_model !== undefined &&
    displayModelCompatibility(
      value.display_model,
      value.source_references.length,
    ) === 'invalid') return false
  return true
}

export function isRequestEnvelope(value: unknown): value is RequestEnvelope {
  if (!isRecord(value) || value.protocol_version !== PROTOCOL_VERSION) return false
  if (!isUUID(value.request_id) || !isScope(value.scope)) return false
  if (value.kind !== 'query' && value.kind !== 'command') return false
  if (typeof value.operation !== 'string' || !operationSet.has(value.operation)) return false
  const operation = value.operation as Operation
  if (OPERATION_KINDS[operation] !== value.kind) return false
  if (value.kind === 'command' && (
    typeof value.idempotency_key !== 'string' || value.idempotency_key.length === 0
  )) return false
  if (
    value.expected_revision !== undefined &&
    !isNonNegativeSafeInteger(value.expected_revision)
  ) return false
  return Object.prototype.hasOwnProperty.call(value, 'payload')
}

export function isResponseEnvelope(value: unknown): value is ResponseEnvelope {
  if (!isRecord(value) || value.protocol_version !== PROTOCOL_VERSION) return false
  if (!isUUID(value.request_id) || !isNonNegativeSafeInteger(value.revision)) return false
  if (value.error === undefined) return Object.prototype.hasOwnProperty.call(value, 'result')
  if (!isRecord(value.error)) return false
  const validCodes = new Set([
    'invalid', 'unauthorized', 'forbidden', 'not_found', 'conflict',
    'rate_limited', 'unavailable', 'internal',
  ])
  return (
    typeof value.error.code === 'string' &&
    validCodes.has(value.error.code) &&
    typeof value.error.message === 'string' &&
    typeof value.error.retryable === 'boolean'
  )
}

export function isEventEnvelope(value: unknown): value is EventEnvelope {
  if (!isRecord(value) || !isNonNegativeSafeInteger(value.sequence)) return false
  if (!isUUID(value.event_id) || !isCorrelation(value.correlation)) return false
  if (typeof value.type !== 'string' || !eventTypeSet.has(value.type)) return false
  if (typeof value.occurred_at !== 'string' || Number.isNaN(Date.parse(value.occurred_at))) {
    return false
  }
  if (!Object.prototype.hasOwnProperty.call(value, 'payload')) return false
  const eventType = value.type as EventType
  if (!computerEventTypes.has(eventType)) return true
  if (!isRecord(value.payload) ||
    value.payload.protocol_version !== COMPUTER_EVENT_VERSION) {
    return true
  }
  return isComputerEventPayload(value.payload) &&
    value.correlation.tool_id === value.payload.tool_event_id &&
    value.correlation.actor_id === value.payload.scope.actor_id &&
    computerEventTypeByPhase[value.payload.phase] === eventType
}

export function isWorkspaceOperationEnvelope(
  value: unknown,
): value is WorkspaceOperationEnvelope {
  if (!isRecord(value) || value.version !== WORKSPACE_HOST_VERSION) return false
  const operations = new Set([
    'workspace.provision', 'workspace.readiness', 'workspace.pause',
    'workspace.resume', 'workspace.stop', 'workspace.archive', 'workspace.destroy',
  ])
  if (typeof value.operation !== 'string' || !operations.has(value.operation)) return false
  if (!isUUID(value.actor_id) || !isUUID(value.project_id) || !isUUID(value.request_id)) return false
  if (!isUUID(value.correlation_id) || !isNonNegativeSafeInteger(value.workspace_revision)) return false
  if (typeof value.idempotency_key !== 'string' || value.idempotency_key.length === 0) return false
  if (!['GREEN', 'YELLOW', 'RED'].includes(String(value.policy_classification))) return false
  if (typeof value.deadline !== 'string' || Number.isNaN(Date.parse(value.deadline))) return false
  if (value.secret_grants !== undefined && (!Array.isArray(value.secret_grants) ||
    value.secret_grants.some((grant) => !isRecord(grant) ||
      !isUUID(grant.id) || typeof grant.reference !== 'string' || grant.reference.length === 0 ||
      typeof grant.grant_token !== 'string' || grant.grant_token.length === 0 ||
      typeof grant.expires_at !== 'string' || Number.isNaN(Date.parse(grant.expires_at))))) {
    return false
  }
  return true
}

export function assertRequestEnvelope(value: unknown): asserts value is RequestEnvelope {
  if (!isRequestEnvelope(value)) throw new TypeError('invalid control-plane request')
}

export function assertResponseEnvelope(value: unknown): asserts value is ResponseEnvelope {
  if (!isResponseEnvelope(value)) throw new TypeError('invalid control-plane response')
}

export function assertEventEnvelope(value: unknown): asserts value is EventEnvelope {
  if (!isEventEnvelope(value)) throw new TypeError('invalid control-plane event')
}
`
