// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type AppendAck struct {
	_tab flatbuffers.Table
}

func GetRootAsAppendAck(buf []byte, offset flatbuffers.UOffsetT) *AppendAck {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AppendAck{}
	x.Init(buf, n+offset)
	return x
}

func FinishAppendAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAppendAck(buf []byte, offset flatbuffers.UOffsetT) *AppendAck {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AppendAck{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAppendAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AppendAck) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AppendAck) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AppendAck) ClientSeq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendAck) MutateClientSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *AppendAck) FirstLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendAck) MutateFirstLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *AppendAck) LastLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendAck) MutateLastLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *AppendAck) Duplicate() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *AppendAck) MutateDuplicate(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *AppendAck) LeafCount() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendAck) MutateLeafCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *AppendAck) LastLeafHash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *AppendAck) LastLeafHashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AppendAck) LastLeafHashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppendAck) MutateLastLeafHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *AppendAck) MmrRoot(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *AppendAck) MmrRootLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AppendAck) MmrRootBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppendAck) MutateMmrRoot(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func AppendAckStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func AppendAckAddClientSeq(builder *flatbuffers.Builder, clientSeq uint64) {
	builder.PrependUint64Slot(0, clientSeq, 0)
}
func AppendAckAddFirstLsn(builder *flatbuffers.Builder, firstLsn uint64) {
	builder.PrependUint64Slot(1, firstLsn, 0)
}
func AppendAckAddLastLsn(builder *flatbuffers.Builder, lastLsn uint64) {
	builder.PrependUint64Slot(2, lastLsn, 0)
}
func AppendAckAddDuplicate(builder *flatbuffers.Builder, duplicate bool) {
	builder.PrependBoolSlot(3, duplicate, false)
}
func AppendAckAddLeafCount(builder *flatbuffers.Builder, leafCount uint64) {
	builder.PrependUint64Slot(4, leafCount, 0)
}
func AppendAckAddLastLeafHash(builder *flatbuffers.Builder, lastLeafHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(lastLeafHash), 0)
}
func AppendAckStartLastLeafHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func AppendAckAddMmrRoot(builder *flatbuffers.Builder, mmrRoot flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(mmrRoot), 0)
}
func AppendAckStartMmrRootVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func AppendAckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
