// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type AsOf struct {
	_tab flatbuffers.Table
}

func GetRootAsAsOf(buf []byte, offset flatbuffers.UOffsetT) *AsOf {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AsOf{}
	x.Init(buf, n+offset)
	return x
}

func FinishAsOfBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAsOf(buf []byte, offset flatbuffers.UOffsetT) *AsOf {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AsOf{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAsOfBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AsOf) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AsOf) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AsOf) BeliefType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AsOf) MutateBeliefType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *AsOf) CanonicalIdentity() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AsOf) ValidTimeNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AsOf) MutateValidTimeNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *AsOf) TransactionLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AsOf) MutateTransactionLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func AsOfStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func AsOfAddBeliefType(builder *flatbuffers.Builder, beliefType byte) {
	builder.PrependByteSlot(0, beliefType, 0)
}
func AsOfAddCanonicalIdentity(builder *flatbuffers.Builder, canonicalIdentity flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(canonicalIdentity), 0)
}
func AsOfAddValidTimeNs(builder *flatbuffers.Builder, validTimeNs int64) {
	builder.PrependInt64Slot(2, validTimeNs, 0)
}
func AsOfAddTransactionLsn(builder *flatbuffers.Builder, transactionLsn uint64) {
	builder.PrependUint64Slot(3, transactionLsn, 0)
}
func AsOfEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
