// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type AttestAck struct {
	_tab flatbuffers.Table
}

func GetRootAsAttestAck(buf []byte, offset flatbuffers.UOffsetT) *AttestAck {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AttestAck{}
	x.Init(buf, n+offset)
	return x
}

func FinishAttestAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAttestAck(buf []byte, offset flatbuffers.UOffsetT) *AttestAck {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AttestAck{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAttestAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AttestAck) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AttestAck) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AttestAck) FirstLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AttestAck) MutateFirstLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *AttestAck) LastLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AttestAck) MutateLastLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *AttestAck) Count() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AttestAck) MutateCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func AttestAckStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AttestAckAddFirstLsn(builder *flatbuffers.Builder, firstLsn uint64) {
	builder.PrependUint64Slot(0, firstLsn, 0)
}
func AttestAckAddLastLsn(builder *flatbuffers.Builder, lastLsn uint64) {
	builder.PrependUint64Slot(1, lastLsn, 0)
}
func AttestAckAddCount(builder *flatbuffers.Builder, count uint32) {
	builder.PrependUint32Slot(2, count, 0)
}
func AttestAckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
