// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type BeliefResult struct {
	_tab flatbuffers.Table
}

func GetRootAsBeliefResult(buf []byte, offset flatbuffers.UOffsetT) *BeliefResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BeliefResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishBeliefResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBeliefResult(buf []byte, offset flatbuffers.UOffsetT) *BeliefResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BeliefResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBeliefResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BeliefResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BeliefResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BeliefResult) Present() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *BeliefResult) MutatePresent(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *BeliefResult) BeliefType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefResult) MutateBeliefType(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *BeliefResult) BeliefId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BeliefResult) BeliefIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BeliefResult) BeliefIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BeliefResult) MutateBeliefId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BeliefResult) CanonicalIdentity() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BeliefResult) ConflictDomain() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BeliefResult) Value(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BeliefResult) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BeliefResult) ValueBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BeliefResult) MutateValue(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BeliefResult) Claim() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefResult) MutateClaim(n byte) bool {
	return rcv._tab.MutateByteSlot(16, n)
}

func (rcv *BeliefResult) ValidFromNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefResult) MutateValidFromNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *BeliefResult) ValidToNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefResult) MutateValidToNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func (rcv *BeliefResult) TransactionLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefResult) MutateTransactionLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func (rcv *BeliefResult) Version() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefResult) MutateVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(24, n)
}

func (rcv *BeliefResult) SupersedesVersion() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefResult) MutateSupersedesVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(26, n)
}

func (rcv *BeliefResult) Provenance(obj *BeliefProvenanceRecord, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BeliefResult) ProvenanceLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BeliefResult) ConflictEdges(obj *BeliefConflictRecord, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BeliefResult) ConflictEdgesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BeliefResult) Tombstoned() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *BeliefResult) MutateTombstoned(n bool) bool {
	return rcv._tab.MutateBoolSlot(32, n)
}

func BeliefResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func BeliefResultAddPresent(builder *flatbuffers.Builder, present bool) {
	builder.PrependBoolSlot(0, present, false)
}
func BeliefResultAddBeliefType(builder *flatbuffers.Builder, beliefType byte) {
	builder.PrependByteSlot(1, beliefType, 0)
}
func BeliefResultAddBeliefId(builder *flatbuffers.Builder, beliefId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(beliefId), 0)
}
func BeliefResultStartBeliefIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BeliefResultAddCanonicalIdentity(builder *flatbuffers.Builder, canonicalIdentity flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(canonicalIdentity), 0)
}
func BeliefResultAddConflictDomain(builder *flatbuffers.Builder, conflictDomain flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(conflictDomain), 0)
}
func BeliefResultAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(value), 0)
}
func BeliefResultStartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BeliefResultAddClaim(builder *flatbuffers.Builder, claim byte) {
	builder.PrependByteSlot(6, claim, 0)
}
func BeliefResultAddValidFromNs(builder *flatbuffers.Builder, validFromNs int64) {
	builder.PrependInt64Slot(7, validFromNs, 0)
}
func BeliefResultAddValidToNs(builder *flatbuffers.Builder, validToNs int64) {
	builder.PrependInt64Slot(8, validToNs, 0)
}
func BeliefResultAddTransactionLsn(builder *flatbuffers.Builder, transactionLsn uint64) {
	builder.PrependUint64Slot(9, transactionLsn, 0)
}
func BeliefResultAddVersion(builder *flatbuffers.Builder, version uint64) {
	builder.PrependUint64Slot(10, version, 0)
}
func BeliefResultAddSupersedesVersion(builder *flatbuffers.Builder, supersedesVersion uint64) {
	builder.PrependUint64Slot(11, supersedesVersion, 0)
}
func BeliefResultAddProvenance(builder *flatbuffers.Builder, provenance flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(provenance), 0)
}
func BeliefResultStartProvenanceVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BeliefResultAddConflictEdges(builder *flatbuffers.Builder, conflictEdges flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(conflictEdges), 0)
}
func BeliefResultStartConflictEdgesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BeliefResultAddTombstoned(builder *flatbuffers.Builder, tombstoned bool) {
	builder.PrependBoolSlot(14, tombstoned, false)
}
func BeliefResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
