// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type BeliefConflictRecord struct {
	_tab flatbuffers.Table
}

func GetRootAsBeliefConflictRecord(buf []byte, offset flatbuffers.UOffsetT) *BeliefConflictRecord {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BeliefConflictRecord{}
	x.Init(buf, n+offset)
	return x
}

func FinishBeliefConflictRecordBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBeliefConflictRecord(buf []byte, offset flatbuffers.UOffsetT) *BeliefConflictRecord {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BeliefConflictRecord{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBeliefConflictRecordBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BeliefConflictRecord) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BeliefConflictRecord) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BeliefConflictRecord) OtherType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefConflictRecord) MutateOtherType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *BeliefConflictRecord) OtherCanonicalIdentity() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BeliefConflictRecord) CreatedLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefConflictRecord) MutateCreatedLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *BeliefConflictRecord) ResolvedLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefConflictRecord) MutateResolvedLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *BeliefConflictRecord) ObligatedSurfacing() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *BeliefConflictRecord) MutateObligatedSurfacing(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func BeliefConflictRecordStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func BeliefConflictRecordAddOtherType(builder *flatbuffers.Builder, otherType byte) {
	builder.PrependByteSlot(0, otherType, 0)
}
func BeliefConflictRecordAddOtherCanonicalIdentity(builder *flatbuffers.Builder, otherCanonicalIdentity flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(otherCanonicalIdentity), 0)
}
func BeliefConflictRecordAddCreatedLsn(builder *flatbuffers.Builder, createdLsn uint64) {
	builder.PrependUint64Slot(2, createdLsn, 0)
}
func BeliefConflictRecordAddResolvedLsn(builder *flatbuffers.Builder, resolvedLsn uint64) {
	builder.PrependUint64Slot(3, resolvedLsn, 0)
}
func BeliefConflictRecordAddObligatedSurfacing(builder *flatbuffers.Builder, obligatedSurfacing bool) {
	builder.PrependBoolSlot(4, obligatedSurfacing, false)
}
func BeliefConflictRecordEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
