// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type BeliefProvenanceRecord struct {
	_tab flatbuffers.Table
}

func GetRootAsBeliefProvenanceRecord(buf []byte, offset flatbuffers.UOffsetT) *BeliefProvenanceRecord {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BeliefProvenanceRecord{}
	x.Init(buf, n+offset)
	return x
}

func FinishBeliefProvenanceRecordBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBeliefProvenanceRecord(buf []byte, offset flatbuffers.UOffsetT) *BeliefProvenanceRecord {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BeliefProvenanceRecord{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBeliefProvenanceRecordBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BeliefProvenanceRecord) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BeliefProvenanceRecord) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BeliefProvenanceRecord) FirstLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefProvenanceRecord) MutateFirstLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *BeliefProvenanceRecord) LastLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BeliefProvenanceRecord) MutateLastLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func BeliefProvenanceRecordStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BeliefProvenanceRecordAddFirstLsn(builder *flatbuffers.Builder, firstLsn uint64) {
	builder.PrependUint64Slot(0, firstLsn, 0)
}
func BeliefProvenanceRecordAddLastLsn(builder *flatbuffers.Builder, lastLsn uint64) {
	builder.PrependUint64Slot(1, lastLsn, 0)
}
func BeliefProvenanceRecordEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
