// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type CryptoDelete struct {
	_tab flatbuffers.Table
}

func GetRootAsCryptoDelete(buf []byte, offset flatbuffers.UOffsetT) *CryptoDelete {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CryptoDelete{}
	x.Init(buf, n+offset)
	return x
}

func FinishCryptoDeleteBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCryptoDelete(buf []byte, offset flatbuffers.UOffsetT) *CryptoDelete {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CryptoDelete{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCryptoDeleteBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CryptoDelete) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CryptoDelete) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CryptoDelete) Actor() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CryptoDelete) MutateActor(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func CryptoDeleteStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CryptoDeleteAddActor(builder *flatbuffers.Builder, actor uint16) {
	builder.PrependUint16Slot(0, actor, 0)
}
func CryptoDeleteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
