// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type ErrorDetail struct {
	_tab flatbuffers.Table
}

func GetRootAsErrorDetail(buf []byte, offset flatbuffers.UOffsetT) *ErrorDetail {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ErrorDetail{}
	x.Init(buf, n+offset)
	return x
}

func FinishErrorDetailBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsErrorDetail(buf []byte, offset flatbuffers.UOffsetT) *ErrorDetail {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ErrorDetail{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedErrorDetailBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ErrorDetail) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ErrorDetail) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ErrorDetail) Code() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ErrorDetail) MutateCode(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *ErrorDetail) SystemError() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ErrorDetail) MutateSystemError(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *ErrorDetail) Lsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ErrorDetail) MutateLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *ErrorDetail) Offset() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ErrorDetail) MutateOffset(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func ErrorDetailStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ErrorDetailAddCode(builder *flatbuffers.Builder, code byte) {
	builder.PrependByteSlot(0, code, 0)
}
func ErrorDetailAddSystemError(builder *flatbuffers.Builder, systemError int32) {
	builder.PrependInt32Slot(1, systemError, 0)
}
func ErrorDetailAddLsn(builder *flatbuffers.Builder, lsn uint64) {
	builder.PrependUint64Slot(2, lsn, 0)
}
func ErrorDetailAddOffset(builder *flatbuffers.Builder, offset uint64) {
	builder.PrependUint64Slot(3, offset, 0)
}
func ErrorDetailEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
