// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type HealthResult struct {
	_tab flatbuffers.Table
}

func GetRootAsHealthResult(buf []byte, offset flatbuffers.UOffsetT) *HealthResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HealthResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishHealthResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHealthResult(buf []byte, offset flatbuffers.UOffsetT) *HealthResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HealthResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHealthResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HealthResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HealthResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HealthResult) Ready() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *HealthResult) MutateReady(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *HealthResult) ActorCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HealthResult) MutateActorCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *HealthResult) ActiveConnections() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HealthResult) MutateActiveConnections(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func HealthResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func HealthResultAddReady(builder *flatbuffers.Builder, ready bool) {
	builder.PrependBoolSlot(0, ready, false)
}
func HealthResultAddActorCount(builder *flatbuffers.Builder, actorCount uint32) {
	builder.PrependUint32Slot(1, actorCount, 0)
}
func HealthResultAddActiveConnections(builder *flatbuffers.Builder, activeConnections uint32) {
	builder.PrependUint32Slot(2, activeConnections, 0)
}
func HealthResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
