// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type LatencyBucket struct {
	_tab flatbuffers.Table
}

func GetRootAsLatencyBucket(buf []byte, offset flatbuffers.UOffsetT) *LatencyBucket {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LatencyBucket{}
	x.Init(buf, n+offset)
	return x
}

func FinishLatencyBucketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLatencyBucket(buf []byte, offset flatbuffers.UOffsetT) *LatencyBucket {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LatencyBucket{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLatencyBucketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LatencyBucket) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LatencyBucket) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LatencyBucket) Operation() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LatencyBucket) UpperBoundNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LatencyBucket) MutateUpperBoundNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *LatencyBucket) Count() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LatencyBucket) MutateCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func LatencyBucketStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func LatencyBucketAddOperation(builder *flatbuffers.Builder, operation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(operation), 0)
}
func LatencyBucketAddUpperBoundNs(builder *flatbuffers.Builder, upperBoundNs uint64) {
	builder.PrependUint64Slot(1, upperBoundNs, 0)
}
func LatencyBucketAddCount(builder *flatbuffers.Builder, count uint64) {
	builder.PrependUint64Slot(2, count, 0)
}
func LatencyBucketEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
