// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type RebuildResult struct {
	_tab flatbuffers.Table
}

func GetRootAsRebuildResult(buf []byte, offset flatbuffers.UOffsetT) *RebuildResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RebuildResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishRebuildResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRebuildResult(buf []byte, offset flatbuffers.UOffsetT) *RebuildResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RebuildResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRebuildResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RebuildResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RebuildResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RebuildResult) Actor() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RebuildResult) MutateActor(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *RebuildResult) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RebuildResult) AppliedLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RebuildResult) MutateAppliedLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func RebuildResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RebuildResultAddActor(builder *flatbuffers.Builder, actor uint16) {
	builder.PrependUint16Slot(0, actor, 0)
}
func RebuildResultAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func RebuildResultAddAppliedLsn(builder *flatbuffers.Builder, appliedLsn uint64) {
	builder.PrependUint64Slot(2, appliedLsn, 0)
}
func RebuildResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
