// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type RecallMode byte

const (
	RecallModelist_windows    RecallMode = 0
	RecallModeopen_window     RecallMode = 1
	RecallModeresolve_members RecallMode = 2
)

var EnumNamesRecallMode = map[RecallMode]string{
	RecallModelist_windows:    "list_windows",
	RecallModeopen_window:     "open_window",
	RecallModeresolve_members: "resolve_members",
}

var EnumValuesRecallMode = map[string]RecallMode{
	"list_windows":    RecallModelist_windows,
	"open_window":     RecallModeopen_window,
	"resolve_members": RecallModeresolve_members,
}

func (v RecallMode) String() string {
	if s, ok := EnumNamesRecallMode[v]; ok {
		return s
	}
	return "RecallMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
