// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type RequestPayload byte

const (
	RequestPayloadNONE              RequestPayload = 0
	RequestPayloadAppend            RequestPayload = 1
	RequestPayloadActivate          RequestPayload = 2
	RequestPayloadTranscript        RequestPayload = 3
	RequestPayloadRecall            RequestPayload = 4
	RequestPayloadAsOf              RequestPayload = 5
	RequestPayloadCheckpoint        RequestPayload = 6
	RequestPayloadLatestCheckpoint  RequestPayload = 7
	RequestPayloadAttest            RequestPayload = 8
	RequestPayloadSubscribe         RequestPayload = 9
	RequestPayloadHealth            RequestPayload = 10
	RequestPayloadStats             RequestPayload = 11
	RequestPayloadLatencyHistograms RequestPayload = 12
	RequestPayloadVerifyStatus      RequestPayload = 13
	RequestPayloadRebuildProjection RequestPayload = 14
	RequestPayloadCryptoDelete      RequestPayload = 15
)

var EnumNamesRequestPayload = map[RequestPayload]string{
	RequestPayloadNONE:              "NONE",
	RequestPayloadAppend:            "Append",
	RequestPayloadActivate:          "Activate",
	RequestPayloadTranscript:        "Transcript",
	RequestPayloadRecall:            "Recall",
	RequestPayloadAsOf:              "AsOf",
	RequestPayloadCheckpoint:        "Checkpoint",
	RequestPayloadLatestCheckpoint:  "LatestCheckpoint",
	RequestPayloadAttest:            "Attest",
	RequestPayloadSubscribe:         "Subscribe",
	RequestPayloadHealth:            "Health",
	RequestPayloadStats:             "Stats",
	RequestPayloadLatencyHistograms: "LatencyHistograms",
	RequestPayloadVerifyStatus:      "VerifyStatus",
	RequestPayloadRebuildProjection: "RebuildProjection",
	RequestPayloadCryptoDelete:      "CryptoDelete",
}

var EnumValuesRequestPayload = map[string]RequestPayload{
	"NONE":              RequestPayloadNONE,
	"Append":            RequestPayloadAppend,
	"Activate":          RequestPayloadActivate,
	"Transcript":        RequestPayloadTranscript,
	"Recall":            RequestPayloadRecall,
	"AsOf":              RequestPayloadAsOf,
	"Checkpoint":        RequestPayloadCheckpoint,
	"LatestCheckpoint":  RequestPayloadLatestCheckpoint,
	"Attest":            RequestPayloadAttest,
	"Subscribe":         RequestPayloadSubscribe,
	"Health":            RequestPayloadHealth,
	"Stats":             RequestPayloadStats,
	"LatencyHistograms": RequestPayloadLatencyHistograms,
	"VerifyStatus":      RequestPayloadVerifyStatus,
	"RebuildProjection": RequestPayloadRebuildProjection,
	"CryptoDelete":      RequestPayloadCryptoDelete,
}

func (v RequestPayload) String() string {
	if s, ok := EnumNamesRequestPayload[v]; ok {
		return s
	}
	return "RequestPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
