// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type ResponsePayload byte

const (
	ResponsePayloadNONE             ResponsePayload = 0
	ResponsePayloadErrorDetail      ResponsePayload = 1
	ResponsePayloadAppendAck        ResponsePayload = 2
	ResponsePayloadBytesResult      ResponsePayload = 3
	ResponsePayloadSubscriptionAck  ResponsePayload = 4
	ResponsePayloadHealthResult     ResponsePayload = 5
	ResponsePayloadStatsResult      ResponsePayload = 6
	ResponsePayloadLatencyResult    ResponsePayload = 7
	ResponsePayloadVerifyResult     ResponsePayload = 8
	ResponsePayloadRebuildResult    ResponsePayload = 9
	ResponsePayloadDeleteResult     ResponsePayload = 10
	ResponsePayloadTranscriptResult ResponsePayload = 11
	ResponsePayloadRecallResult     ResponsePayload = 12
	ResponsePayloadBeliefResult     ResponsePayload = 13
	ResponsePayloadCheckpointAck    ResponsePayload = 14
	ResponsePayloadCheckpointResult ResponsePayload = 15
	ResponsePayloadAttestAck        ResponsePayload = 16
)

var EnumNamesResponsePayload = map[ResponsePayload]string{
	ResponsePayloadNONE:             "NONE",
	ResponsePayloadErrorDetail:      "ErrorDetail",
	ResponsePayloadAppendAck:        "AppendAck",
	ResponsePayloadBytesResult:      "BytesResult",
	ResponsePayloadSubscriptionAck:  "SubscriptionAck",
	ResponsePayloadHealthResult:     "HealthResult",
	ResponsePayloadStatsResult:      "StatsResult",
	ResponsePayloadLatencyResult:    "LatencyResult",
	ResponsePayloadVerifyResult:     "VerifyResult",
	ResponsePayloadRebuildResult:    "RebuildResult",
	ResponsePayloadDeleteResult:     "DeleteResult",
	ResponsePayloadTranscriptResult: "TranscriptResult",
	ResponsePayloadRecallResult:     "RecallResult",
	ResponsePayloadBeliefResult:     "BeliefResult",
	ResponsePayloadCheckpointAck:    "CheckpointAck",
	ResponsePayloadCheckpointResult: "CheckpointResult",
	ResponsePayloadAttestAck:        "AttestAck",
}

var EnumValuesResponsePayload = map[string]ResponsePayload{
	"NONE":             ResponsePayloadNONE,
	"ErrorDetail":      ResponsePayloadErrorDetail,
	"AppendAck":        ResponsePayloadAppendAck,
	"BytesResult":      ResponsePayloadBytesResult,
	"SubscriptionAck":  ResponsePayloadSubscriptionAck,
	"HealthResult":     ResponsePayloadHealthResult,
	"StatsResult":      ResponsePayloadStatsResult,
	"LatencyResult":    ResponsePayloadLatencyResult,
	"VerifyResult":     ResponsePayloadVerifyResult,
	"RebuildResult":    ResponsePayloadRebuildResult,
	"DeleteResult":     ResponsePayloadDeleteResult,
	"TranscriptResult": ResponsePayloadTranscriptResult,
	"RecallResult":     ResponsePayloadRecallResult,
	"BeliefResult":     ResponsePayloadBeliefResult,
	"CheckpointAck":    ResponsePayloadCheckpointAck,
	"CheckpointResult": ResponsePayloadCheckpointResult,
	"AttestAck":        ResponsePayloadAttestAck,
}

func (v ResponsePayload) String() string {
	if s, ok := EnumNamesResponsePayload[v]; ok {
		return s
	}
	return "ResponsePayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
