// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type ResponseStatus byte

const (
	ResponseStatusok    ResponseStatus = 0
	ResponseStatuserror ResponseStatus = 1
)

var EnumNamesResponseStatus = map[ResponseStatus]string{
	ResponseStatusok:    "ok",
	ResponseStatuserror: "error",
}

var EnumValuesResponseStatus = map[string]ResponseStatus{
	"ok":    ResponseStatusok,
	"error": ResponseStatuserror,
}

func (v ResponseStatus) String() string {
	if s, ok := EnumNamesResponseStatus[v]; ok {
		return s
	}
	return "ResponseStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
