// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type StatsResult struct {
	_tab flatbuffers.Table
}

func GetRootAsStatsResult(buf []byte, offset flatbuffers.UOffsetT) *StatsResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatsResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatsResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatsResult(buf []byte, offset flatbuffers.UOffsetT) *StatsResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatsResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatsResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatsResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatsResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatsResult) Actor() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatsResult) MutateActor(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *StatsResult) LogEvents() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatsResult) MutateLogEvents(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *StatsResult) LogBytes() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatsResult) MutateLogBytes(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *StatsResult) ProjectionStats(obj *ProjectionStat, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *StatsResult) ProjectionStatsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func StatsResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func StatsResultAddActor(builder *flatbuffers.Builder, actor uint16) {
	builder.PrependUint16Slot(0, actor, 0)
}
func StatsResultAddLogEvents(builder *flatbuffers.Builder, logEvents uint64) {
	builder.PrependUint64Slot(1, logEvents, 0)
}
func StatsResultAddLogBytes(builder *flatbuffers.Builder, logBytes uint64) {
	builder.PrependUint64Slot(2, logBytes, 0)
}
func StatsResultAddProjectionStats(builder *flatbuffers.Builder, projectionStats flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(projectionStats), 0)
}
func StatsResultStartProjectionStatsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StatsResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
