// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type SubscriptionAck struct {
	_tab flatbuffers.Table
}

func GetRootAsSubscriptionAck(buf []byte, offset flatbuffers.UOffsetT) *SubscriptionAck {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SubscriptionAck{}
	x.Init(buf, n+offset)
	return x
}

func FinishSubscriptionAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSubscriptionAck(buf []byte, offset flatbuffers.UOffsetT) *SubscriptionAck {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SubscriptionAck{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSubscriptionAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SubscriptionAck) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SubscriptionAck) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SubscriptionAck) SubscriptionId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SubscriptionAck) MutateSubscriptionId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func SubscriptionAckStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SubscriptionAckAddSubscriptionId(builder *flatbuffers.Builder, subscriptionId uint64) {
	builder.PrependUint64Slot(0, subscriptionId, 0)
}
func SubscriptionAckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
