// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type TemporalWindowRecord struct {
	_tab flatbuffers.Table
}

func GetRootAsTemporalWindowRecord(buf []byte, offset flatbuffers.UOffsetT) *TemporalWindowRecord {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TemporalWindowRecord{}
	x.Init(buf, n+offset)
	return x
}

func FinishTemporalWindowRecordBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTemporalWindowRecord(buf []byte, offset flatbuffers.UOffsetT) *TemporalWindowRecord {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TemporalWindowRecord{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTemporalWindowRecordBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TemporalWindowRecord) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TemporalWindowRecord) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TemporalWindowRecord) Level() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TemporalWindowRecord) MutateLevel(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *TemporalWindowRecord) StartNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TemporalWindowRecord) MutateStartNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *TemporalWindowRecord) EndNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TemporalWindowRecord) MutateEndNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *TemporalWindowRecord) MemberCount() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TemporalWindowRecord) MutateMemberCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func TemporalWindowRecordStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TemporalWindowRecordAddLevel(builder *flatbuffers.Builder, level byte) {
	builder.PrependByteSlot(0, level, 0)
}
func TemporalWindowRecordAddStartNs(builder *flatbuffers.Builder, startNs int64) {
	builder.PrependInt64Slot(1, startNs, 0)
}
func TemporalWindowRecordAddEndNs(builder *flatbuffers.Builder, endNs int64) {
	builder.PrependInt64Slot(2, endNs, 0)
}
func TemporalWindowRecordAddMemberCount(builder *flatbuffers.Builder, memberCount uint64) {
	builder.PrependUint64Slot(3, memberCount, 0)
}
func TemporalWindowRecordEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
