// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type VerifyResult struct {
	_tab flatbuffers.Table
}

func GetRootAsVerifyResult(buf []byte, offset flatbuffers.UOffsetT) *VerifyResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VerifyResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishVerifyResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVerifyResult(buf []byte, offset flatbuffers.UOffsetT) *VerifyResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VerifyResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVerifyResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VerifyResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VerifyResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VerifyResult) Actor() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VerifyResult) MutateActor(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *VerifyResult) Root(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *VerifyResult) RootLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *VerifyResult) RootBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *VerifyResult) MutateRoot(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *VerifyResult) LeafCount() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VerifyResult) MutateLeafCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *VerifyResult) LastCheckpointLsn() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VerifyResult) MutateLastCheckpointLsn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *VerifyResult) Verified() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VerifyResult) MutateVerified(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func VerifyResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func VerifyResultAddActor(builder *flatbuffers.Builder, actor uint16) {
	builder.PrependUint16Slot(0, actor, 0)
}
func VerifyResultAddRoot(builder *flatbuffers.Builder, root flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(root), 0)
}
func VerifyResultStartRootVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func VerifyResultAddLeafCount(builder *flatbuffers.Builder, leafCount uint64) {
	builder.PrependUint64Slot(2, leafCount, 0)
}
func VerifyResultAddLastCheckpointLsn(builder *flatbuffers.Builder, lastCheckpointLsn uint64) {
	builder.PrependUint64Slot(3, lastCheckpointLsn, 0)
}
func VerifyResultAddVerified(builder *flatbuffers.Builder, verified bool) {
	builder.PrependBoolSlot(4, verified, false)
}
func VerifyResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
