// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type WirePayload byte

const (
	WirePayloadNONE     WirePayload = 0
	WirePayloadHello    WirePayload = 1
	WirePayloadWelcome  WirePayload = 2
	WirePayloadRequest  WirePayload = 3
	WirePayloadResponse WirePayload = 4
	WirePayloadEvent    WirePayload = 5
)

var EnumNamesWirePayload = map[WirePayload]string{
	WirePayloadNONE:     "NONE",
	WirePayloadHello:    "Hello",
	WirePayloadWelcome:  "Welcome",
	WirePayloadRequest:  "Request",
	WirePayloadResponse: "Response",
	WirePayloadEvent:    "Event",
}

var EnumValuesWirePayload = map[string]WirePayload{
	"NONE":     WirePayloadNONE,
	"Hello":    WirePayloadHello,
	"Welcome":  WirePayloadWelcome,
	"Request":  WirePayloadRequest,
	"Response": WirePayloadResponse,
	"Event":    WirePayloadEvent,
}

func (v WirePayload) String() string {
	if s, ok := EnumNamesWirePayload[v]; ok {
		return s
	}
	return "WirePayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
