// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "centra/core/cortexclient/internal/flatbuffers"
)

type WireEnvelope struct {
	_tab flatbuffers.Table
}

const WireEnvelopeIdentifier = "NCPR"

func GetRootAsWireEnvelope(buf []byte, offset flatbuffers.UOffsetT) *WireEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WireEnvelope{}
	x.Init(buf, n+offset)
	return x
}

func FinishWireEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(WireEnvelopeIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func WireEnvelopeBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, WireEnvelopeIdentifier)
}

func GetSizePrefixedRootAsWireEnvelope(buf []byte, offset flatbuffers.UOffsetT) *WireEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WireEnvelope{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWireEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(WireEnvelopeIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedWireEnvelopeBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, WireEnvelopeIdentifier)
}

func (rcv *WireEnvelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WireEnvelope) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WireEnvelope) ProtoVersion() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *WireEnvelope) MutateProtoVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *WireEnvelope) PayloadType() WirePayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return WirePayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *WireEnvelope) MutatePayloadType(n WirePayload) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *WireEnvelope) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func WireEnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func WireEnvelopeAddProtoVersion(builder *flatbuffers.Builder, protoVersion uint16) {
	builder.PrependUint16Slot(0, protoVersion, 0)
}
func WireEnvelopeAddPayloadType(builder *flatbuffers.Builder, payloadType WirePayload) {
	builder.PrependByteSlot(1, byte(payloadType), 0)
}
func WireEnvelopeAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(payload), 0)
}
func WireEnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
