// Copyright © 2026 Paxlabs Inc. All rights reserved. SPDX-License-Identifier: LicenseRef-Paxlabs-Matrix-Protocol
// Contact · license@Paxeer.app · legal@Paxeer.app

package main

import (
	"fmt"
	"time"

	"matrix/mcl/ir"
)

// BuildPlan constructs the hand-authored PlanTree the harness walks. It
// exercises all three real MCP servers (fs, fetch, git) plus a parallel
// branch and a sub-dispatch placeholder so plan_validate covers the full
// node-kind matrix.
//
// Concretely, the root is Sequential with 4 children:
//
//  1. Sequential (fs roundtrip): list_directory → write_file → read_text_file
//  2. Parallel (concurrent reads): get_file_info on README.md  (fs)
//     git_status (git)
//  3. ToolCall fetch_url (fetch)
//  4. Step in-skill prompt (no LLM call here; just validates the kind path)
//
// Every ToolCall has an explicit SideEffectClass so the capability gate
// fires at Registry.Get time.
func BuildPlan(intentID, agentURI, skillRef, fsJail, gitRepoDir string) (*ir.PlanTree, error) {
	plan := &ir.PlanTree{
		ID:          synthIntentID("plan|"+intentID, "build"),
		Version:     "mcl/0.1",
		IntentID:    intentID,
		CreatedAt:   time.Now().UTC().Format(time.RFC3339Nano),
		CreatedBy:   agentURI,
		SkillRef:    skillRef,
		ModelDigest: sha256Hex("accounts/fireworks/models/deepseek-v4-pro"),
		Root: ir.PlanNode{
			ID:          "n0",
			Kind:        ir.NodeSequential,
			Description: "Top-level e2e walk",
			Children: []ir.PlanNode{
				{
					ID:          "n1",
					Kind:        ir.NodeSequential,
					Description: "Filesystem roundtrip",
					Children: []ir.PlanNode{
						{
							ID:          "n1a",
							Kind:        ir.NodeToolCall,
							Description: "List sandbox directory",
							ToolCall: &ir.ToolCallPayload{
								ToolRef:         "matrix://tool/mcp/fs/list_directory@2026.1.14",
								Args:            map[string]string{"path": fsJail},
								SideEffectClass: "read",
								TimeoutMs:       10000,
							},
						},
						{
							ID:          "n1b",
							Kind:        ir.NodeToolCall,
							Description: "Write summary file",
							ToolCall: &ir.ToolCallPayload{
								ToolRef: "matrix://tool/mcp/fs/write_file@2026.1.14",
								Args: map[string]string{
									"path":    fsJail + "/SUMMARY.md",
									"content": "# Matrix v1 launch checklist\n\nAuto-generated by mcl-e2e harness via real MCP filesystem-mcp.\n",
								},
								SideEffectClass: "write",
								TimeoutMs:       10000,
							},
						},
						{
							ID:          "n1c",
							Kind:        ir.NodeToolCall,
							Description: "Read summary file back",
							ToolCall: &ir.ToolCallPayload{
								ToolRef:         "matrix://tool/mcp/fs/read_text_file@2026.1.14",
								Args:            map[string]string{"path": fsJail + "/SUMMARY.md"},
								SideEffectClass: "read",
								TimeoutMs:       10000,
							},
						},
					},
				},
				{
					ID:          "n2",
					Kind:        ir.NodeParallel,
					Description: "Parallel reads",
					Children: []ir.PlanNode{
						{
							ID:          "n2a",
							Kind:        ir.NodeToolCall,
							Description: "Stat the SUMMARY.md we just wrote",
							ToolCall: &ir.ToolCallPayload{
								ToolRef:         "matrix://tool/mcp/fs/get_file_info@2026.1.14",
								Args:            map[string]string{"path": fsJail + "/SUMMARY.md"},
								SideEffectClass: "read",
								TimeoutMs:       5000,
							},
						},
						{
							ID:          "n2b",
							Kind:        ir.NodeToolCall,
							Description: "Show git working-tree status",
							ToolCall: &ir.ToolCallPayload{
								ToolRef:         "matrix://tool/mcp/git/git_status@2026.1.14",
								Args:            map[string]string{"repo_path": gitRepoDir},
								SideEffectClass: "read",
								TimeoutMs:       5000,
							},
						},
					},
				},
				{
					ID:          "n3",
					Kind:        ir.NodeToolCall,
					Description: "Fetch a small JSON over the network",
					ToolCall: &ir.ToolCallPayload{
						ToolRef:         "matrix://tool/mcp/fetch/fetch@2025.4.7",
						Args:            map[string]string{"url": "https://example.com/", "max_length": "2000"},
						SideEffectClass: "network",
						TimeoutMs:       30000,
					},
				},
				{
					ID:          "n4",
					Kind:        ir.NodeStep,
					Description: "In-skill summarisation prompt (kind-coverage only)",
					Step: &ir.StepPayload{
						PromptName:      "summarize",
						Inputs:          map[string]string{"goal": "v1 launch checklist"},
						ExpectedOutputs: []string{"summary_text"},
					},
				},
			},
		},
	}

	hash, err := ir.HashPlan(plan)
	if err != nil {
		return nil, fmt.Errorf("plan: hash: %w", err)
	}
	plan.Hash = hash

	if err := ir.ValidatePlan(plan); err != nil {
		return nil, fmt.Errorf("plan: ValidatePlan: %w", err)
	}
	return plan, nil
}

// Copyright © 2026 Paxlabs Inc. All rights reserved.
