// Command specgen compiles the IDE-neutral spec system in spec/ into:
//   - per-IDE pointer/rule files (Cursor, Windsurf, Claude, Codex, Copilot, Kiro)
//   - a human-readable markdown mirror (requirements.md / design.md / tasks.md)
//     rendered from each feature's spec.kvx
//
// The kvx files in spec/ are the SINGLE SOURCE OF TRUTH. Everything specgen
// writes is generated output — do not hand-edit it.
//
// Usage:
//   go run .                 # repo root inferred as ../.. from spec/specgen
//   go run . -root /path     # explicit repo root
//   go run . -check          # fail (non-zero) if any output is stale
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

func main() {
	root := flag.String("root", "", "repo root (default: two levels up from this command)")
	check := flag.Bool("check", false, "verify outputs are up to date; exit non-zero if stale")
	flag.Parse()

	repo := *root
	if repo == "" {
		// spec/specgen -> repo root is two levels up.
		wd, err := os.Getwd()
		must(err)
		repo = filepath.Clean(filepath.Join(wd, "..", ".."))
	}

	w := &writer{check: *check}
	if err := run(repo, w); err != nil {
		fmt.Fprintln(os.Stderr, "specgen:", err)
		os.Exit(1)
	}
	if *check && w.stale > 0 {
		fmt.Fprintf(os.Stderr, "specgen: %d output(s) stale — run `go run .` in spec/specgen and commit\n", w.stale)
		os.Exit(2)
	}
	fmt.Printf("specgen: %d written, %d unchanged%s\n", w.written, w.unchanged, checkSuffix(*check, w.stale))
}

func run(repo string, w *writer) error {
	specDir := filepath.Join(repo, "spec")
	wf, err := ParseFile(filepath.Join(specDir, "workflow.kvx"))
	if err != nil {
		return fmt.Errorf("workflow.kvx: %w", err)
	}
	banner := wf.Str("render", "banner")
	if banner == "" {
		banner = "GENERATED by spec/specgen — DO NOT EDIT."
	}

	// 1. Per-IDE adapter pointer files.
	brief := buildBrief(wf)
	for _, kv := range wf.OrderedKV("adapters", "") {
		label, rel := kv[0], kv[1]
		if rel == "" {
			continue
		}
		if err := w.write(filepath.Join(repo, rel), adapter(label, brief, banner)); err != nil {
			return err
		}
	}

	// 2. Markdown mirror per feature (a feature = a dir under spec/ holding spec.kvx).
	if wf.Bool("render", "markdown_mirror", true) {
		features, err := discoverFeatures(specDir)
		if err != nil {
			return err
		}
		mirrorKiro := wf.Bool("render", "mirror_to_kiro", false)
		for _, fdir := range features {
			if err := renderFeature(repo, specDir, fdir, banner, mirrorKiro, w); err != nil {
				return fmt.Errorf("feature %s: %w", filepath.Base(fdir), err)
			}
		}
	}
	return nil
}

func renderFeature(repo, specDir, fdir, banner string, mirrorKiro bool, w *writer) error {
	f, err := ParseFile(filepath.Join(fdir, "spec.kvx"))
	if err != nil {
		return err
	}
	feature := f.Str("meta", "feature")
	if feature == "" {
		feature = filepath.Base(fdir)
	}

	req := renderRequirements(f, banner)
	des, err := renderDesign(f, fdir, banner)
	if err != nil {
		return err
	}
	tasks, err := renderTasks(f, fdir, banner)
	if err != nil {
		return err
	}

	out := map[string]string{
		filepath.Join(fdir, "requirements.md"): req,
		filepath.Join(fdir, "design.md"):       des,
		filepath.Join(fdir, "tasks.md"):        tasks,
	}
	if mirrorKiro {
		kdir := filepath.Join(repo, ".kiro", "specs", feature)
		out[filepath.Join(kdir, "requirements.md")] = req
		out[filepath.Join(kdir, "design.md")] = des
		out[filepath.Join(kdir, "tasks.md")] = tasks
	}

	paths := make([]string, 0, len(out))
	for p := range out {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		if err := w.write(p, out[p]); err != nil {
			return err
		}
	}
	return nil
}

// discoverFeatures returns the spec/<feature> dirs that contain a spec.kvx.
func discoverFeatures(specDir string) ([]string, error) {
	entries, err := os.ReadDir(specDir)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() || e.Name() == "specgen" {
			continue
		}
		p := filepath.Join(specDir, e.Name())
		if _, err := os.Stat(filepath.Join(p, "spec.kvx")); err == nil {
			out = append(out, p)
		}
	}
	sort.Strings(out)
	return out, nil
}

// writer writes files idempotently (skips unchanged) and supports -check mode
// (reports staleness without writing).
type writer struct {
	check                      bool
	written, unchanged, stale  int
}

func (w *writer) write(path, content string) error {
	old, err := os.ReadFile(path)
	if err == nil && string(old) == content {
		w.unchanged++
		return nil
	}
	if w.check {
		w.stale++
		fmt.Fprintln(os.Stderr, "stale:", path)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	w.written++
	fmt.Fprintln(os.Stderr, "wrote:", path)
	return nil
}

func checkSuffix(check bool, stale int) string {
	if check {
		return fmt.Sprintf(", %d stale", stale)
	}
	return ""
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
