apiVersion: v1
kind: Service
metadata:
  name: {{ include "ion.fullname" . }}
  labels:
    {{- include "ion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ion.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.proxy.port }}
